'use strict';

// #397 credential durability — regression suite for the 2026-07-03 lockout.
//
// The live basic_auth credential existed ONLY inside the (hand-edited)
// Caddyfile: any regeneration lost it, and with an empty config a cutover
// would have emitted an UNGATED ingress. These tests pin the durable
// contract: the credential is adopted into config (read-only on the file),
// every regeneration re-emits the exact hash byte-for-byte, the remote
// plain-HTTP catch-all shape survives regeneration, and a gated file can
// never be regenerated into an ungated one.

const { describe, it, beforeEach, afterEach } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');

const store = require('../lib/store');
const caddy = require('../lib/caddy');
const cutover = require('../scripts/ingress-cutover');

const DEPLOY_DIR = path.join(__dirname, '..', 'deploy');
const TTYD_TEMPLATE = fs.readFileSync(path.join(DEPLOY_DIR, 'com.tangleclaw.ttyd.plist'), 'utf8');
const CADDY_TEMPLATE = fs.readFileSync(path.join(DEPLOY_DIR, 'com.tangleclaw.caddy.plist'), 'utf8');

// Structurally valid bcrypt hashes (BCRYPT_HASH_RE: $2a$NN$ + exactly 53 of [./A-Za-z0-9]).
const HASH_A = '$2a$14$' + 'iTSJI.iBTYRw68PPqXuqqA'.padEnd(53, 'x');
const HASH_B = '$2a$14$' + 'Ku8vN4X33HbByKDyT5f9BO'.padEnd(53, 'y');

/** The live hand-edited shape from the 2026-06-23 incident file. */
function liveShapedCaddyfile(hash = HASH_A, user = 'jason') {
  return [
    '# Generated by TangleClaw (AUTH-1 / lib/caddy.js) — do not hand-edit.',
    '# NOTE (manual): basic_auth + remote HTTP catch-all added by hand.',
    '{',
    '\thttps_port 8443',
    '\thttp_port 8080',
    '\tadmin off',
    '\tauto_https disable_redirects',
    '}',
    '',
    '(tcauth) {',
    '\tbasic_auth {',
    `\t\t${user} ${hash}`,
    '\t}',
    '}',
    '',
    'localhost {',
    '\ttls /c/cert.pem /c/key.pem',
    '\timport tcauth',
    '\treverse_proxy 127.0.0.1:3102',
    '}',
    '',
    'http:// {',
    '\timport tcauth',
    '\treverse_proxy 127.0.0.1:3102',
    '}',
    ''
  ].join('\n');
}

function buildOpts(overrides = {}) {
  return {
    serverPort: 3102,
    certPath: '/c/cert.pem',
    keyPath: '/c/key.pem',
    ...overrides
  };
}

function makeCtx(overrides = {}) {
  return {
    config: {
      serverPort: 3101, ttydPort: 3100,
      caddyHttpsPort: 8443, caddyHttpPort: 8080,
      publicDomain: null,
      ...(overrides.config || {})
    },
    env: {
      caddyPath: '/opt/homebrew/bin/caddy', ttydPath: '/opt/homebrew/bin/ttyd',
      home: '/Users/test', repoDir: '/repo',
      launchdPath: '/usr/bin:/bin', launchAgentsDir: '/Users/test/Library/LaunchAgents',
      uid: 501
    },
    upstreamPort: 3102,
    certPath: '/c/cert.pem', keyPath: '/c/key.pem',
    caddyfilePath: '/Users/test/.tangleclaw/Caddyfile',
    socketPath: '/Users/test/.tangleclaw/run/ttyd.sock',
    ttydTemplate: TTYD_TEMPLATE,
    caddyTemplate: CADDY_TEMPLATE,
    existingCaddyfileText: overrides.existingCaddyfileText !== undefined
      ? overrides.existingCaddyfileText
      : null
  };
}

describe('auth credential durability (#397 / 2026-07-03 lockout)', () => {
  describe('extractBasicAuthCredential', () => {
    it('extracts from the hand-edited (tcauth) snippet shape', () => {
      const cred = caddy.extractBasicAuthCredential(liveShapedCaddyfile());
      assert.deepEqual(cred, { user: 'jason', hash: HASH_A });
    });

    it('extracts from the generated inline shape', () => {
      const content = caddy.buildCaddyfileContent(buildOpts({ basicAuthUser: 'jason', basicAuthHash: HASH_A }));
      const cred = caddy.extractBasicAuthCredential(content);
      assert.deepEqual(cred, { user: 'jason', hash: HASH_A });
    });

    it('returns null when the file has no credential', () => {
      const content = caddy.buildCaddyfileContent(buildOpts());
      assert.equal(caddy.extractBasicAuthCredential(content), null);
    });

    it('returns null when more than one distinct user is present (never guess)', () => {
      const two = liveShapedCaddyfile() + `\n(other) {\n\tbasic_auth {\n\t\talice ${HASH_B}\n\t}\n}\n`;
      assert.equal(caddy.extractBasicAuthCredential(two), null);
    });
  });

  describe('hasRemoteHttpCatchAll', () => {
    it('detects the live http:// catch-all site', () => {
      assert.equal(caddy.hasRemoteHttpCatchAll(liveShapedCaddyfile()), true);
    });

    it('is false for a default generated file', () => {
      const content = caddy.buildCaddyfileContent(buildOpts({ basicAuthUser: 'jason', basicAuthHash: HASH_A }));
      assert.equal(caddy.hasRemoteHttpCatchAll(content), false);
    });
  });

  describe('buildCaddyfileContent — remoteHttpCatchAll', () => {
    it('emits a gated http:// site plus auto_https disable_redirects', () => {
      const content = caddy.buildCaddyfileContent(buildOpts({
        basicAuthUser: 'jason', basicAuthHash: HASH_A, remoteHttpCatchAll: true
      }));
      assert.match(content, /^http:\/\/ \{/m, 'http:// catch-all site missing');
      assert.match(content, /auto_https disable_redirects/, 'auto_https directive missing');
      // The catch-all must be gated: its block carries basic_auth.
      const httpBlock = content.slice(content.indexOf('http:// {'));
      assert.ok(httpBlock.includes('basic_auth'), 'http:// site must be Basic-Auth gated');
      assert.ok(caddy.hasRemoteHttpCatchAll(content));
    });

    it('REFUSES an ungated plain-HTTP catch-all (open-door guard)', () => {
      assert.throws(
        () => caddy.buildCaddyfileContent(buildOpts({ remoteHttpCatchAll: true })),
        /open door/
      );
    });

    it('REGRESSION: output without the option is unchanged (no http:// site, no auto_https)', () => {
      const content = caddy.buildCaddyfileContent(buildOpts({ basicAuthUser: 'jason', basicAuthHash: HASH_A }));
      assert.ok(!/^http:\/\//m.test(content));
      assert.ok(!content.includes('auto_https'));
    });
  });

  describe('byte-for-byte hash re-emission (the lockout regression)', () => {
    it('a credential put through generate → extract → generate survives exactly', () => {
      const first = caddy.buildCaddyfileContent(buildOpts({
        basicAuthUser: 'jason', basicAuthHash: HASH_A, remoteHttpCatchAll: true
      }));
      const cred = caddy.extractBasicAuthCredential(first);
      assert.equal(cred.hash, HASH_A, 'extracted hash must be byte-identical');
      const second = caddy.buildCaddyfileContent(buildOpts({
        basicAuthUser: cred.user, basicAuthHash: cred.hash, remoteHttpCatchAll: true
      }));
      assert.ok(second.includes(`jason ${HASH_A}`), 'regenerated file must carry the exact hash');
      assert.equal(first, second, 'regeneration with the same inputs is deterministic');
    });
  });

  describe('adoptCredentialIntoConfig', () => {
    let tmpDir;

    beforeEach(() => {
      tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-auth-durability-'));
      store._setBasePath(tmpDir);
      store.init();
    });

    afterEach(() => {
      try { store.close(); } catch (_) { /* already closed */ }
      fs.rmSync(tmpDir, { recursive: true, force: true });
    });

    function setConfig(patch) {
      const config = store.config.load();
      Object.assign(config, patch);
      store.config.save(config);
    }

    it('adopts the live credential + remote-HTTP shape into config (read-only on the file)', () => {
      setConfig({ ingressMode: 'caddy' });
      const caddyfilePath = caddy.getCaddyfilePath();
      const original = liveShapedCaddyfile();
      fs.writeFileSync(caddyfilePath, original);

      const result = caddy.adoptCredentialIntoConfig();
      assert.equal(result.adopted, true);
      assert.equal(result.user, 'jason');
      assert.equal(result.remoteHttp, true);

      const config = store.config.load();
      assert.equal(config.authEnabled, true);
      assert.equal(config.basicAuthUser, 'jason');
      assert.equal(config.basicAuthHash, HASH_A);
      assert.equal(config.caddyRemoteHttp, true);
      // READ-ONLY on the Caddyfile — byte-identical after adoption.
      assert.equal(fs.readFileSync(caddyfilePath, 'utf8'), original);
    });

    it('never overwrites an existing config credential', () => {
      setConfig({ ingressMode: 'caddy', authEnabled: true, basicAuthUser: 'jason', basicAuthHash: HASH_B });
      fs.writeFileSync(caddy.getCaddyfilePath(), liveShapedCaddyfile(HASH_A));

      const result = caddy.adoptCredentialIntoConfig();
      assert.equal(result.adopted, false);
      assert.equal(result.reason, 'config-already-has-credential');
      assert.equal(store.config.load().basicAuthHash, HASH_B, 'config hash untouched');
    });

    it('no-ops outside caddy mode unless requireCaddyMode:false (cutover path)', () => {
      setConfig({ ingressMode: 'direct' });
      fs.writeFileSync(caddy.getCaddyfilePath(), liveShapedCaddyfile());

      assert.equal(caddy.adoptCredentialIntoConfig().adopted, false);
      const forced = caddy.adoptCredentialIntoConfig({ requireCaddyMode: false });
      assert.equal(forced.adopted, true, 'cutover-path override must adopt');
    });

    it('no-ops on a missing Caddyfile and on an ambiguous multi-user file', () => {
      setConfig({ ingressMode: 'caddy' });
      assert.equal(caddy.adoptCredentialIntoConfig().reason, 'no-caddyfile');

      const two = liveShapedCaddyfile() + `\n(other) {\n\tbasic_auth {\n\t\talice ${HASH_B}\n\t}\n}\n`;
      fs.writeFileSync(caddy.getCaddyfilePath(), two);
      assert.equal(caddy.adoptCredentialIntoConfig().reason, 'no-unambiguous-credential');
      assert.equal(store.config.load().basicAuthUser, null);
    });

    it('is idempotent — a second boot adopts nothing further', () => {
      setConfig({ ingressMode: 'caddy' });
      fs.writeFileSync(caddy.getCaddyfilePath(), liveShapedCaddyfile());
      assert.equal(caddy.adoptCredentialIntoConfig().adopted, true);
      assert.equal(caddy.adoptCredentialIntoConfig().adopted, false);
    });
  });

  describe('planCutover — refuse-to-ungate guard', () => {
    it('THROWS when the existing Caddyfile is gated but config has no credential', () => {
      assert.throws(
        () => cutover.planCutover('caddy', makeCtx({ existingCaddyfileText: liveShapedCaddyfile() })),
        /UNGATED/
      );
    });

    it('proceeds when config carries the credential (and re-emits the exact hash)', () => {
      const plan = cutover.planCutover('caddy', makeCtx({
        config: { authEnabled: true, basicAuthUser: 'jason', basicAuthHash: HASH_A, caddyRemoteHttp: true },
        existingCaddyfileText: liveShapedCaddyfile()
      }));
      assert.ok(plan.caddyfile.content.includes(`jason ${HASH_A}`), 'exact hash re-emitted');
      assert.ok(caddy.hasRemoteHttpCatchAll(plan.caddyfile.content), 'remote catch-all preserved');
    });

    it('still allows an ungated plan on a fresh install (no existing file)', () => {
      const plan = cutover.planCutover('caddy', makeCtx({ existingCaddyfileText: null }));
      assert.ok(plan.caddyfile.content, 'fresh-install ungated Caddyfile still plans');
      assert.ok(!plan.caddyfile.content.includes('basic_auth'));
    });

    it('also allows regenerating an already-ungated file without auth (pre-existing behavior)', () => {
      const ungated = caddy.buildCaddyfileContent(buildOpts());
      const plan = cutover.planCutover('caddy', makeCtx({ existingCaddyfileText: ungated }));
      assert.ok(plan.caddyfile.content);
    });
  });
});
