'use strict';

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { setLevel } = require('../lib/logger');
const store = require('../lib/store');

setLevel('error');

let caddy;

/**
 * Write a shell stub named "caddy" into stubDir that simulates the real binary
 * for the two subcommands this module calls: `version` and `validate`.
 * `validate` fails (exit 1, stderr) when the target Caddyfile contains the
 * token INVALID, so the failure path is exercisable without a real Caddy.
 * @param {string} stubDir
 */
function writeCaddyStub(stubDir) {
  const script = `#!/bin/bash
set -e
case "$1" in
  version)
    echo "v2.8.4-stub h1:deadbeef"
    exit 0
    ;;
  validate)
    # Expected: validate --adapter caddyfile --config <path>
    cfg=""
    while [ $# -gt 0 ]; do
      if [ "$1" = "--config" ]; then shift; cfg="$1"; fi
      shift
    done
    if [ -z "$cfg" ] || [ ! -f "$cfg" ]; then
      echo "stub: missing/unreadable config" >&2
      exit 1
    fi
    if grep -q INVALID "$cfg"; then
      echo "stub: adapting caddyfile: invalid directive" >&2
      exit 1
    fi
    echo "Valid configuration"
    exit 0
    ;;
  hash-password)
    # Real caddy reads the plaintext from stdin (one line). Echo a bcrypt-shaped
    # hash so hashPassword's shape check passes; two sentinels exercise the
    # failure paths without a real Caddy.
    read -r pw
    case "$pw" in
      *FAILHASH*) echo "boom: cannot hash" >&2; exit 1 ;;
      *BADHASH*)  echo "not-a-bcrypt-hash"; exit 0 ;;
      *) echo '\$2a\$14\$abcdefghijklmnopqrstuv0123456789ABCDEFGHIJKLMNOPQRSTU'; exit 0 ;;
    esac
    ;;
esac
echo "caddy stub: unknown args: $*" >&2
exit 1
`;
  fs.writeFileSync(path.join(stubDir, 'caddy'), script, { mode: 0o755 });
}

describe('caddy', () => {
  let tmpDir;
  let stubDir;
  let baseDir;
  let origPath;

  before(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-caddy-'));
    stubDir = path.join(tmpDir, 'bin');
    baseDir = path.join(tmpDir, 'tangleclaw');
    fs.mkdirSync(stubDir, { recursive: true });
    writeCaddyStub(stubDir);

    origPath = process.env.PATH;
    process.env.PATH = stubDir + path.delimiter + (origPath || '');

    store._setBasePath(baseDir);
    store.init();

    caddy = require('../lib/caddy');
  });

  after(() => {
    process.env.PATH = origPath;
    store.close();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  describe('getCaddyfilePath', () => {
    it('returns <basePath>/Caddyfile', () => {
      assert.equal(caddy.getCaddyfilePath(), path.join(baseDir, 'Caddyfile'));
    });
  });

  describe('detectCaddy', () => {
    it('reports available: true and parses the version when caddy stub is on PATH', () => {
      const r = caddy.detectCaddy();
      assert.equal(r.available, true);
      assert.equal(r.error, null);
      assert.equal(r.version, 'v2.8.4-stub');
    });

    it('reports available: false when caddy is not on PATH', () => {
      const saved = process.env.PATH;
      process.env.PATH = path.join(tmpDir, 'nonexistent-dir');
      try {
        const r = caddy.detectCaddy();
        assert.equal(r.available, false);
        assert.equal(r.version, null);
        assert.match(r.error, /not found on PATH/);
      } finally {
        process.env.PATH = saved;
      }
    });
  });

  describe('buildCaddyfileContent', () => {
    const opts = { serverPort: 3101, certPath: '/c/cert.pem', keyPath: '/c/key.pem' };

    it('requires serverPort', () => {
      assert.throws(() => caddy.buildCaddyfileContent({ certPath: '/c/cert.pem', keyPath: '/c/key.pem' }), /serverPort/);
    });

    it('requires certPath and keyPath', () => {
      assert.throws(() => caddy.buildCaddyfileContent({ serverPort: 3101 }), /certPath and keyPath/);
    });

    it('emits a localhost site that reuses the mkcert cert and proxies to the TC port', () => {
      const out = caddy.buildCaddyfileContent(opts);
      assert.match(out, /^localhost \{$/m);
      assert.match(out, /\ttls \/c\/cert\.pem \/c\/key\.pem/);
      assert.match(out, /\treverse_proxy 127\.0\.0\.1:3101/);
      assert.match(out, /admin off/);
      // generated-file header so a human knows not to hand-edit
      assert.match(out, /Generated by TangleClaw/);
    });

    it('omits any public/ACME block when publicDomain is not set', () => {
      const out = caddy.buildCaddyfileContent(opts);
      // exactly one site block (the localhost one) → one reverse_proxy line
      assert.equal((out.match(/reverse_proxy/g) || []).length, 1);
    });

    it('emits a second ACME site block (no tls directive) when publicDomain is set', () => {
      const out = caddy.buildCaddyfileContent({ ...opts, publicDomain: 'tc.example.com' });
      assert.match(out, /^tc\.example\.com \{$/m);
      assert.equal((out.match(/reverse_proxy/g) || []).length, 2);
      // the public block must NOT carry a tls directive (so Caddy auto-ACMEs it)
      const publicBlock = out.slice(out.indexOf('tc.example.com {'));
      assert.doesNotMatch(publicBlock, /\ttls /);
    });

    it('honors a custom localSite hostname', () => {
      const out = caddy.buildCaddyfileContent({ ...opts, localSite: 'tc.local' });
      assert.match(out, /^tc\.local \{$/m);
    });

    it('defaults to non-privileged global ports (8443/8080)', () => {
      const out = caddy.buildCaddyfileContent(opts);
      assert.match(out, /\thttps_port 8443/);
      assert.match(out, /\thttp_port 8080/);
    });

    it('honors custom https/http ports (e.g. 443/80 for a root daemon)', () => {
      const out = caddy.buildCaddyfileContent({ ...opts, httpsPort: 443, httpPort: 80 });
      assert.match(out, /\thttps_port 443/);
      assert.match(out, /\thttp_port 80/);
      // the local site stays a bare hostname; the port comes from the global directive
      assert.match(out, /^localhost \{$/m);
    });

    // AUTH-2 — basic_auth gate (bcrypt hash, never plaintext). The hash below is
    // a real bcrypt-shaped token; the stubbed `caddy validate` doesn't check it,
    // real `caddy validate` syntax is exercised in verification.
    const AUTH = { basicAuthUser: 'jason', basicAuthHash: '$2a$14$wThequ7Ahgg6dT3KZ8x9KuOk0o0gO3pQF1m6Xq9r4tFz8sJgVn3bC' };

    it('emits no basic_auth gate by default (ungated ingress unchanged)', () => {
      const out = caddy.buildCaddyfileContent(opts);
      assert.doesNotMatch(out, /basic_auth/);
      assert.doesNotMatch(out, /@protected/);
    });

    it('injects a basic_auth gate over the local site when user+hash are set', () => {
      const out = caddy.buildCaddyfileContent({ ...opts, ...AUTH });
      assert.match(out, /\t@protected not path \/api\/health/);
      assert.match(out, /\tbasic_auth @protected \{/);
      assert.match(out, /\t\tjason \$2a\$14\$wThequ7Ahgg6dT3KZ8x9KuOk0o0gO3pQF1m6Xq9r4tFz8sJgVn3bC/);
      // basic_auth must precede reverse_proxy so the gate runs before the upstream.
      assert.ok(out.indexOf('basic_auth') < out.indexOf('reverse_proxy'));
    });

    it('keeps /api/health out of the gate (health probe needs no credentials)', () => {
      const out = caddy.buildCaddyfileContent({ ...opts, ...AUTH });
      // The gate references "@protected = not path /api/health", so health is open.
      assert.match(out, /@protected not path \/api\/health/);
    });

    it('gates the public ACME site too when publicDomain + auth are set', () => {
      const out = caddy.buildCaddyfileContent({ ...opts, ...AUTH, publicDomain: 'tc.example.com' });
      assert.equal((out.match(/basic_auth @protected \{/g) || []).length, 2);
      const publicBlock = out.slice(out.indexOf('tc.example.com {'));
      assert.match(publicBlock, /basic_auth @protected/);
    });

    it('throws when only the user is set (fail closed — no half-set gate)', () => {
      assert.throws(() => caddy.buildCaddyfileContent({ ...opts, basicAuthUser: 'jason' }),
        /must be set together/);
    });

    it('throws when only the hash is set (fail closed — no half-set gate)', () => {
      assert.throws(() => caddy.buildCaddyfileContent({ ...opts, basicAuthHash: AUTH.basicAuthHash }),
        /must be set together/);
    });

    it('still integrity-stamps a gated Caddyfile so regeneration owns the auth block (#397 item 3)', () => {
      const out = caddy.buildCaddyfileContent({ ...opts, ...AUTH });
      assert.equal(caddy.isGeneratedCaddyfile(out), true);
    });
  });

  describe('writeCaddyfile', () => {
    it('writes the generated content to the default path and returns it', () => {
      const r = caddy.writeCaddyfile({ serverPort: 3101, certPath: '/c/cert.pem', keyPath: '/c/key.pem' });
      assert.equal(r.caddyfilePath, path.join(baseDir, 'Caddyfile'));
      assert.ok(fs.existsSync(r.caddyfilePath));
      assert.equal(fs.readFileSync(r.caddyfilePath, 'utf8'), r.content);
      assert.match(r.content, /reverse_proxy 127\.0\.0\.1:3101/);
    });

    it('creates the destination directory if missing', () => {
      const nested = path.join(tmpDir, 'nested', 'dir', 'Caddyfile');
      const r = caddy.writeCaddyfile({ caddyfilePath: nested, serverPort: 3200, certPath: '/c/cert.pem', keyPath: '/c/key.pem' });
      assert.ok(fs.existsSync(nested));
      assert.match(r.content, /reverse_proxy 127\.0\.0\.1:3200/);
    });
  });

  describe('getTtydSocketPath', () => {
    it('returns <basePath>/run/ttyd.sock', () => {
      assert.equal(caddy.getTtydSocketPath(), path.join(baseDir, 'run', 'ttyd.sock'));
    });
  });

  describe('ttydConnectTarget', () => {
    it('targets the TCP port in direct mode (default)', () => {
      const t = caddy.ttydConnectTarget({ ingressMode: 'direct', ttydPort: 3100 });
      assert.equal(t.socketPath, undefined);
      assert.equal(t.host, '127.0.0.1');
      assert.equal(t.port, 3100);
      assert.equal(t.hostHeader, '127.0.0.1:3100');
    });

    it('defaults to port 3100 when ttydPort is unset', () => {
      const t = caddy.ttydConnectTarget({});
      assert.equal(t.port, 3100);
      assert.equal(t.hostHeader, '127.0.0.1:3100');
    });

    it('respects a custom ttydPort in direct mode', () => {
      const t = caddy.ttydConnectTarget({ ingressMode: 'direct', ttydPort: 3105 });
      assert.equal(t.port, 3105);
      assert.equal(t.hostHeader, '127.0.0.1:3105');
    });

    it('targets the Unix socket in caddy mode', () => {
      const t = caddy.ttydConnectTarget({ ingressMode: 'caddy', ttydPort: 3100 });
      assert.equal(t.socketPath, caddy.getTtydSocketPath());
      assert.equal(t.host, undefined);
      assert.equal(t.port, undefined);
      assert.equal(t.hostHeader, 'localhost');
    });

    it('tolerates a null/undefined config (direct defaults)', () => {
      const t = caddy.ttydConnectTarget();
      assert.equal(t.port, 3100);
      assert.equal(t.socketPath, undefined);
    });
  });

  describe('validateCaddyfile', () => {
    it('returns ok: false when the Caddyfile does not exist', () => {
      const r = caddy.validateCaddyfile(path.join(tmpDir, 'no-such-Caddyfile'));
      assert.equal(r.ok, false);
      assert.match(r.error, /not found/);
    });

    it('returns ok: true for a valid generated Caddyfile', () => {
      const cfg = path.join(tmpDir, 'valid-Caddyfile');
      caddy.writeCaddyfile({ caddyfilePath: cfg, serverPort: 3101, certPath: '/c/cert.pem', keyPath: '/c/key.pem' });
      const r = caddy.validateCaddyfile(cfg);
      assert.equal(r.ok, true);
      assert.equal(r.error, null);
    });

    it('returns ok: false with the validator detail when the config is invalid', () => {
      const cfg = path.join(tmpDir, 'invalid-Caddyfile');
      fs.writeFileSync(cfg, 'localhost {\n\tINVALID directive\n}\n');
      const r = caddy.validateCaddyfile(cfg);
      assert.equal(r.ok, false);
      assert.match(r.error, /invalid directive/);
    });

    it('returns ok: false when caddy is not on PATH', () => {
      const cfg = path.join(tmpDir, 'present-Caddyfile');
      fs.writeFileSync(cfg, 'localhost {\n}\n');
      const saved = process.env.PATH;
      process.env.PATH = path.join(tmpDir, 'nonexistent-dir');
      try {
        const r = caddy.validateCaddyfile(cfg);
        assert.equal(r.ok, false);
        assert.match(r.error, /not available/);
      } finally {
        process.env.PATH = saved;
      }
    });
  });

  // #397 bug 3 — clobber guard helper (integrity-verified, not just prefix-matched).
  describe('isGeneratedCaddyfile', () => {
    const gen = () => caddy.buildCaddyfileContent({ serverPort: 3101, certPath: '/c/cert.pem', keyPath: '/c/key.pem' });

    it('returns true for a freshly generated Caddyfile (body hashes to the stamp)', () => {
      assert.equal(caddy.isGeneratedCaddyfile(gen()), true);
    });
    it('returns false when the body is hand-edited but the header line is kept (the live-system case)', () => {
      // Operator appends a basic_auth block but leaves the generated header in place.
      const tampered = gen().replace(/\}\n$/, '\tbasic_auth { jason $2a$hash }\n}\n');
      assert.notEqual(tampered, gen());
      assert.equal(caddy.isGeneratedCaddyfile(tampered), false);
    });
    it('returns false for a legacy generated header with no sha256 stamp', () => {
      const legacy = '# Generated by TangleClaw (AUTH-1 / lib/caddy.js) — do not hand-edit.\nlocalhost {\n}\n';
      assert.equal(caddy.isGeneratedCaddyfile(legacy), false);
    });
    it('returns false when leading blank lines shift the header off line 0', () => {
      assert.equal(caddy.isGeneratedCaddyfile('\n\n' + gen()), false);
    });
    it('returns false for a hand-edited Caddyfile (no marker at all)', () => {
      assert.equal(caddy.isGeneratedCaddyfile('localhost {\n\tbasic_auth { jason $2a$hash }\n}\n'), false);
    });
    it('returns false for non-string / single-line input', () => {
      assert.equal(caddy.isGeneratedCaddyfile(null), false);
      assert.equal(caddy.isGeneratedCaddyfile(undefined), false);
      assert.equal(caddy.isGeneratedCaddyfile('# Generated by TangleClaw sha256:' + 'a'.repeat(64)), false);
    });
  });

  // #397 bug 1 — cert staging into the non-TCC store dir.
  describe('getStagedCertsDir', () => {
    it('returns <basePath>/certs', () => {
      assert.equal(caddy.getStagedCertsDir(), path.join(baseDir, 'certs'));
    });
  });

  describe('stageCert', () => {
    let srcDir;
    before(() => {
      srcDir = path.join(tmpDir, 'src-certs');
      fs.mkdirSync(srcDir, { recursive: true });
    });

    it('copies cert + key into the staging dir and returns the staged paths', () => {
      const srcCert = path.join(srcDir, 'cert.pem');
      const srcKey = path.join(srcDir, 'key.pem');
      fs.writeFileSync(srcCert, 'CERT-A');
      fs.writeFileSync(srcKey, 'KEY-A');
      const staged = caddy.stageCert(srcCert, srcKey);
      assert.equal(staged.certPath, path.join(baseDir, 'certs', 'cert.pem'));
      assert.equal(staged.keyPath, path.join(baseDir, 'certs', 'key.pem'));
      assert.equal(fs.readFileSync(staged.certPath, 'utf8'), 'CERT-A');
      assert.equal(fs.readFileSync(staged.keyPath, 'utf8'), 'KEY-A');
    });

    it('writes the key 0600 and the cert 0644', () => {
      const srcCert = path.join(srcDir, 'cert.pem');
      const srcKey = path.join(srcDir, 'key.pem');
      fs.writeFileSync(srcCert, 'CERT-B');
      fs.writeFileSync(srcKey, 'KEY-B');
      const staged = caddy.stageCert(srcCert, srcKey);
      assert.equal(fs.statSync(staged.keyPath).mode & 0o777, 0o600);
      assert.equal(fs.statSync(staged.certPath).mode & 0o777, 0o644);
    });

    it('overwrites on re-stage so cert rotation propagates', () => {
      const srcCert = path.join(srcDir, 'cert.pem');
      const srcKey = path.join(srcDir, 'key.pem');
      fs.writeFileSync(srcCert, 'ROTATED');
      fs.writeFileSync(srcKey, 'ROTATED-KEY');
      const staged = caddy.stageCert(srcCert, srcKey);
      assert.equal(fs.readFileSync(staged.certPath, 'utf8'), 'ROTATED');
    });

    it('no-ops the copy when the source already IS the staged file (self-copy safe)', () => {
      // Mirrors the generate path, which writes straight into the staging dir.
      const stagedDir = caddy.getStagedCertsDir();
      const selfCert = path.join(stagedDir, 'cert.pem');
      const selfKey = path.join(stagedDir, 'key.pem');
      fs.writeFileSync(selfCert, 'SELF');
      fs.writeFileSync(selfKey, 'SELF-KEY');
      const staged = caddy.stageCert(selfCert, selfKey);
      assert.equal(staged.certPath, selfCert);
      assert.equal(fs.readFileSync(staged.certPath, 'utf8'), 'SELF');
    });

    it('throws when cert or key path is missing', () => {
      assert.throws(() => caddy.stageCert(null, '/k'), /required/);
      assert.throws(() => caddy.stageCert('/c', null), /required/);
    });
  });

  // AUTH-2 — first-run admin credential helpers.
  describe('validateAdminPassword', () => {
    it('accepts a strong password', () => {
      const r = caddy.validateAdminPassword('a-strong-passphrase-42', 'admin');
      assert.equal(r.ok, true);
      assert.equal(r.error, null);
    });

    it('rejects an empty / non-string password', () => {
      assert.equal(caddy.validateAdminPassword('', 'admin').ok, false);
      assert.equal(caddy.validateAdminPassword(undefined, 'admin').ok, false);
      assert.equal(caddy.validateAdminPassword(12345, 'admin').ok, false);
    });

    it('enforces the 12-character minimum at the boundary', () => {
      assert.equal(caddy.validateAdminPassword('twelvechars!', 'admin').ok, true);   // exactly 12
      const r = caddy.validateAdminPassword('elevenchar!', 'admin');                 // 11
      assert.equal(r.ok, false);
      assert.match(r.error, /at least 12/);
    });

    it('rejects control characters (they would be truncated by stdin hashing)', () => {
      assert.equal(caddy.validateAdminPassword('abc\ndef-ghijkl', 'admin').ok, false);
      assert.equal(caddy.validateAdminPassword('abc\tdef-ghijkl', 'admin').ok, false);
    });

    it('rejects a known-weak password (denylist, case-insensitive)', () => {
      const r = caddy.validateAdminPassword('PasswordPassword', 'admin');
      assert.equal(r.ok, false);
      assert.match(r.error, /too common/);
    });

    it('rejects a password that contains the username (case-insensitive)', () => {
      const r = caddy.validateAdminPassword('JasonsLongPassword', 'jason');
      assert.equal(r.ok, false);
      assert.match(r.error, /username/);
    });

    it('ignores the username rule when no username is given', () => {
      assert.equal(caddy.validateAdminPassword('a-strong-passphrase-42').ok, true);
    });
  });

  describe('hashPassword', () => {
    it('returns the bcrypt hash from `caddy hash-password`', () => {
      const hash = caddy.hashPassword('a-strong-passphrase-42');
      assert.match(hash, /^\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53}$/);
    });

    it('throws on an empty plaintext', () => {
      assert.throws(() => caddy.hashPassword(''), /non-empty/);
    });

    it('throws when caddy exits non-zero', () => {
      assert.throws(() => caddy.hashPassword('FAILHASH-please-12'), /hash-password failed/);
    });

    it('throws when caddy returns a non-bcrypt value', () => {
      assert.throws(() => caddy.hashPassword('BADHASH-please-123'), /did not return a bcrypt hash/);
    });
  });
});
