'use strict';

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { setLevel } = require('../lib/logger');
const store = require('../lib/store');

setLevel('error');

let caddy;

/**
 * Write a shell stub named "caddy" into stubDir that simulates the real binary
 * for the two subcommands this module calls: `version` and `validate`.
 * `validate` fails (exit 1, stderr) when the target Caddyfile contains the
 * token INVALID, so the failure path is exercisable without a real Caddy.
 * @param {string} stubDir
 */
function writeCaddyStub(stubDir) {
  const script = `#!/bin/bash
set -e
case "$1" in
  version)
    echo "v2.8.4-stub h1:deadbeef"
    exit 0
    ;;
  validate)
    # Expected: validate --adapter caddyfile --config <path>
    cfg=""
    while [ $# -gt 0 ]; do
      if [ "$1" = "--config" ]; then shift; cfg="$1"; fi
      shift
    done
    if [ -z "$cfg" ] || [ ! -f "$cfg" ]; then
      echo "stub: missing/unreadable config" >&2
      exit 1
    fi
    if grep -q INVALID "$cfg"; then
      echo "stub: adapting caddyfile: invalid directive" >&2
      exit 1
    fi
    echo "Valid configuration"
    exit 0
    ;;
esac
echo "caddy stub: unknown args: $*" >&2
exit 1
`;
  fs.writeFileSync(path.join(stubDir, 'caddy'), script, { mode: 0o755 });
}

describe('caddy', () => {
  let tmpDir;
  let stubDir;
  let baseDir;
  let origPath;

  before(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-caddy-'));
    stubDir = path.join(tmpDir, 'bin');
    baseDir = path.join(tmpDir, 'tangleclaw');
    fs.mkdirSync(stubDir, { recursive: true });
    writeCaddyStub(stubDir);

    origPath = process.env.PATH;
    process.env.PATH = stubDir + path.delimiter + (origPath || '');

    store._setBasePath(baseDir);
    store.init();

    caddy = require('../lib/caddy');
  });

  after(() => {
    process.env.PATH = origPath;
    store.close();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  describe('getCaddyfilePath', () => {
    it('returns <basePath>/Caddyfile', () => {
      assert.equal(caddy.getCaddyfilePath(), path.join(baseDir, 'Caddyfile'));
    });
  });

  describe('detectCaddy', () => {
    it('reports available: true and parses the version when caddy stub is on PATH', () => {
      const r = caddy.detectCaddy();
      assert.equal(r.available, true);
      assert.equal(r.error, null);
      assert.equal(r.version, 'v2.8.4-stub');
    });

    it('reports available: false when caddy is not on PATH', () => {
      const saved = process.env.PATH;
      process.env.PATH = path.join(tmpDir, 'nonexistent-dir');
      try {
        const r = caddy.detectCaddy();
        assert.equal(r.available, false);
        assert.equal(r.version, null);
        assert.match(r.error, /not found on PATH/);
      } finally {
        process.env.PATH = saved;
      }
    });
  });

  describe('buildCaddyfileContent', () => {
    const opts = { serverPort: 3101, certPath: '/c/cert.pem', keyPath: '/c/key.pem' };

    it('requires serverPort', () => {
      assert.throws(() => caddy.buildCaddyfileContent({ certPath: '/c/cert.pem', keyPath: '/c/key.pem' }), /serverPort/);
    });

    it('requires certPath and keyPath', () => {
      assert.throws(() => caddy.buildCaddyfileContent({ serverPort: 3101 }), /certPath and keyPath/);
    });

    it('emits a localhost site that reuses the mkcert cert and proxies to the TC port', () => {
      const out = caddy.buildCaddyfileContent(opts);
      assert.match(out, /^localhost \{$/m);
      assert.match(out, /\ttls \/c\/cert\.pem \/c\/key\.pem/);
      assert.match(out, /\treverse_proxy 127\.0\.0\.1:3101/);
      assert.match(out, /admin off/);
      // generated-file header so a human knows not to hand-edit
      assert.match(out, /Generated by TangleClaw/);
    });

    it('omits any public/ACME block when publicDomain is not set', () => {
      const out = caddy.buildCaddyfileContent(opts);
      // exactly one site block (the localhost one) → one reverse_proxy line
      assert.equal((out.match(/reverse_proxy/g) || []).length, 1);
    });

    it('emits a second ACME site block (no tls directive) when publicDomain is set', () => {
      const out = caddy.buildCaddyfileContent({ ...opts, publicDomain: 'tc.example.com' });
      assert.match(out, /^tc\.example\.com \{$/m);
      assert.equal((out.match(/reverse_proxy/g) || []).length, 2);
      // the public block must NOT carry a tls directive (so Caddy auto-ACMEs it)
      const publicBlock = out.slice(out.indexOf('tc.example.com {'));
      assert.doesNotMatch(publicBlock, /\ttls /);
    });

    it('honors a custom localSite label (slice-3 non-privileged port seam)', () => {
      const out = caddy.buildCaddyfileContent({ ...opts, localSite: 'localhost:8443' });
      assert.match(out, /^localhost:8443 \{$/m);
    });
  });

  describe('writeCaddyfile', () => {
    it('writes the generated content to the default path and returns it', () => {
      const r = caddy.writeCaddyfile({ serverPort: 3101, certPath: '/c/cert.pem', keyPath: '/c/key.pem' });
      assert.equal(r.caddyfilePath, path.join(baseDir, 'Caddyfile'));
      assert.ok(fs.existsSync(r.caddyfilePath));
      assert.equal(fs.readFileSync(r.caddyfilePath, 'utf8'), r.content);
      assert.match(r.content, /reverse_proxy 127\.0\.0\.1:3101/);
    });

    it('creates the destination directory if missing', () => {
      const nested = path.join(tmpDir, 'nested', 'dir', 'Caddyfile');
      const r = caddy.writeCaddyfile({ caddyfilePath: nested, serverPort: 3200, certPath: '/c/cert.pem', keyPath: '/c/key.pem' });
      assert.ok(fs.existsSync(nested));
      assert.match(r.content, /reverse_proxy 127\.0\.0\.1:3200/);
    });
  });

  describe('validateCaddyfile', () => {
    it('returns ok: false when the Caddyfile does not exist', () => {
      const r = caddy.validateCaddyfile(path.join(tmpDir, 'no-such-Caddyfile'));
      assert.equal(r.ok, false);
      assert.match(r.error, /not found/);
    });

    it('returns ok: true for a valid generated Caddyfile', () => {
      const cfg = path.join(tmpDir, 'valid-Caddyfile');
      caddy.writeCaddyfile({ caddyfilePath: cfg, serverPort: 3101, certPath: '/c/cert.pem', keyPath: '/c/key.pem' });
      const r = caddy.validateCaddyfile(cfg);
      assert.equal(r.ok, true);
      assert.equal(r.error, null);
    });

    it('returns ok: false with the validator detail when the config is invalid', () => {
      const cfg = path.join(tmpDir, 'invalid-Caddyfile');
      fs.writeFileSync(cfg, 'localhost {\n\tINVALID directive\n}\n');
      const r = caddy.validateCaddyfile(cfg);
      assert.equal(r.ok, false);
      assert.match(r.error, /invalid directive/);
    });

    it('returns ok: false when caddy is not on PATH', () => {
      const cfg = path.join(tmpDir, 'present-Caddyfile');
      fs.writeFileSync(cfg, 'localhost {\n}\n');
      const saved = process.env.PATH;
      process.env.PATH = path.join(tmpDir, 'nonexistent-dir');
      try {
        const r = caddy.validateCaddyfile(cfg);
        assert.equal(r.ok, false);
        assert.match(r.error, /not available/);
      } finally {
        process.env.PATH = saved;
      }
    });
  });
});
