'use strict';

// #1394 — the Caddyfile security divergence check.
//
// Two layers, deliberately split.
//
// The PROPERTY layer runs everywhere. It asserts against committed `caddy
// adapt` JSON generated by real Caddy from real generator output
// (`scripts/regen-caddy-adapt-fixtures.js`), so the logic that decides what
// counts as drift is covered on CI, which has no `caddy` binary. A hand-written
// approximation of adapt's JSON would agree with whatever the code already does
// and prove nothing — the whole point of this check is that Caddy's parser is
// the only parser.
//
// The INTEGRATION layer shells out to `caddy` and skips honestly when it is
// absent. It also re-derives every fixture and compares, so a Caddy release
// that changes the JSON shape fails here on a developer machine instead of
// leaving the committed snapshot quietly describing a Caddy nobody runs.

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { setLevel } = require('../lib/logger');

setLevel('error');

const caddy = require('../lib/caddy');
const drift = require('../lib/caddy-drift');
const store = require('../lib/store');
const { withoutCaddy } = require('./_caddy-stub');
const {
  FIXTURE_CADDYFILES,
  fixtureConfig,
  FIXTURE_HASH,
  FIXTURE_TAILNET_HOST,
  FIXTURE_HTTPS_PORT,
  FIXTURE_SERVER_PORT,
  FIXTURE_STRAY_PORT
} = require('./_caddy-drift-fixtures');

const FIXTURE_DIR = path.join(__dirname, 'fixtures');
const CADDY_AVAILABLE = caddy.detectCaddy().available;

/**
 * Load a committed `caddy adapt` fixture.
 * @param {string} name - Fixture name, e.g. `'hand-edited'`.
 * @returns {object} Adapted Caddy JSON.
 */
function adapted(name) {
  return JSON.parse(fs.readFileSync(path.join(FIXTURE_DIR, `caddy-adapt-${name}.json`), 'utf8'));
}

/**
 * Summarize a committed fixture.
 * @param {string} name - Fixture name.
 * @returns {{ sites: Map<string, object>, listeners: Map<string, object> }}
 */
function summarize(name) {
  return drift.summarizeConfig(adapted(name));
}

/** @returns {object} A lease row shaped like `store.portLeases` returns. */
function lease(port, reach, project = 'TangleBrain', service = 'gui', host = 'localhost') {
  return { port, reach, project, service, host };
}

describe('caddy-drift — reading the adapted config', () => {
  it('keys sites by listen address and host, never by server name', () => {
    // The observed fact this defends: adding one hand-written block moves the
    // HTTPS listener from srv1 to srv2. A check keyed to the NAME would have
    // silently started asserting against a different server.
    const cleanNames = Object.keys(adapted('generated').apps.http.servers);
    const editedNames = Object.keys(adapted('hand-edited').apps.http.servers);
    const nameOf = (config, listenAddr) => Object.entries(config.apps.http.servers)
      .find(([, srv]) => srv.listen.includes(listenAddr))[0];
    assert.notEqual(
      nameOf(adapted('generated'), `:${FIXTURE_HTTPS_PORT}`),
      nameOf(adapted('hand-edited'), `:${FIXTURE_HTTPS_PORT}`),
      'fixture precondition: the hand-edit must rename the HTTPS server'
    );
    assert.ok(cleanNames.length < editedNames.length);

    // The site key, by contrast, is stable across exactly that rename.
    const clean = summarize('generated').sites;
    const edited = summarize('hand-edited').sites;
    const httpsKey = [...clean.keys()].find((k) => k.startsWith(`:${FIXTURE_HTTPS_PORT}|`));
    assert.ok(httpsKey, 'the generated file has an HTTPS site');
    assert.ok(edited.has(httpsKey), 'the same site keeps its key after the rename');
  });

  it('counts a gate that is a SIBLING route of the proxy it protects', () => {
    // TangleClaw's generator emits the gate and the proxy as two sibling routes,
    // so the proxy's own handler chain contains no authentication handler. A
    // walk that asked "was this proxy gated in its own chain" would report the
    // generator's own output as open.
    for (const site of summarize('generated').sites.values()) {
      assert.ok(site.gates.length > 0, `${site.key} should read as gated`);
    }
  });

  it('ignores a pure redirect block, which proxies nothing to gate', () => {
    const sites = summarize('generated').sites;
    const httpSite = [...sites.keys()].filter((k) => k.startsWith(':8080|'));
    assert.deepEqual(httpSite, [], 'the http->https redirect site holds no gate property');
  });

  it('sees the hand-added ungated site and its upstream', () => {
    const sites = summarize('hand-edited').sites;
    const stray = sites.get(`:${FIXTURE_STRAY_PORT}|${FIXTURE_TAILNET_HOST}`);
    assert.ok(stray, 'the hand-added block is a site');
    assert.deepEqual(stray.gates, [], 'it carries no gate');
    assert.deepEqual(stray.proxies, [`127.0.0.1:${FIXTURE_STRAY_PORT}`]);
  });

  it('reads protocols off the listener, and reports its absence as null', () => {
    assert.deepEqual(summarize('generated').listeners.get(`:${FIXTURE_HTTPS_PORT}`).protocols, ['h1']);
    assert.equal(summarize('no-h1').listeners.get(`:${FIXTURE_HTTPS_PORT}`).protocols, null);
  });

  it('gives two matchers the same signature regardless of key order', () => {
    const a = drift.matcherSignature([{ host: ['x'], path: ['/a'] }]);
    const b = drift.matcherSignature([{ path: ['/a'], host: ['x'] }]);
    assert.equal(a, b);
    assert.equal(drift.matcherSignature(undefined), '*', 'no matcher means everything');
    assert.equal(drift.matcherSignature([]), '*');
  });
});

describe('caddy-drift — P1, every proxying site has a gate', () => {
  const baseline = summarize('generated').sites;

  it('holds when the live file is the generated one', () => {
    const result = drift.checkGates(baseline, baseline);
    assert.equal(result.status, drift.HOLDS);
    assert.deepEqual(result.findings, []);
  });

  it('does NOT fire on the generator\'s own ungated bypass routes', () => {
    // The bypass paths (/api/health, /openclaw-direct/*, /manifest.json) reach
    // the upstream with no gate BY DESIGN. An absolute "no ungated proxy
    // anywhere" reading of this property fires on every correct install.
    const result = drift.checkGates(summarize('generated').sites, baseline);
    assert.equal(result.status, drift.HOLDS);
  });

  it('reports the hand-added site, naming the missing property and nothing else', () => {
    const result = drift.checkGates(summarize('hand-edited').sites, baseline);
    assert.equal(result.status, drift.DIVERGED);
    assert.equal(result.findings.length, 1, 'only the hand-added site diverges');
    assert.match(result.findings[0], new RegExp(`:${FIXTURE_STRAY_PORT}`));
    assert.match(result.findings[0], /with no gate/);
    // Neutral: names the missing property, does not attribute a mistake.
    assert.ok(!/mistake|wrong|should|error/i.test(result.findings[0]));
  });

  it('is NOT-MEASURED, never clean, when the config generates no gate at all', () => {
    const ungated = summarize('ungated').sites;
    const result = drift.checkGates(ungated, ungated);
    assert.equal(result.status, drift.NOT_MEASURED);
    assert.notEqual(result.status, drift.HOLDS);
    assert.match(result.findings[0], /UNGATED/);
  });

  it('does not blame the live file for a gate the baseline also omits', () => {
    // Live and baseline both ungated on the same site: the live file has not
    // diverged from anything, whatever else is wrong. Guarded by a gated
    // baseline site so the not-measured branch above is not what answers.
    const baselineMixed = new Map(baseline);
    const ungatedSite = { key: ':9999|x', listen: ':9999', hosts: ['x'], proxies: ['127.0.0.1:9999'], gates: [] };
    baselineMixed.set(ungatedSite.key, ungatedSite);
    const live = new Map([[ungatedSite.key, { ...ungatedSite }]]);
    const result = drift.checkGates(live, baselineMixed);
    assert.equal(result.status, drift.HOLDS);
  });
});

describe('caddy-drift — P2, the HTTPS listener negotiates h1 only', () => {
  const baseline = summarize('generated').listeners;

  it('holds when the pin is present', () => {
    const result = drift.checkHttpsProtocols(baseline, baseline, FIXTURE_HTTPS_PORT);
    assert.equal(result.status, drift.HOLDS);
  });

  it('reports a stripped pin', () => {
    const result = drift.checkHttpsProtocols(summarize('no-h1').listeners, baseline, FIXTURE_HTTPS_PORT);
    assert.equal(result.status, drift.DIVERGED);
    assert.match(result.findings[0], /h1/);
  });

  it('reports a missing HTTPS listener as divergence, not as absence of evidence', () => {
    const result = drift.checkHttpsProtocols(new Map(), baseline, FIXTURE_HTTPS_PORT);
    assert.equal(result.status, drift.DIVERGED);
    assert.match(result.findings[0], /no listener/);
  });

  it('is NOT-MEASURED when the baseline itself has no HTTPS listener to compare', () => {
    const result = drift.checkHttpsProtocols(baseline, new Map(), FIXTURE_HTTPS_PORT);
    assert.equal(result.status, drift.NOT_MEASURED);
  });
});

describe('caddy-drift — P3, no upstream the generated config does not dial', () => {
  const baseline = drift.upstreamsOf(summarize('generated').sites);

  it('holds against itself', () => {
    const result = drift.checkUpstreams(baseline, baseline);
    assert.equal(result.status, drift.HOLDS);
    assert.deepEqual(result.unknown, []);
  });

  it('names the upstream TangleClaw does not generate', () => {
    const result = drift.checkUpstreams(drift.upstreamsOf(summarize('hand-edited').sites), baseline);
    assert.equal(result.status, drift.DIVERGED);
    assert.deepEqual(result.unknown, [`127.0.0.1:${FIXTURE_STRAY_PORT}`]);
  });
});

describe('caddy-drift — P4, the PortHub lease cross-reference', () => {
  const unknown = [`127.0.0.1:${FIXTURE_STRAY_PORT}`];

  it('is NOT-MEASURED, never clean, when PortHub did not answer', () => {
    const result = drift.checkLeaseReach(unknown, null);
    assert.equal(result.status, drift.NOT_MEASURED);
    assert.match(result.findings[0], /PortHub/);
  });

  it('reports a loopback-only lease that the Caddyfile fronts, naming its owner', () => {
    const result = drift.checkLeaseReach(unknown, [lease(FIXTURE_STRAY_PORT, 'loopback', 'TangleBrain', 'knob-gui')]);
    assert.equal(result.status, drift.DIVERGED);
    assert.match(result.findings[0], /reach:loopback/);
    assert.match(result.findings[0], /TangleBrain/);
    assert.match(result.findings[0], /knob-gui/);
  });

  it('holds when the lease declares a reach the site actually provides', () => {
    for (const reach of ['tailnet', 'lan']) {
      const result = drift.checkLeaseReach(unknown, [lease(FIXTURE_STRAY_PORT, reach)]);
      assert.equal(result.status, drift.HOLDS, `${reach} should satisfy a Caddy-fronted site`);
    }
  });

  it('is NOT-MEASURED when the port has no lease at all', () => {
    const result = drift.checkLeaseReach(unknown, [lease(9999, 'loopback')]);
    assert.equal(result.status, drift.NOT_MEASURED);
    assert.match(result.findings[0], /no PortHub lease/);
  });

  it('is NOT-MEASURED when the lease carries a reach it cannot read', () => {
    const result = drift.checkLeaseReach(unknown, [lease(FIXTURE_STRAY_PORT, undefined)]);
    assert.equal(result.status, drift.NOT_MEASURED);
  });

  it('is NOT-MEASURED for an upstream that is not a local port', () => {
    const result = drift.checkLeaseReach(['10.0.0.4:8080', 'unix//tmp/x.sock'], [lease(8080, 'loopback')]);
    assert.equal(result.status, drift.NOT_MEASURED);
  });

  it('holds only when nothing unknown is fronted', () => {
    assert.equal(drift.checkLeaseReach([], []).status, drift.HOLDS);
  });

  it('matches the lease by HOST as well as port', () => {
    // port_leases is keyed on (host, port) and list() orders by host, so a row
    // for another machine sorts ahead of the localhost row and a port-only
    // match lets it answer for a dial it has nothing to do with.
    const foreign = lease(FIXTURE_STRAY_PORT, 'lan', 'OtherBox', 'gui', 'elkaholic');
    const local = lease(FIXTURE_STRAY_PORT, 'loopback', 'TangleBrain', 'knob-gui', 'localhost');
    const found = drift.checkLeaseReach(unknown, [foreign, local]);
    assert.equal(found.status, drift.DIVERGED, 'the foreign row must not shadow the local one');
    assert.match(found.findings[0], /TangleBrain/);

    // And a foreign row ALONE answers for nothing.
    const alone = drift.checkLeaseReach(unknown, [foreign]);
    assert.equal(alone.status, drift.NOT_MEASURED);
    assert.match(alone.findings[0], /no PortHub lease/);
  });

  it('treats a lease with no host as local, since localhost is the column default', () => {
    const bare = { port: FIXTURE_STRAY_PORT, reach: 'loopback', project: 'P', service: 's' };
    assert.equal(drift.checkLeaseReach(unknown, [bare]).status, drift.DIVERGED);
  });

  it('reads the reach vocabulary from the store, not from a second copy', () => {
    // Two copies of the list meant a widened vocabulary left P4 quietly
    // refusing to recognise the new value while the store accepted it.
    assert.deepEqual(drift.REACH_ORDER, store.LEASE_REACHES);
    assert.equal(drift.REACH_ORDER, store.LEASE_REACHES, 'the same array, not an equal one');
  });

  it('treats every loopback spelling as this machine', () => {
    for (const host of ['127.0.0.1', 'localhost', '::1', '[::1]']) {
      assert.ok(drift.isLoopbackHost(host), host);
    }
    assert.ok(!drift.isLoopbackHost('10.0.0.4'));
  });
});

describe('caddy-drift — buildBaseline, which needs no caddy binary', () => {
  // Every other path to buildBaseline is behind an adapt call, so on CI it had
  // no coverage at all. It only builds TEXT; the binary is needed to adapt it.
  it('generates a gated baseline from CONFIG, not from the live file', () => {
    // The point of sourcing from config: a hand-edit that DELETED the gate must
    // not produce a baseline that also has none, or the check blesses it.
    const ungatedLive = 'localhost {\n\treverse_proxy 127.0.0.1:3102\n}\n';
    const built = drift.buildBaseline(fixtureConfig(), ungatedLive);
    assert.equal(built.ok, true, built.reason);
    assert.match(built.content, /basic_auth/, 'the baseline is gated even though the live file is not');
    assert.match(built.content, new RegExp(`reverse_proxy 127\\.0\\.0\\.1:${FIXTURE_SERVER_PORT}`));
    assert.match(built.content, new RegExp(`servers :${FIXTURE_HTTPS_PORT}`));
  });

  it('emits no gate when the config declares none', () => {
    const built = drift.buildBaseline(fixtureConfig({ authEnabled: false, caddyTailnetHost: null }), null);
    assert.equal(built.ok, true, built.reason);
    assert.ok(!built.content.includes('basic_auth'));
  });

  it('takes cert paths from the live file when it can read them', () => {
    // Cosmetic to every measured property, but it is what keeps the baseline
    // from claiming certificates this install does not have.
    const live = FIXTURE_CADDYFILES.generated;
    const built = drift.buildBaseline(fixtureConfig(), live);
    assert.equal(built.ok, true, built.reason);
    assert.match(built.content, /tls \/fixtures\/cert\.pem \/fixtures\/key\.pem/);
  });

  it('falls back to the staged certs dir when the live file is unreadable', () => {
    const built = drift.buildBaseline(fixtureConfig(), null);
    assert.equal(built.ok, true, built.reason);
    assert.match(built.content, /cert\.pem/);
  });

  it('reports a generator refusal rather than throwing', () => {
    // The generator throws on a half-set credential pair, by design — a
    // misconfigured gate must never silently produce an UNGATED baseline.
    const built = drift.buildBaseline(fixtureConfig({ basicAuthHash: null }), null);
    assert.equal(built.ok, false);
    assert.ok(typeof built.reason === 'string' && built.reason.length > 0);
  });
});

describe('caddy-drift — honest degradation', () => {
  it('reports every property NOT-MEASURED when caddy is absent', async () => {
    await withoutCaddy(() => {
      const result = drift.checkCaddyDrift({
        config: fixtureConfig(),
        caddyfilePath: path.join(FIXTURE_DIR, 'caddy-adapt-generated.json')
      });
      assert.equal(result.measured, false);
      for (const [name, property] of Object.entries(result.properties)) {
        assert.equal(property.status, drift.NOT_MEASURED, `${name} must not read as clean`);
      }
      // The flat findings list carries DIVERGENCES only. An unrun check
      // contributes nothing to it, so a caller that reports "no findings" as
      // healthy must read `measured` — which is why it exists.
      assert.deepEqual(result.findings, []);
      assert.match(result.reason, /caddy/i);
    });
  });

  it('reports NOT-MEASURED when the Caddyfile is missing', () => {
    const result = drift.checkCaddyDrift({
      config: fixtureConfig(),
      caddyfilePath: path.join(os.tmpdir(), 'tc-no-such-caddyfile-1394')
    });
    assert.equal(result.measured, false);
    assert.match(result.reason, /could not be read/);
    for (const property of Object.values(result.properties)) {
      assert.equal(property.status, drift.NOT_MEASURED);
    }
  });

  it('adaptCaddyfile refuses a path that does not exist', () => {
    const result = drift.adaptCaddyfile(path.join(os.tmpdir(), 'tc-absent-1394'));
    assert.equal(result.ok, false);
    assert.match(result.reason, /not found/);
  });
});

describe('caddy-drift — credentials never reach a report', () => {
  it('redacts the bcrypt hash out of an adapt failure', { skip: !CADDY_AVAILABLE && 'caddy is not installed' }, () => {
    // `caddy adapt` quotes the offending line on a parse error, and in this
    // project's config that line can be `basic_auth <user> <hash>`. The hash is
    // present in the input by construction, so a redaction that stopped working
    // fails here rather than leaking into a log.
    const broken = `{\n\tinvalid_global_directive\n}\n\nlocalhost {\n\tbasic_auth {\n\t\tfixture ${FIXTURE_HASH}\n\t}\n`;
    assert.ok(broken.includes(FIXTURE_HASH), 'fixture precondition: the input carries a hash');
    const result = drift.adaptCaddyfileContent(broken);
    assert.equal(result.ok, false);
    assert.ok(!result.reason.includes(FIXTURE_HASH), 'the hash must not survive into the reason');
  });

  it('redacts findings on the way out', () => {
    // Pinning the contract at the boundary rather than trusting that no message
    // template will ever interpolate adapt output.
    const result = drift.checkLeaseReach(
      ['127.0.0.1:3250'],
      [lease(3250, 'loopback', `proj${FIXTURE_HASH}`, 'svc')]
    );
    assert.ok(result.findings[0].includes(FIXTURE_HASH), 'precondition: the raw finding carries it');
    const redacted = caddy.redactHashes(result.findings[0]);
    assert.ok(!redacted.includes(FIXTURE_HASH));
  });
});

describe('caddy-drift — against real caddy', { skip: !CADDY_AVAILABLE && 'caddy is not installed' }, () => {
  it('the committed fixtures still match what this Caddy produces', () => {
    for (const [name, content] of Object.entries(FIXTURE_CADDYFILES)) {
      const fresh = drift.adaptCaddyfileContent(content);
      assert.equal(fresh.ok, true, `${name}: ${fresh.reason}`);
      assert.deepEqual(
        fresh.config,
        adapted(name),
        `test/fixtures/caddy-adapt-${name}.json is stale — `
        + 'run node scripts/regen-caddy-adapt-fixtures.js and review the diff'
      );
    }
  });

  it('finds exactly the hand-added block, end to end', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-drift-e2e-'));
    try {
      const file = path.join(dir, 'Caddyfile');
      fs.writeFileSync(file, FIXTURE_CADDYFILES['hand-edited'], { mode: 0o600 });
      const result = drift.checkCaddyDrift({
        config: fixtureConfig(),
        caddyfilePath: file,
        leases: [lease(FIXTURE_STRAY_PORT, 'loopback', 'TangleBrain', 'knob-gui')]
      });
      assert.equal(result.measured, true);
      assert.equal(result.properties.gatedProxies.status, drift.DIVERGED);
      assert.equal(result.properties.httpsProtocols.status, drift.HOLDS);
      assert.equal(result.properties.knownUpstreams.status, drift.DIVERGED);
      assert.equal(result.properties.leaseReach.status, drift.DIVERGED);
      assert.equal(result.findings.length, 3, result.findings.join(' | '));
      for (const finding of result.findings) {
        assert.match(finding, new RegExp(String(FIXTURE_STRAY_PORT)));
        assert.ok(!finding.includes(FIXTURE_HASH));
      }
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('finds nothing in the file TangleClaw itself generates', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-drift-clean-'));
    try {
      const file = path.join(dir, 'Caddyfile');
      fs.writeFileSync(file, FIXTURE_CADDYFILES.generated, { mode: 0o600 });
      const result = drift.checkCaddyDrift({
        config: fixtureConfig(),
        caddyfilePath: file,
        leases: []
      });
      assert.equal(result.measured, true);
      assert.deepEqual(result.findings, [], 'the generator must not fail its own check');
      for (const [name, property] of Object.entries(result.properties)) {
        assert.equal(property.status, drift.HOLDS, `${name}: ${property.findings.join(' | ')}`);
      }
    } finally {
      fs.rmSync(dir, { recursive: true, force: true });
    }
  });

  it('leaves no baseline temp file behind', () => {
    const before = fs.readdirSync(os.tmpdir()).filter((n) => n.startsWith('tc-caddy-baseline-'));
    drift.adaptCaddyfileContent(FIXTURE_CADDYFILES.generated);
    const after = fs.readdirSync(os.tmpdir()).filter((n) => n.startsWith('tc-caddy-baseline-'));
    assert.deepEqual(after, before, 'the baseline carries the credential; it must not linger in /tmp');
  });
});
