'use strict';

// Classification of an existing Caddyfile into the states the setup wizard must
// act on. The wizard cannot offer the CLI's `--force`, so it never overwrites a
// file a human maintains: it adopts a hand-rolled gate, and refuses anything it
// cannot adopt unambiguously.
//
// The distinction that earns this its own suite: a hand-edited file with NO
// credential and one with SEVERAL are different answers. `extractBasicAuthCredential`
// returns null for both, so classifying on that alone would tell an operator with
// two logins that they have none — and route them to overwrite a working gate.

const { describe, it } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const caddy = require('../lib/caddy');

// Exactly 53 chars of [./A-Za-z0-9] after the `$2a$14$` prefix — the real bcrypt
// shape that CREDENTIAL_LINE_RE matches. A fixture of any other length silently
// matches nothing, and every state collapses to `ungated`.
const BCRYPT_A = '$2a$14$abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0';
const BCRYPT_B = '$2a$14$zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA9';

/** Build a hand-edited Caddyfile (no integrity stamp) with the given credential lines. */
function handEdited(credentialLines) {
  return [
    '# Generated by TangleClaw (AUTH-1 / lib/caddy.js) — do not hand-edit.',
    '# NOTE (manual): basic_auth added by hand to unblock remote login.',
    '{',
    '\thttps_port 8443',
    '}',
    '',
    'localhost {',
    '\tbasic_auth {',
    ...credentialLines.map((l) => `\t\t${l}`),
    '\t}',
    '\treverse_proxy 127.0.0.1:3102',
    '}',
    ''
  ].join('\n');
}

/** Write content to a temp file and return its path. */
function tmpCaddyfile(content) {
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-ingress-state-'));
  const p = path.join(dir, 'Caddyfile');
  fs.writeFileSync(p, content);
  return p;
}

describe('classifyIngressState', () => {
  it('reports "absent" when no Caddyfile exists', () => {
    const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-ingress-state-'));
    const state = caddy.classifyIngressState(path.join(dir, 'Caddyfile'));
    assert.equal(state.state, 'absent');
    assert.equal(state.safeToWrite, true, 'nothing to preserve, so the wizard may provision');
    assert.equal(state.user, null);
  });

  it('reports "generated" for an integrity-verified generated file, which may be rewritten', () => {
    const content = caddy.buildCaddyfileContent({
      serverPort: 3102,
      certPath: '/tmp/cert.pem',
      keyPath: '/tmp/key.pem',
      basicAuthUser: 'jason',
      basicAuthHash: BCRYPT_A
    });
    // Guard the premise: if this stops being a generated file the test proves nothing.
    assert.equal(caddy.isGeneratedCaddyfile(content), true);

    const state = caddy.classifyIngressState(tmpCaddyfile(content));
    assert.equal(state.state, 'generated');
    assert.equal(state.safeToWrite, true);
  });

  it('reports "adoptable" for a hand-edited file carrying exactly one credential', () => {
    const state = caddy.classifyIngressState(tmpCaddyfile(handEdited([`jason ${BCRYPT_A}`])));
    assert.equal(state.state, 'adoptable');
    assert.equal(state.safeToWrite, false, 'a human maintains this file');
    assert.equal(state.user, 'jason');
  });

  it('reports "ambiguous" for a hand-edited file with more than one distinct user', () => {
    const state = caddy.classifyIngressState(
      tmpCaddyfile(handEdited([`jason ${BCRYPT_A}`, `alex ${BCRYPT_B}`]))
    );
    assert.equal(state.state, 'ambiguous');
    assert.equal(state.safeToWrite, false);
    assert.equal(state.user, null, 'adoption must never guess which credential is canonical');
    assert.deepEqual(state.users, ['jason', 'alex']);
  });

  it('reports "ungated" for a hand-edited file with no credential at all', () => {
    const content = [
      '# my own reverse proxy',
      'localhost {',
      '\treverse_proxy 127.0.0.1:3102',
      '}',
      ''
    ].join('\n');
    const state = caddy.classifyIngressState(tmpCaddyfile(content));
    assert.equal(state.state, 'ungated');
    assert.equal(state.safeToWrite, false);
    assert.equal(state.user, null);
  });

  it('separates "ungated" from "ambiguous" — the whole reason this classifier exists', () => {
    const none = caddy.classifyIngressState(tmpCaddyfile(handEdited([])));
    const many = caddy.classifyIngressState(
      tmpCaddyfile(handEdited([`jason ${BCRYPT_A}`, `alex ${BCRYPT_B}`]))
    );
    // extractBasicAuthCredential collapses both to null; the classifier must not.
    assert.equal(caddy.extractBasicAuthCredential(fs.readFileSync(tmpCaddyfile(handEdited([])), 'utf8')), null);
    assert.notEqual(none.state, many.state);
  });

  it('never reports safeToWrite for any hand-edited state', () => {
    const handEditedCases = [
      handEdited([`jason ${BCRYPT_A}`]),
      handEdited([`jason ${BCRYPT_A}`, `alex ${BCRYPT_B}`]),
      handEdited([])
    ];
    for (const content of handEditedCases) {
      const state = caddy.classifyIngressState(tmpCaddyfile(content));
      assert.equal(state.safeToWrite, false, `hand-edited file classified ${state.state} must be protected`);
    }
  });

  it('treats an unreadable path as absent rather than throwing', () => {
    const state = caddy.classifyIngressState('/nonexistent/dir/Caddyfile');
    assert.equal(state.state, 'absent');
  });

  it('classifies THIS machine\'s live Caddyfile as protected, when one is present', (t) => {
    const live = caddy.getCaddyfilePath();
    if (!fs.existsSync(live)) {
      t.skip('no live Caddyfile on this machine');
      return;
    }
    const state = caddy.classifyIngressState(live);
    // Whatever shape it is, the wizard must never be told it may rewrite it
    // unless it is a verifiably generated file.
    if (state.state !== 'generated') {
      assert.equal(state.safeToWrite, false);
    }
  });
});
