'use strict';

/*
 * #858 — an engine switch leaves the previous engine's config file behind as
 * stale canon. `generateConfig` writes only the active engine's file, so the
 * old one stayed on disk unmarked, read by convention (`CLAUDE.md`), and
 * steadily wrong. These drive the real switch path (`projects.updateProject`)
 * and read the files back: the retired file says it is inactive and names the
 * live engine; a hand-written or plugin-owned file is left alone with the
 * reason; switching back regenerates without a false drift warning.
 */

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { setLevel, setConsoleStream } = require('../lib/logger');
setLevel('error');
const store = require('../lib/store');
const projects = require('../lib/projects');
const engines = require('../lib/engines');

describe('#858 an engine switch retires the previous engine\'s config file', () => {
  let tmpDir;
  let projectsDir;

  before(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-switch-retire-'));
    projectsDir = path.join(tmpDir, 'projects');
    fs.mkdirSync(projectsDir, { recursive: true });
    store._setBasePath(path.join(tmpDir, 'tangleclaw'));
    store.init();
    const config = store.config.load();
    config.projectsDir = projectsDir;
    store.config.save(config);
  });

  after(() => {
    store.close();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  /**
   * Create a project on an engine with its config written, the way a project
   * looks before a switch.
   * @param {string} name - Project name.
   * @param {string} engine - Engine id.
   * @returns {string} The project directory.
   */
  function seed(name, engine) {
    const dir = path.join(projectsDir, name);
    const created = projects.createProject({ name, engine });
    assert.deepEqual(created.errors || [], [], `seed ${name}`);
    const projConfig = store.projectConfig.load(dir);
    projConfig.engine = engine;
    store.projectConfig.save(dir, projConfig);
    engines.writeEngineConfig(engine, dir, projConfig, store.engines.get(engine));
    return dir;
  }

  it('claude → antigravity: the generated CLAUDE.md becomes an inactive notice naming the live engine and file', async () => {
    const dir = seed('retire-claude', 'claude');
    assert.match(fs.readFileSync(path.join(dir, 'CLAUDE.md'), 'utf8'), /^# CLAUDE\.md — Generated by TangleClaw/);

    const result = await projects.updateProject('retire-claude', { engine: 'antigravity' });
    assert.deepEqual(result.errors || [], []);

    const claudeMd = fs.readFileSync(path.join(dir, 'CLAUDE.md'), 'utf8');
    assert.match(claudeMd, /TangleClaw: INACTIVE engine config/);
    assert.match(claudeMd, /switched from claude to antigravity/);
    assert.match(claudeMd, /The live config is AGENTS\.md/);
    assert.doesNotMatch(claudeMd, /Generated by TangleClaw/, 'nothing left that reads as a live generated config');
    assert.match(fs.readFileSync(path.join(dir, 'AGENTS.md'), 'utf8'), /BEGIN:tangleclaw/, 'the live engine\'s file was written');
  });

  it('antigravity → claude: only the managed block becomes the notice; the operator\'s content outside it stays', async () => {
    const dir = seed('retire-agy', 'antigravity');
    const agents = path.join(dir, 'AGENTS.md');
    fs.writeFileSync(agents, `# My own notes\n\nKeep me.\n\n${fs.readFileSync(agents, 'utf8')}`);

    const result = await projects.updateProject('retire-agy', { engine: 'claude' });
    assert.deepEqual(result.errors || [], []);

    const after = fs.readFileSync(agents, 'utf8');
    assert.match(after, /^# My own notes\n\nKeep me\./, 'content outside the markers is the operator\'s');
    assert.match(after, /BEGIN:tangleclaw[\s\S]*INACTIVE engine config[\s\S]*switched from antigravity to claude[\s\S]*END:tangleclaw/);
    assert.match(fs.readFileSync(path.join(dir, 'CLAUDE.md'), 'utf8'), /^# CLAUDE\.md — Generated by TangleClaw/);
  });

  it('switching back regenerates over the notice without calling it operator drift', async () => {
    const dir = seed('retire-roundtrip', 'claude');
    await projects.updateProject('retire-roundtrip', { engine: 'antigravity' });
    assert.match(fs.readFileSync(path.join(dir, 'CLAUDE.md'), 'utf8'), /INACTIVE engine config/);

    const lines = [];
    setConsoleStream({ write: (s) => lines.push(String(s)) });
    setLevel('warn');
    try {
      await projects.updateProject('retire-roundtrip', { engine: 'claude' });
    } finally {
      setConsoleStream(null);
      setLevel('error');
    }
    const claudeMd = fs.readFileSync(path.join(dir, 'CLAUDE.md'), 'utf8');
    assert.match(claudeMd, /^# CLAUDE\.md — Generated by TangleClaw/, 'live again');
    assert.doesNotMatch(claudeMd, /INACTIVE engine config/);
    assert.deepEqual(lines.filter((l) => /drift detected/.test(l)), [],
      'the notice is TangleClaw\'s own content — overwriting it is not overwriting hand-edits');
    // And the file the project just left is now the retired one.
    assert.match(fs.readFileSync(path.join(dir, 'AGENTS.md'), 'utf8'), /INACTIVE engine config[\s\S]*switched from antigravity to claude/);
  });

  it('a plugin-governed CLAUDE.md is never touched — the file is the plugin\'s', async () => {
    const dir = seed('retire-governed', 'claude');
    fs.mkdirSync(path.join(dir, '.claude'), { recursive: true });
    fs.writeFileSync(path.join(dir, '.claude', 'settings.json'), JSON.stringify({ enabledPlugins: { 'prawduct@prawduct': true } }));
    const before = '# Plugin-owned anchor\n\nHands off.\n';
    fs.writeFileSync(path.join(dir, 'CLAUDE.md'), before);

    const r = engines.retireInactiveEngineConfig(dir, 'claude', 'codex');
    assert.equal(r.retired, false);
    assert.match(r.reason, /plugin-governed/);
    assert.equal(fs.readFileSync(path.join(dir, 'CLAUDE.md'), 'utf8'), before);
  });

  it('a hand-written file with no generated header and no markers is left alone, and says why', () => {
    const dir = path.join(projectsDir, 'retire-handwritten');
    fs.mkdirSync(dir, { recursive: true });
    const before = '# Hand-written CLAUDE.md\n\nMine.\n';
    fs.writeFileSync(path.join(dir, 'CLAUDE.md'), before);

    const r = engines.retireInactiveEngineConfig(dir, 'claude', 'codex');
    assert.equal(r.retired, false);
    assert.match(r.reason, /not TangleClaw-written/);
    assert.equal(fs.readFileSync(path.join(dir, 'CLAUDE.md'), 'utf8'), before);
  });

  it('an engine with no config file, a missing file, and an already-retired file each report their reason', () => {
    const dir = path.join(projectsDir, 'retire-reasons');
    fs.mkdirSync(dir, { recursive: true });
    assert.match(engines.retireInactiveEngineConfig(dir, 'openclaw', 'claude').reason, /has no config file/);
    assert.match(engines.retireInactiveEngineConfig(dir, 'claude', 'codex').reason, /no config file on disk/);
    fs.writeFileSync(path.join(dir, 'CLAUDE.md'), '# CLAUDE.md — Generated by TangleClaw\n\nlive\n');
    assert.equal(engines.retireInactiveEngineConfig(dir, 'claude', 'codex').retired, true);
    assert.match(engines.retireInactiveEngineConfig(dir, 'claude', 'codex').reason, /already marked inactive/);
  });
});
