'use strict';

// Covers: `lib/managed-block.js` — the splice that both the engine-config layer
// and the wrap pipeline's priming roll now share (#1132). The policy questions
// live here; each caller's own test file pins what IT passes in, because a call
// site's arguments are code that a test of the callee does not cover.

const { test, describe } = require('node:test');
const assert = require('node:assert/strict');

const {
  spliceManagedBlock, extractManagedBlock, hasManagedMarkers, _markerFault
} = require('../lib/managed-block');

const MARKERS = { begin: '<!-- BEGIN:tc -->', end: '<!-- END:tc -->' };
const { begin: B, end: E } = MARKERS;

/**
 * Splice and assert the call was allowed, so a refusal can never masquerade as
 * a passing assertion about content.
 * @param {string} existing - Current file contents
 * @param {string} body - Generated body for the managed block
 * @param {object} [markers] - Marker pair to use
 * @returns {string} The merged file content
 */
function splice(existing, body, markers = MARKERS) {
  const { merged, error } = spliceManagedBlock(existing, body, markers);
  assert.equal(error, null, `splice refused: ${error}`);
  return merged;
}

describe('a well-formed file is spliced, and nothing outside the region moves', () => {
  test('an existing block is replaced in place', () => {
    const prior = `head\n${B}\nold\n${E}\ntail`;
    assert.equal(splice(prior, 'new'), `head\n${B}\nnew\n${E}\ntail`);
  });

  test('an absent block is appended after one blank line', () => {
    assert.equal(splice('prose', 'body'), `prose\n\n${B}\nbody\n${E}\n`);
  });

  test('an empty file gets the block with no leading whitespace', () => {
    assert.equal(splice('', 'body'), `${B}\nbody\n${E}\n`);
  });

  test('a foreign vendor block in the same file is untouched', () => {
    // The reason this mechanism exists: `next dev` re-adds its own block to the
    // same AGENTS.md on every run, and the operator writes there too.
    const prior = `<!-- BEGIN:nextjs-agent-rules -->\nvendor\n<!-- END:nextjs-agent-rules -->\n\n${B}\nours\n${E}\n`;
    const out = splice(prior, 'ours v2');
    assert.match(out, /^<!-- BEGIN:nextjs-agent-rules -->\nvendor\n<!-- END:nextjs-agent-rules -->\n/);
    assert.ok(!/\bours\n/.test(out), 'only our body is replaced');
  });
});

describe('only the counts license an edit — a marker literal is not proof the marker is ours', () => {
  test('a misordered pair is repaired, keeping the text that was between the markers', () => {
    // The shape #1132 names. Both markers are unambiguously ours (one of each),
    // so the pair may be rewritten; the text between a CLOSING marker and an
    // OPENING one was never generated by us, so it is kept.
    const out = splice(`${E}\nkeep me\n${B}\n`, 'body');
    assert.equal(out, `${B}\nbody\n${E}\nkeep me\n\n`);
  });

  test('the repaired block lands where the first marker sat, not at the end', () => {
    // Mutation this catches: repairing by stripping markers and appending,
    // which relocates our region out of the sections that give it its point.
    const out = splice(`top\n${E}\nmid\n${B}\nbottom`, 'body');
    assert.ok(out.indexOf(B) < out.indexOf('mid'));
    assert.match(out, /^top\n/);
  });

  test('a repaired file is byte-identical on the next pass, and every pass after', () => {
    // #1132's acceptance criterion as a property: the old append added a block
    // per pass, forever. Mutation this catches: a repair that leaves the file
    // still malformed, which restores the growth one pass later.
    let file = `${E}\nkeep me\n${B}\n`;
    const sizes = [];
    for (let pass = 0; pass < 5; pass += 1) {
      file = splice(file, `body ${pass}`);
      sizes.push(file.length);
    }
    assert.equal(new Set(sizes.slice(1)).size, 1, `file kept growing: ${sizes}`);
    assert.match(file, /keep me/, 'their text survives every pass, not just the first');
  });

  test('the repair reports itself, and an ordinary splice does not', () => {
    // A repair moves bytes OUTSIDE the managed region. It is the one write a
    // caller must announce, so the fact has to leave this module.
    assert.equal(spliceManagedBlock(`${E}\nx\n${B}`, 'body', MARKERS).repaired, true);
    assert.equal(spliceManagedBlock(`${B}\nold\n${E}`, 'body', MARKERS).repaired, false);
    assert.equal(spliceManagedBlock('prose', 'body', MARKERS).repaired, false);
    assert.equal(spliceManagedBlock(`${B}${B}${E}`, 'body', MARKERS).repaired, false);
  });

  test('an operator documenting the markers in their own prose is refused, not adopted', () => {
    // The hazard that makes counting the only honest test. Someone explaining
    // this mechanism inside the very file it edits writes both literals in
    // their prose; nothing in the text distinguishes that from a real region.
    // Adopting the first pair would delete their explanation and drop the real
    // block below it. Mutation this catches: treating any begin-then-end as a
    // complete region and collapsing the rest.
    const doc = `# Notes\nWe splice between ${B} and ${E} — do not edit inside.\n\n${B}\nreal\n${E}\n`;
    const { merged, error, repaired } = spliceManagedBlock(doc, 'body', MARKERS);
    assert.equal(merged, null, 'nothing is written');
    assert.equal(repaired, false);
    assert.match(error, /2 begin, 2 end/);
  });

  test('a stray marker beside a real block is refused, so the block cannot migrate into their prose', () => {
    const doc = `# Notes\nthe ${B} marker opens it\n\n${B}\nreal\n${E}\n`;
    const { merged, error } = spliceManagedBlock(doc, 'body', MARKERS);
    assert.equal(merged, null);
    assert.match(error, /2 begin, 1 end/);
  });

  test('every ambiguous count is refused and leaves the file untouched', () => {
    const ambiguous = [
      `head\n${B}\ntheirs`,
      `head\n${E}\ntheirs`,
      `${B}\na\n${E}\nmiddle\n${B}\nb\n${E}\n`,
      `${B}\n${B}\n${E}\n${E}\n`,
      `${E}${B}${E}`
    ];
    for (const prior of ambiguous) {
      const { merged, error } = spliceManagedBlock(prior, 'body', MARKERS);
      assert.equal(merged, null, `should refuse ${JSON.stringify(prior)}`);
      assert.match(error, /malformed/);
    }
  });

  test('a refused file is refused identically next time — no growth, no drift', () => {
    // Refusal is stable in the same way repair is: nothing is written, so the
    // input to the next pass is the input to this one.
    const prior = `${B}\na\n${E}\nmid\n${B}\nb\n${E}`;
    const first = spliceManagedBlock(prior, 'body', MARKERS);
    const second = spliceManagedBlock(prior, 'body', MARKERS);
    assert.equal(first.merged, null);
    assert.equal(second.error, first.error);
  });
});

describe('hasManagedMarkers answers the ownership question once', () => {
  test('any single marker counts as ours', () => {
    // The predicate exists because a both-markers test read a one-marker file
    // as marker-free, and a caller then took a whole-file path over it.
    assert.equal(hasManagedMarkers(`head\n${B}\nx`, MARKERS), true);
    assert.equal(hasManagedMarkers(`head\n${E}\nx`, MARKERS), true);
    assert.equal(hasManagedMarkers(`${B}x${E}`, MARKERS), true);
  });

  test('a file with neither marker is not ours', () => {
    assert.equal(hasManagedMarkers('nothing here', MARKERS), false);
    assert.equal(hasManagedMarkers('', MARKERS), false);
  });

  test('an unusable marker pair is not ours rather than throwing', () => {
    assert.equal(hasManagedMarkers('x', { begin: '#a', end: '#a' }), false);
  });
});

describe('a marker literal in the body is refused, because repair cannot undo it', () => {
  test('a begin literal is refused and nothing is spliced', () => {
    const { merged, error } = spliceManagedBlock('file', `body ${B} more`, MARKERS);
    assert.equal(merged, null);
    assert.match(error, /marker literal/);
  });

  test('an end literal is refused', () => {
    assert.equal(spliceManagedBlock('file', `body ${E}`, MARKERS).merged, null);
  });

  test('the caller\'s hint names where the literal came from', () => {
    const { error } = spliceManagedBlock('file', B, MARKERS, { bodySourceHint: 'check the shared doc' });
    assert.match(error, /check the shared doc/);
  });

  test('a refusal leaves the file writable by the next clean body', () => {
    assert.equal(spliceManagedBlock('file', B, MARKERS).merged, null);
    const recovered = spliceManagedBlock('file', 'clean', MARKERS);
    assert.equal(recovered.error, null);
    assert.match(recovered.merged, /clean/);
  });
});

describe('a marker pair that cannot delimit a region is a caller fault, reported as one', () => {
  test('identical markers are refused', () => {
    const { merged, error } = spliceManagedBlock('x', 'body', { begin: '#tc', end: '#tc' });
    assert.equal(merged, null);
    assert.match(error, /identical/);
  });

  test('nested markers are refused — the scan could not tell them apart', () => {
    // Mutation this catches: dropping the overlap check. `indexOf` for the
    // shorter marker would match inside the longer one, so every begin would
    // also register as an end and the spans would be nonsense.
    const { merged, error } = spliceManagedBlock('x', 'body', { begin: '<!-- tc:begin -->', end: 'tc:begin' });
    assert.equal(merged, null);
    assert.match(error, /overlap/);
  });

  test('a missing form is refused rather than defaulted', () => {
    assert.match(spliceManagedBlock('x', 'body', { begin: '', end: E }).error, /missing/);
    assert.match(_markerFault(null), /missing/);
  });
});

describe('extractManagedBlock reads only an established block', () => {
  test('it returns the body between the first complete pair', () => {
    assert.equal(extractManagedBlock(`h\n${B}\nbody\n${E}\nt`, MARKERS), '\nbody\n');
  });

  test('an empty block reads as empty, not as absent', () => {
    // A caller comparing bodies to detect drift has to tell those apart.
    assert.equal(extractManagedBlock(`${B}${E}`, MARKERS), '');
  });

  test('a file with no complete pair reads as null', () => {
    assert.equal(extractManagedBlock(`${B}\nno close`, MARKERS), null);
    assert.equal(extractManagedBlock(`${E}\nprose\n${B}`, MARKERS), null);
    assert.equal(extractManagedBlock('nothing here', MARKERS), null);
  });

  test('an unusable marker pair reads as null rather than throwing', () => {
    assert.equal(extractManagedBlock('x', { begin: '#a', end: '#a' }), null);
  });
});
