'use strict';

// Chunk G slice 1 (#331) — the Project Master singleton: identity generation,
// idempotent ensure, tmux-truth status, and the two operator API routes.
// The master is deliberately NOT a sessions row / project — tests pin that
// invariant. tmux and engine detection are injected fakes: tests must never
// create a real `tangleclaw-master` session or launch a real engine.

const { describe, it, before, after, beforeEach } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const http = require('node:http');
const { setLevel } = require('../lib/logger');

setLevel('error');

// The generated base URL derives its port from TANGLECLAW_PORT before config
// (#654), and a dev session launched *by* TangleClaw inherits that variable from
// the server process — which would silently override every config-driven port
// assertion below and make results depend on how the test runner was started.
// Neutralize the ambient value; tests that mean to exercise the override set it
// explicitly and restore it.
delete process.env.TANGLECLAW_PORT;

const store = require('../lib/store');
const master = require('../lib/master');

let tmpDir;

before(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-master-'));
  store._setBasePath(tmpDir);
  store.init();
});

after(() => {
  store.close();
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

/**
 * Fake tmux with programmable liveness; records createSession calls.
 *
 * `hasSession` is DERIVED from `probeSession` here exactly as it is in
 * `lib/tmux.js`, rather than being a second independent switch. A stub that let
 * the two disagree could report a combination the real module cannot produce,
 * and the whole subject of these tests is what the caller does with the
 * distinction between them.
 *
 * @param {object} [opts] - Options.
 * @param {boolean} [opts.alive] - Whether the session is live.
 * @param {boolean} [opts.answered] - Whether tmux replied at all. `false` is
 *   the wedged server (#94/#144/#380) — the state that reports every session
 *   as gone unless a caller asks for the third outcome.
 * @param {Function} [opts.createSession] - Override the creation behaviour
 *   (return false, throw) without hand-rolling a stub that would be free to
 *   omit `probeSession` and drift from the real module's shape.
 * @returns {object} A tmux-shaped stub.
 */
function fakeTmux({ alive = false, answered = true, createSession } = {}) {
  const calls = [];
  const probeSession = () => ({
    live: answered ? alive : false,
    answered,
    cause: answered ? null : 'read-timed-out'
  });
  return {
    calls,
    probeSession,
    hasSession: () => probeSession().live,
    createSession: (name, opts) => {
      calls.push({ name, opts });
      return createSession ? createSession(name, opts) : true;
    }
  };
}

const availableEngines = {
  detectEngine: () => ({ available: true }),
  // _masterRuntime resolves through the injected lib (#707), so the stub must
  // answer resolution too — otherwise these tests silently fall back to the real
  // detector and their result depends on the host's installed CLIs.
  resolveDefaultEngine: (config) => (config && config.defaultEngine) || 'claude'
};

/**
 * An engines stub whose resolution uses the REAL precedence over a controlled
 * installed-set. `availableEngines` above is a pass-through that ignores
 * availability entirely, so it cannot exercise a fallback — it returns the same
 * answer whether or not the resolver is wired in, which is how the master-pin
 * bypass survived its own test.
 * @param {string[]} installed - Engine ids present on the imagined machine
 * @returns {object}
 */
function enginesInstalling(installed) {
  const realEngines = require('../lib/engines');
  const list = ['claude', 'codex', 'aider'].map((id) => ({ id, available: installed.includes(id) }));
  return {
    detectEngine: (profile) => ({ available: installed.includes(profile && profile.id) }),
    resolveDefaultEngine: (config) => realEngines.resolveDefaultEngine(config, list)
  };
}

describe('buildMasterClaudeMd', () => {
  it('carries the generated marker, the role, and the read-only rules', () => {
    const md = master.buildMasterClaudeMd({ serverPort: 3101 });
    assert.match(md, /Generated by TangleClaw — Project Master identity/);
    assert.match(md, /TangleClaw Project Master/);
    assert.match(md, /Read-only\./);
    assert.match(md, /Use only GET endpoints/);
    assert.match(md, /Never edit files outside this directory/);
  });

  it('renders the API base URL from config port and the SERVED protocol (ENG-5R2W)', () => {
    // https only with the full willServeHttps conjunction (flag + both cert paths).
    const md = master.buildMasterClaudeMd({
      serverPort: 3200, httpsEnabled: true,
      httpsCertPath: '/c.pem', httpsKeyPath: '/k.pem'
    });
    assert.match(md, /https:\/\/localhost:3200/);
    const md2 = master.buildMasterClaudeMd({ serverPort: 3102 });
    assert.match(md2, /http:\/\/localhost:3102/);
    // httpsEnabled defaults to true — without cert paths the server serves
    // HTTP (createServer fallback), so the base URL must say http.
    const md3 = master.buildMasterClaudeMd({ serverPort: 3102, httpsEnabled: true });
    assert.match(md3, /http:\/\/localhost:3102/);
  });

  it('renders the port the server actually binds, not config.serverPort (#654)', () => {
    // Same drift as the injected project configs: the plist binds 3102 while
    // config keeps the 3101 default, so the master identity file handed the
    // Project Master session a base URL nothing was serving.
    const had = Object.prototype.hasOwnProperty.call(process.env, 'TANGLECLAW_PORT');
    const prev = process.env.TANGLECLAW_PORT;
    try {
      process.env.TANGLECLAW_PORT = '3102';
      const md = master.buildMasterClaudeMd({ serverPort: 3101 });
      assert.match(md, /http:\/\/localhost:3102/);
      assert.doesNotMatch(md, /localhost:3101/);
    } finally {
      if (had) process.env.TANGLECLAW_PORT = prev;
      else delete process.env.TANGLECLAW_PORT;
    }
  });

  it('renders an http base URL in caddy ingress mode even with full HTTPS config (ENG-5R2W)', () => {
    const md = master.buildMasterClaudeMd({
      serverPort: 3102, ingressMode: 'caddy', httpsEnabled: true,
      httpsCertPath: '/c.pem', httpsKeyPath: '/k.pem'
    });
    assert.match(md, /http:\/\/localhost:3102/);
    assert.doesNotMatch(md, /https:\/\/localhost/);
  });

  it('includes the bearer Authentication block only when the gate is on AND a token exists', () => {
    const on = master.buildMasterClaudeMd({ serviceTokenEnabled: true, serviceToken: 'tcsk_abc' });
    assert.match(on, /Authorization: Bearer tcsk_abc/);
    assert.match(on, /\(bearer token\)/);
    const offNoToken = master.buildMasterClaudeMd({ serviceTokenEnabled: true });
    assert.doesNotMatch(offNoToken, /Authorization: Bearer/);
    const tokenButDisabled = master.buildMasterClaudeMd({ serviceToken: 'tcsk_abc' });
    assert.doesNotMatch(tokenButDisabled, /Authorization: Bearer/);
    assert.doesNotMatch(tokenButDisabled, /\(bearer token\)/);
  });
});

describe('ensureMasterSession', () => {
  let home;

  beforeEach(() => {
    home = path.join(tmpDir, `master-home-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  });

  it('creates the home dir + CLAUDE.md and launches when the session is absent', () => {
    const t = fakeTmux({ alive: false });
    const r = master.ensureMasterSession({ home, tmuxLib: t, enginesLib: availableEngines });
    assert.equal(r.created, true);
    assert.equal(r.tmuxSession, master.MASTER_TMUX_SESSION);
    assert.equal(r.error, undefined);
    const md = fs.readFileSync(path.join(home, 'CLAUDE.md'), 'utf8');
    assert.match(md, /Project Master identity/);
    assert.equal(t.calls.length, 1);
    assert.equal(t.calls[0].name, 'tangleclaw-master');
    assert.equal(t.calls[0].opts.cwd, home, 'session cwd must be the master home');
    assert.ok(t.calls[0].opts.command, 'must send the engine launch command');
  });

  it('is idempotent — an alive session means no second launch, but CLAUDE.md still regenerates', () => {
    const t = fakeTmux({ alive: true });
    fs.mkdirSync(home, { recursive: true });
    fs.writeFileSync(path.join(home, 'CLAUDE.md'), 'stale hand-edit');
    const r = master.ensureMasterSession({ home, tmuxLib: t, enginesLib: availableEngines });
    assert.equal(r.created, false);
    assert.equal(r.error, undefined);
    assert.equal(t.calls.length, 0, 'must not create a second session');
    const md = fs.readFileSync(path.join(home, 'CLAUDE.md'), 'utf8');
    assert.match(md, /Project Master identity/, 'identity must be regenerated on every ensure');
    assert.doesNotMatch(md, /stale hand-edit/);
  });

  it('refuses with an error when the engine binary is unavailable — and does not create tmux', () => {
    const t = fakeTmux({ alive: false });
    const r = master.ensureMasterSession({
      home,
      tmuxLib: t,
      // Resolution is pinned so this test is about DETECTION only — without it the
      // real resolver runs and the assertion depends on the host's installed CLIs.
      enginesLib: { detectEngine: () => ({ available: false }), resolveDefaultEngine: () => 'claude' }
    });
    assert.equal(r.created, false);
    assert.match(r.error, /not available/);
    assert.equal(t.calls.length, 0);
  });

  it('names the real problem when NO engine is installed, not a phantom engine id (#707)', () => {
    // The bare-machine case. Before the resolver, config's shipped 'claude'
    // default meant the master reported `Engine "claude" not available (binary
    // not found)` — pointing the operator at a config value when the machine
    // simply had no engine. The resolver returns null here; reporting
    // `Engine "null" not found` would be no better, so the guard says it plainly.
    // Injected through the same seam the caller uses for detection, so this
    // doesn't depend on which CLIs the host machine has installed.
    const noEngines = { detectEngine: () => ({ available: false }), resolveDefaultEngine: () => null };
    const t = fakeTmux({ alive: false });
    const r = master.ensureMasterSession({ home, tmuxLib: t, enginesLib: noEngines });
    assert.equal(r.created, false);
    assert.match(r.error, /No AI engine is installed/);
    assert.doesNotMatch(r.error, /null/, 'must not leak the null through to the operator');
    assert.equal(t.calls.length, 0, 'must not create a tmux session with no engine to run');
  });

  it('refuses with an error when the configured default engine has no profile', () => {
    const config = store.config.load();
    const saved = config.defaultEngine;
    try {
      config.defaultEngine = 'ghost-engine';
      store.config.save(config);
      const t = fakeTmux({ alive: false });
      const r = master.ensureMasterSession({ home, tmuxLib: t, enginesLib: availableEngines });
      assert.equal(r.created, false);
      assert.match(r.error, /"ghost-engine" not found/);
      assert.equal(t.calls.length, 0);
    } finally {
      config.defaultEngine = saved;
      store.config.save(config);
    }
  });

  it('refuses when the engine is available but has no launch command — no bare-shell master', () => {
    const sessionsLib = require('../lib/sessions');
    const original = sessionsLib._buildLaunchCommand;
    try {
      sessionsLib._buildLaunchCommand = () => undefined;
      const t = fakeTmux({ alive: false });
      const r = master.ensureMasterSession({ home, tmuxLib: t, enginesLib: availableEngines });
      assert.equal(r.created, false);
      assert.match(r.error, /no launch command/);
      assert.equal(t.calls.length, 0, 'must not create a session that would run a bare shell');
    } finally {
      sessionsLib._buildLaunchCommand = original;
    }
  });

  it('surfaces tmux failures as typed errors — create-false and thrown', () => {
    const engines = availableEngines;
    const refusing = fakeTmux({ alive: false, createSession: () => false });
    const r1 = master.ensureMasterSession({ home, tmuxLib: refusing, enginesLib: engines });
    assert.equal(r1.created, false);
    assert.match(r1.error, /Failed to create tmux session/);

    const throwing = fakeTmux({ alive: false, createSession: () => { throw new Error('boom'); } });
    const r2 = master.ensureMasterSession({ home: home + '-t', tmuxLib: throwing, enginesLib: engines });
    assert.equal(r2.created, false);
    assert.match(r2.error, /tmux error: boom/);
  });

  it('server boot honors master.autoStart (structural pin — boot code is not unit-launchable)', () => {
    const src = fs.readFileSync(path.join(__dirname, '..', 'server.js'), 'utf8');
    assert.match(src, /master\.masterSettings\(config\)\.autoStart/,
      'server startup must consult the autoStart setting');
    // "Never fatal" needs a real catch: ensureMasterSession types tmux/engine
    // failures into result.error but THROWS on fs faults — an uncaught throw
    // here is self-locking (autoStart is only disablable via the crashed
    // server's own API).
    const block = src.slice(src.indexOf('Project Master auto-start'), src.indexOf('Master auto-start failed'));
    assert.match(block, /try \{/,
      'the auto-start block must catch throws, not just typed errors');
  });

  it('never records a sessions-table row — the master is not a project session', () => {
    // Structural guard (the TB-3 no-HTTP-client pattern): the module must not
    // touch the sessions store at all — its only lib/sessions dependency is
    // the launch-command builder.
    const src = fs.readFileSync(path.join(__dirname, '..', 'lib', 'master.js'), 'utf8');
    assert.doesNotMatch(src, /store\.sessions/,
      'lib/master.js must never read or write the sessions table');
    assert.doesNotMatch(src, /sessions\.launchSession/,
      'the master must not go through the project launch path');
  });
});

describe('getMasterStatus', () => {
  it('reports liveness straight from tmux', () => {
    assert.equal(master.getMasterStatus({ tmuxLib: fakeTmux({ alive: true }) }).exists, true);
    assert.equal(master.getMasterStatus({ tmuxLib: fakeTmux({ alive: false }) }).exists, false);
    assert.equal(master.getMasterStatus({ tmuxLib: fakeTmux() }).tmuxSession, 'tangleclaw-master');
  });

  it('carries the effective settings for the panel/settings UI', () => {
    // enginesLib is injected because `resolvedEngine` now comes from availability
    // resolution (#707); without it this asserts against whichever CLIs the host
    // happens to have installed, and fails on a machine with none — which is the
    // machine class the resolver exists for.
    const s = master.getMasterStatus({ tmuxLib: fakeTmux(), enginesLib: availableEngines }).settings;
    assert.equal(s.accessLevel, 'read-only');
    assert.deepEqual(s.accessLevels, ['read-only', 'suggest', 'write']);
    assert.deepEqual(s.enabledAccessLevels, ['read-only']);
    assert.equal(s.engine, null);
    assert.equal(s.resolvedEngine, 'claude');
    assert.equal(s.scope, 'all');
    assert.equal(s.autoStart, false);
    assert.equal(s.enforcement, 'structural');
  });

  // A wedged tmux answers nothing, and `hasSession` flattened that into
  // `false` — so the one machine state where an operator most needs to know
  // whether the master is up was the one state that reported it as down
  // (#905). Same defect #900 removed from the fleet view and #891 from
  // `git.dirty`; this was the surface they left alone.
  it('reports the master\'s state as UNKNOWN when tmux did not answer', () => {
    // THE MUTATION THIS CATCHES: `exists: probe.live` instead of the answered
    // ternary — which is `hasSession` again, and reports a running master as
    // absent for as long as the wedge lasts.
    const status = master.getMasterStatus({ tmuxLib: fakeTmux({ alive: true, answered: false }) });

    assert.equal(status.exists, null,
      'a liveness nobody could establish must not be reported as an absence');
    assert.deepEqual(status.incomplete, ['exists'],
      'and it has to be NAMED, or a consumer cannot tell null from a missing field');
    assert.equal(status.cause, 'read-timed-out');
  });

  it('names nothing incomplete on the healthy path, and still carries the field', () => {
    // THE MUTATION THIS CATCHES: emitting `incomplete` only on failure. A field
    // that appears only when something is wrong makes every consumer probe for
    // its existence instead of reading its value — the argument
    // `lib/sessions.js` already makes for its own wrapping payload.
    for (const alive of [true, false]) {
      const status = master.getMasterStatus({ tmuxLib: fakeTmux({ alive }) });
      assert.deepEqual(status.incomplete, [], `incomplete must be [] when alive=${alive}`);
      assert.equal(status.cause, null);
      assert.equal(status.exists, alive, 'an ANSWERED negative is still a real false');
    }
  });
});

describe('ensureMasterSession refuses to start a second master over one it cannot see', () => {
  it('declines, and does not create a session, when tmux did not answer', () => {
    // THE MUTATION THIS CATCHES: keeping `t.hasSession(...)` as the guard.
    // False then means BOTH "not running" and "tmux is wedged", and this caller
    // acts on false by starting one — so a wedge aimed a `tmux new-session` at
    // a master that was already running. `lib/sessions.js` refuses on the same
    // grounds for project sessions; this is that rule on the master's path.
    const t = fakeTmux({ alive: true, answered: false });
    const home = path.join(tmpDir, 'master-wedge');

    const r = master.ensureMasterSession({ home, tmuxLib: t, enginesLib: availableEngines });

    assert.equal(r.created, false);
    assert.match(r.error, /could not determine/i,
      'the refusal must say what it could not establish, not report a failed start');
    assert.equal(t.calls.length, 0,
      'and it must not have tried — a created session here is a SECOND master over a live one');
    // THE MUTATION THIS CATCHES: returning only a message. The route maps this
    // field to its own error code, and without it the panel falls back to the
    // generic failure code and paints the master DOWN — a definite claim about
    // the exact thing this refusal says could not be established.
    assert.deepEqual(r.incomplete, ['exists'],
      'the refusal has to be machine-distinguishable from a failed start, not just worded differently');
    assert.equal(r.cause, 'read-timed-out');
  });

  it('routes an unestablished liveness to its own error code, not the generic failure', () => {
    // The mapping is one line in server.js and it is the seam between "the
    // server knows this is an unknown" and "the panel renders it as one".
    // Structural pin: the route is not unit-launchable, and the repo pins boot
    // and route wiring this way elsewhere.
    const src = fs.readFileSync(path.join(__dirname, '..', 'server.js'), 'utf8');
    assert.match(src, /MASTER_LIVENESS_UNKNOWN/,
      'the distinct code must exist, or the client cannot branch on it');
    assert.match(src, /\(result\.incomplete \|\| \[\]\)\.includes\('exists'\)/,
      'and it must be selected from the refusal\'s own field rather than by matching its wording');
  });

  it('still starts one when tmux answered that nothing is running', () => {
    // The other half, keeping the refusal from becoming a blanket "never start":
    // an answered negative is a real negative, and the master must still launch.
    const t = fakeTmux({ alive: false, answered: true });
    const home = path.join(tmpDir, 'master-answered-absent');

    const r = master.ensureMasterSession({ home, tmuxLib: t, enginesLib: availableEngines });

    assert.equal(r.error, undefined, 'an answered absence is not an error');
    assert.equal(t.calls.length, 1, 'it has to actually start the master');
  });
});

/** Remove every master rule row (store-level delete has no confirm gate). */
function clearMasterRules() {
  for (const rule of store.sessionRules.list({ kind: 'master' })) {
    store.sessionRules.delete(rule.id);
  }
}

describe('masterSettings normalization', () => {
  it('applies defaults for a missing/partial master block (shallow-merge safety)', () => {
    assert.deepEqual(master.masterSettings({}), {
      accessLevel: 'read-only', engine: null, launchMode: 'default', scope: 'all', autoStart: false
    });
    const partial = master.masterSettings({ master: { autoStart: true } });
    assert.equal(partial.autoStart, true);
    assert.equal(partial.accessLevel, 'read-only');
    assert.equal(partial.engine, null);
    // #756: a hand-edited partial block must not surface launchMode as
    // undefined — `_buildLaunchCommand` would then receive it and the Master
    // would launch under whatever that coerces to.
    assert.equal(partial.launchMode, 'default');
  });

  it('rejects out-of-enum access levels back to read-only', () => {
    assert.equal(master.masterSettings({ master: { accessLevel: 'god-mode' } }).accessLevel, 'read-only');
  });
});

describe('master Hard rules — seeding, fail-safe, restore', () => {
  beforeEach(clearMasterRules);

  it('seeds the shipped baseline once, idempotently, as system rows', () => {
    assert.equal(master.seedBaselineMasterRules(), master.MASTER_BASELINE_RULES.length);
    assert.equal(master.seedBaselineMasterRules(), 0, 'second call must not duplicate');
    const rules = store.sessionRules.list({ kind: 'master' });
    assert.equal(rules.length, master.MASTER_BASELINE_RULES.length);
    for (const rule of rules) {
      assert.equal(rule.createdBy, 'system');
      assert.equal(rule.projectId, null);
    }
  });

  it('does not re-seed after the operator deleted individual rules (their choice sticks)', () => {
    master.seedBaselineMasterRules();
    const rules = store.sessionRules.list({ kind: 'master' });
    store.sessionRules.delete(rules[0].id);
    assert.equal(master.seedBaselineMasterRules(), 0);
    assert.equal(store.sessionRules.list({ kind: 'master' }).length, rules.length - 1);
  });

  it('restoreDefaultMasterRules replaces custom rules with the baseline, preserving history', () => {
    master.seedBaselineMasterRules();
    const custom = store.sessionRules.create({ content: 'my custom boundary', kind: 'master' });
    const restored = master.restoreDefaultMasterRules();
    assert.equal(restored.length, master.MASTER_BASELINE_RULES.length);
    assert.ok(restored.every((r) => r.createdBy === 'system'));
    assert.ok(!restored.some((r) => r.content === 'my custom boundary'));
    // History outlives the deleted rule (audit) — the delete op is recorded.
    const history = store.sessionRules.listVersions(custom.id);
    assert.ok(history.length >= 2);
    assert.equal(history[0].op, 'delete');
  });

  it('buildMasterClaudeMd renders live rules, and falls back to the baseline at zero enabled rules', () => {
    const withRules = master.buildMasterClaudeMd({ serverPort: 3101 }, {
      rules: [{ content: 'Custom rule one.' }, { content: 'Custom rule two.' }]
    });
    assert.match(withRules, /- Custom rule one\./);
    assert.match(withRules, /- Custom rule two\./);
    assert.doesNotMatch(withRules, /Use only GET endpoints/, 'custom rules REPLACE the baseline');

    // Zero enabled rules → the boundary cannot be emptied: baseline renders.
    const failSafe = master.buildMasterClaudeMd({ serverPort: 3101 }, { rules: [] });
    assert.match(failSafe, /Use only GET endpoints/);
    assert.match(failSafe, /Never edit files outside this directory/);
  });
});

describe('buildMasterClaudeMd — scope and memory sections', () => {
  it('renders the all-projects scope by default, with the fallback warning when present', () => {
    const md = master.buildMasterClaudeMd({ serverPort: 3101 });
    assert.match(md, /## Scope/);
    assert.match(md, /All projects on this TangleClaw instance are in scope\./);
    const warned = master.buildMasterClaudeMd({ serverPort: 3101 }, {
      scope: { kind: 'all', warning: 'The configured scope group no longer exists; scope fell back to all projects.' }
    });
    assert.match(warned, /scope fell back to all projects/);
  });

  it('renders group scope with the member project list and the honest not-a-boundary line', () => {
    const md = master.buildMasterClaudeMd({ serverPort: 3101 }, {
      scope: { kind: 'group', groupName: 'backend', projects: [{ name: 'api-server' }, { name: 'worker' }] }
    });
    assert.match(md, /scoped to the \*\*backend\*\* project group/);
    assert.match(md, /- api-server/);
    assert.match(md, /- worker/);
    assert.match(md, /not a security boundary/);
  });

  it('describes the memory carve-out: TC-refreshed vs master-maintained files', () => {
    const md = master.buildMasterClaudeMd({ serverPort: 3101 });
    assert.match(md, /## Memory/);
    assert.match(md, /memory\/FLEET\.md/);
    assert.match(md, /memory\/CHANGELOG\.md/);
    assert.match(md, /never edit them/);
  });
});

describe('_resolveScope', () => {
  it('falls back to all-projects (with warning) when the configured group is gone', () => {
    const resolved = master._resolveScope({ type: 'group', groupId: 'no-such-group' });
    assert.equal(resolved.kind, 'all');
    assert.match(resolved.warning, /no longer exists/);
  });

  it('resolves a real group to its name and member projects', () => {
    const p = store.projects.create({ name: 'scope-proj', path: '/tmp/scope-proj' });
    const g = store.projectGroups.create({ name: 'scope-group' });
    store.projectGroups.addMember(g.id, p.id);
    const resolved = master._resolveScope({ type: 'group', groupId: g.id });
    assert.equal(resolved.kind, 'group');
    assert.equal(resolved.groupName, 'scope-group');
    assert.deepEqual(resolved.projects.map((x) => x.name), ['scope-proj']);
  });
});

describe('master memory scaffold', () => {
  it('refreshes TC-maintained files and seeds master-maintained files exactly once', () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-master-mem-'));
    try {
      master._refreshMasterMemory(home);
      const memDir = path.join(home, 'memory');
      for (const f of ['FLEET.md', 'HOWTO.md', 'MEMORY.md', 'CHANGELOG.md', 'NOTES.md']) {
        assert.ok(fs.existsSync(path.join(memDir, f)), `${f} must exist`);
      }
      // Master-maintained files survive a second refresh untouched…
      fs.writeFileSync(path.join(memDir, 'NOTES.md'), 'master wrote this');
      fs.writeFileSync(path.join(memDir, 'CHANGELOG.md'), 'activity entry');
      // …while TC-maintained files are overwritten (hand-edits are futile).
      fs.writeFileSync(path.join(memDir, 'FLEET.md'), 'stale hand-edit');
      master._refreshMasterMemory(home);
      assert.equal(fs.readFileSync(path.join(memDir, 'NOTES.md'), 'utf8'), 'master wrote this');
      assert.equal(fs.readFileSync(path.join(memDir, 'CHANGELOG.md'), 'utf8'), 'activity entry');
      assert.match(fs.readFileSync(path.join(memDir, 'FLEET.md'), 'utf8'), /Generated by TangleClaw/);
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });

  it('lists registered projects (including archived, labeled) in the fleet map', () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-master-fleet-'));
    try {
      const p = store.projects.create({ name: 'fleet-proj', path: '/tmp/fleet-proj', engineId: 'claude' });
      store.projects.archive(p.id);
      master._refreshMasterMemory(home);
      const fleet = fs.readFileSync(path.join(home, 'memory', 'FLEET.md'), 'utf8');
      assert.match(fleet, /\*\*fleet-proj\*\*/);
      assert.match(fleet, /ARCHIVED/);
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });
});

describe('read-only guardrails (structural enforcement)', () => {
  const { spawnSync } = require('node:child_process');

  /** Run the generated guard script with a tool-input payload; returns
   *  { denied, reason } parsed from its stdout contract. */
  function runGuard(home, payload) {
    const script = path.join(home, '.claude', 'hooks', 'guard-writes.js');
    const res = spawnSync(process.execPath, [script], {
      input: typeof payload === 'string' ? payload : JSON.stringify(payload),
      encoding: 'utf8'
    });
    assert.equal(res.status, 0, `guard must always exit 0 (got ${res.status}: ${res.stderr})`);
    if (!res.stdout) return { denied: false };
    const out = JSON.parse(res.stdout);
    return {
      denied: out.hookSpecificOutput.permissionDecision === 'deny',
      reason: out.hookSpecificOutput.permissionDecisionReason
    };
  }

  it('writes settings.json (memory allow rules + PreToolUse matcher) and the guard script', () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-master-guard-'));
    try {
      master._writeMasterGuardrails(home);
      const settings = JSON.parse(fs.readFileSync(path.join(home, '.claude', 'settings.json'), 'utf8'));
      assert.deepEqual(settings.permissions.allow, ['Edit(./memory/**)', 'Write(./memory/**)']);
      assert.equal(settings.hooks.PreToolUse[0].matcher, 'Edit|Write|NotebookEdit');
      assert.match(settings.hooks.PreToolUse[0].hooks[0].command, /guard-writes\.js/);
      assert.ok(fs.existsSync(path.join(home, '.claude', 'hooks', 'guard-writes.js')));
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });

  it('the guard allows writes inside memory/ and hard-denies everywhere else — including .claude/ itself', () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-master-guard-'));
    try {
      master._writeMasterGuardrails(home);
      assert.equal(runGuard(home, { tool_input: { file_path: path.join(home, 'memory', 'NOTES.md') } }).denied, false);
      assert.equal(runGuard(home, { tool_input: { file_path: 'memory/nested/deep.md' } }).denied, false, 'relative paths resolve against the home');
      assert.equal(runGuard(home, { tool_input: { file_path: path.join(home, 'CLAUDE.md') } }).denied, true);
      assert.equal(runGuard(home, { tool_input: { file_path: '/etc/hosts' } }).denied, true);
      // The guard protects its own config — the master cannot edit away its guardrails.
      assert.equal(runGuard(home, { tool_input: { file_path: path.join(home, '.claude', 'settings.json') } }).denied, true);
      // Escape attempts via .. resolve outside and deny.
      assert.equal(runGuard(home, { tool_input: { file_path: 'memory/../CLAUDE.md' } }).denied, true);
      // A sibling like memory-evil/ must not prefix-match the carve-out.
      assert.equal(runGuard(home, { tool_input: { file_path: path.join(home, 'memory-evil', 'x.md') } }).denied, true);
      // NotebookEdit carries notebook_path.
      assert.equal(runGuard(home, { tool_input: { notebook_path: path.join(home, 'memory', 'n.ipynb') } }).denied, false);
      assert.equal(runGuard(home, { tool_input: { notebook_path: path.join(home, 'n.ipynb') } }).denied, true);
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });

  it('the guard denies by default on malformed or pathless input (harness fails open on crashes — the guard must not crash)', () => {
    const home = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-master-guard-'));
    try {
      master._writeMasterGuardrails(home);
      assert.equal(runGuard(home, 'not json at all').denied, true);
      assert.equal(runGuard(home, { tool_input: {} }).denied, true);
      assert.equal(runGuard(home, {}).denied, true);
    } finally {
      fs.rmSync(home, { recursive: true, force: true });
    }
  });
});

describe('ensureMasterSession — settings integration', () => {
  let home;

  beforeEach(() => {
    clearMasterRules();
    home = path.join(tmpDir, `master-home-s-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  });

  it('seeds the baseline, renders it into CLAUDE.md, scaffolds memory, and writes guardrails (claude engine)', () => {
    const r = master.ensureMasterSession({ home, tmuxLib: fakeTmux({ alive: false }), enginesLib: availableEngines });
    assert.equal(r.created, true);
    assert.equal(r.engine, 'claude');
    assert.equal(r.accessLevel, 'read-only');
    assert.equal(r.enforcement, 'structural');
    assert.equal(store.sessionRules.list({ kind: 'master' }).length, master.MASTER_BASELINE_RULES.length);
    assert.match(fs.readFileSync(path.join(home, 'CLAUDE.md'), 'utf8'), /Use only GET endpoints/);
    assert.ok(fs.existsSync(path.join(home, 'memory', 'FLEET.md')));
    assert.ok(fs.existsSync(path.join(home, '.claude', 'settings.json')));
  });

  it('renders edited rules into the identity on the next ensure', () => {
    master.seedBaselineMasterRules();
    store.sessionRules.create({ content: 'Session-rules-backed custom boundary.', kind: 'master' });
    master.ensureMasterSession({ home, tmuxLib: fakeTmux({ alive: true }), enginesLib: availableEngines });
    assert.match(fs.readFileSync(path.join(home, 'CLAUDE.md'), 'utf8'), /Session-rules-backed custom boundary\./);
  });

  it('resolves a pinned master.engine that is not installed (#707)', () => {
    // The bypass this closes: `_masterRuntime` honored `settings.engine`
    // unconditionally, so an operator who pinned Claude in Master settings on a
    // machine without Claude got `Engine "claude" not available (binary not
    // found)` — the exact failure the resolver exists to prevent, reached
    // through a second door. Fails against `settings.engine || ...`.
    const config = store.config.load();
    const saved = config.master;
    try {
      config.master = { accessLevel: 'read-only', engine: 'claude', scope: 'all', autoStart: false };
      store.config.save(config);
      const r = master.ensureMasterSession({
        home, tmuxLib: fakeTmux({ alive: false }), enginesLib: enginesInstalling(['codex'])
      });
      assert.equal(r.engine, 'codex', 'a pinned engine that is not installed must resolve, not be honored');
      assert.equal(r.enforcement, 'instructional');
    } finally {
      config.master = saved;
      store.config.save(config);
    }
  });

  it('keeps a pinned master.engine that IS installed', () => {
    const config = store.config.load();
    const saved = config.master;
    try {
      config.master = { accessLevel: 'read-only', engine: 'codex', scope: 'all', autoStart: false };
      store.config.save(config);
      const r = master.ensureMasterSession({
        home, tmuxLib: fakeTmux({ alive: false }), enginesLib: enginesInstalling(['claude', 'codex'])
      });
      assert.equal(r.engine, 'codex', 'an installed pin must be honored, not overridden');
    } finally {
      config.master = saved;
      store.config.save(config);
    }
  });

  /*
   * #756 — the Master had no launch mode at any layer. `lib/master.js` built its
   * session with a hardcoded `null`, on the reasoning that ask-gating everything
   * was part of the read-only posture. That conflated two independent axes: this
   * one governs whether the agent prompts inside ITS OWN session and is enforced
   * by the engine; the access level governs what the Master may do to the fleet
   * and is enforced by TangleClaw. A read-only Master in `bypassPermissions` is
   * coherent — it edits its own `memory/` without nagging and still cannot touch
   * the fleet.
   *
   * These assert the FLAGS that reach the launch command, not the argument
   * passed to a spy: the engine profile is the thing that turns a mode id into
   * `--permission-mode acceptEdits`, so a test that stopped at the call boundary
   * would keep passing if the mode never reached the CLI.
   */
  describe('#756 — the Master honors a launch mode', () => {
    /** Run an ensure with a stored master block, restoring config after. */
    function ensureWithMaster(masterBlock, opts = {}) {
      const config = store.config.load();
      const saved = config.master;
      try {
        config.master = { accessLevel: 'read-only', engine: null, scope: 'all', autoStart: false, ...masterBlock };
        store.config.save(config);
        const tmuxLib = fakeTmux({ alive: false });
        const r = master.ensureMasterSession({
          home, tmuxLib, enginesLib: opts.enginesLib || availableEngines
        });
        return { result: r, command: tmuxLib.calls.length ? tmuxLib.calls[0].opts.command : null };
      } finally {
        config.master = saved;
        store.config.save(config);
      }
    }

    it('puts the stored mode\'s real flags into the launch command', () => {
      const { result, command } = ensureWithMaster({ launchMode: 'acceptEdits', engine: 'claude' });
      assert.equal(result.created, true);
      assert.match(command, /--permission-mode acceptEdits/,
        'the mode must reach the CLI, not stop at the call boundary');
      assert.equal(result.launchMode, 'acceptEdits');
    });

    it('defaults to the interactive mode when nothing is stored', () => {
      const { result, command } = ensureWithMaster({ engine: 'claude' });
      assert.equal(result.launchMode, 'default');
      assert.doesNotMatch(command, /--permission-mode|--dangerously-skip-permissions/,
        "the default mode adds no flags — it is the engine's own interactive default");
    });

    it('reconciles a mode the effective engine cannot honor down to default', () => {
      // `acceptEdits` is Claude's; aider defines `yesAlways` and knows nothing
      // about it. Passing it through would hand the CLI a flag it rejects.
      const { result, command } = ensureWithMaster(
        { launchMode: 'acceptEdits', engine: 'aider' },
        { enginesLib: enginesInstalling(['aider']) }
      );
      assert.equal(result.launchMode, 'default',
        'an unhonored mode must reconcile, never reach the CLI');
      assert.doesNotMatch(String(command), /acceptEdits/);
    });

    it('does not FLATTEN the stored choice when an engine cannot honor it', () => {
      // The reconcile happens at launch, not at rest. An operator who picks
      // acceptEdits on Claude, switches the Master to aider, and switches back
      // must find their choice intact rather than silently rewritten to
      // 'default' on the way past.
      const config = store.config.load();
      const saved = config.master;
      try {
        config.master = { accessLevel: 'read-only', engine: 'aider', launchMode: 'acceptEdits', scope: 'all', autoStart: false };
        store.config.save(config);
        master.ensureMasterSession({ home, tmuxLib: fakeTmux({ alive: false }), enginesLib: enginesInstalling(['aider']) });
        assert.equal(master.masterSettings(store.config.load()).launchMode, 'acceptEdits',
          'the stored preference must survive an engine that cannot honor it');
      } finally {
        config.master = saved;
        store.config.save(config);
      }
    });

    it('status reports the stored mode, the resolved mode, and what the engine offers', () => {
      const config = store.config.load();
      const saved = config.master;
      try {
        config.master = { accessLevel: 'read-only', engine: 'aider', launchMode: 'acceptEdits', scope: 'all', autoStart: false };
        store.config.save(config);
        const st = master.getMasterStatus({ tmuxLib: fakeTmux({ alive: true }), enginesLib: enginesInstalling(['aider']) });
        assert.equal(st.settings.launchMode, 'acceptEdits', 'what the operator picked');
        assert.equal(st.settings.resolvedLaunchMode, 'default', 'what will actually run');
        assert.ok(Array.isArray(st.settings.launchModes), 'the surface must not re-derive the offered set');
        assert.ok(!st.settings.launchModes.includes('acceptEdits'),
          'aider does not offer acceptEdits, so the picker must not show it as available');
      } finally {
        config.master = saved;
        store.config.save(config);
      }
    });

    it('ships each offered mode with its human label, not a bare id', () => {
      // The project-settings picker renders `m.label || key`; a Master picker
      // showing `acceptEdits` would be the visibly poorer of two controls doing
      // the same job. Shipping the label here keeps the frontend from needing
      // the engine profile at all.
      const st = master.getMasterStatus({ tmuxLib: fakeTmux({ alive: true }), enginesLib: availableEngines });
      assert.ok(st.settings.launchModes.length > 0, 'this fixture must offer modes, or it proves nothing');
      for (const m of st.settings.launchModes) {
        assert.equal(typeof m.id, 'string');
        assert.equal(typeof m.label, 'string');
        assert.ok(m.label.length, `${m.id} must carry a label`);
      }
      const def = st.settings.launchModes.find((m) => m.id === 'default');
      assert.ok(def && def.label !== 'default', 'the label must come from the engine profile, not echo the id');

      // The SAFETY half, which the label assertions above do not cover:
      // data/engines/claude.json marks bypassPermissions with a warning, and
      // dropping it server-side would leave the picker unable to render ⚠ no
      // matter what the frontend does.
      const bypass = st.settings.launchModes.find((m) => m.id === 'bypassPermissions');
      assert.ok(bypass, 'claude offers bypassPermissions, or this fixture proves nothing');
      assert.ok(bypass.warning && bypass.warning.length,
        'a warned mode must carry its warning to the client');
      assert.ok(bypass.description && bypass.description.length,
        'and its description');
      const plain = st.settings.launchModes.find((m) => m.id === 'default');
      assert.equal(plain.warning, null, 'an unwarned mode carries null, not a missing field');
    });

    it('ensure and status agree on the mode that will run', () => {
      // The lockstep hazard `_masterRuntime` exists to prevent: the settings
      // modal must never show one mode while the session launches another.
      const config = store.config.load();
      const saved = config.master;
      try {
        config.master = { accessLevel: 'read-only', engine: 'aider', launchMode: 'plan', scope: 'all', autoStart: false };
        store.config.save(config);
        const lib = enginesInstalling(['aider']);
        const ensured = master.ensureMasterSession({ home, tmuxLib: fakeTmux({ alive: false }), enginesLib: lib });
        const status = master.getMasterStatus({ tmuxLib: fakeTmux({ alive: true }), enginesLib: lib });
        assert.equal(ensured.launchMode, status.settings.resolvedLaunchMode);
      } finally {
        config.master = saved;
        store.config.save(config);
      }
    });
  });

  it('honors master.engine over defaultEngine, and reports instructional enforcement off-claude', () => {
    const config = store.config.load();
    const saved = config.master;
    try {
      // A non-claude engine id that has no profile: the ensure must resolve it
      // (proving master.engine wins) and skip the claude-only guardrails.
      config.master = { accessLevel: 'read-only', engine: 'ghost-engine', scope: 'all', autoStart: false };
      store.config.save(config);
      const r = master.ensureMasterSession({ home, tmuxLib: fakeTmux({ alive: false }), enginesLib: availableEngines });
      assert.equal(r.engine, 'ghost-engine');
      assert.equal(r.enforcement, 'instructional');
      assert.match(r.error, /"ghost-engine" not found/);
      assert.ok(!fs.existsSync(path.join(home, '.claude')), 'claude-only guardrails must not be written for other engines');
    } finally {
      config.master = saved;
      store.config.save(config);
    }
  });
});

describe('master API routes over HTTP', () => {
  let server;

  before(async () => {
    const { createServer } = require('../server');
    server = createServer();
    await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  });

  after(async () => {
    await new Promise((resolve) => server.close(resolve));
  });

  function request(method, urlPath) {
    return new Promise((resolve, reject) => {
      const req = http.request({
        hostname: '127.0.0.1', port: server.address().port, path: urlPath, method,
        headers: { 'Content-Type': 'application/json' }
      }, (res) => {
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => resolve({ status: res.statusCode, data: JSON.parse(Buffer.concat(chunks).toString('utf8')) }));
      });
      req.on('error', reject);
      req.end();
    });
  }

  it('GET /api/master/status returns the tmux-truth shape', async () => {
    const { status, data } = await request('GET', '/api/master/status');
    assert.equal(status, 200);
    // Tri-state, not boolean. This assertion used to read `typeof data.exists
    // === 'boolean'`, which passes on this machine only because tmux answers
    // here — it would have rejected the very state the payload now exists to
    // carry, and it is the one test that hits the real caller shape
    // (`getMasterStatus()` with no options, exactly as `server.js` calls it).
    assert.ok(data.exists === true || data.exists === false || data.exists === null,
      `exists must be true | false | null, got ${JSON.stringify(data.exists)}`);
    assert.ok(Array.isArray(data.incomplete),
      'incomplete is present on every answer, so consumers read it rather than probe for it');
    assert.ok('cause' in data);
    // The two must agree: naming `exists` as unestablished is exactly what null
    // means, and either one without the other is a payload that contradicts
    // itself.
    assert.equal(data.exists === null, data.incomplete.includes('exists'),
      'exists === null and incomplete naming it are the same claim, and must not disagree');
    assert.equal(data.tmuxSession, 'tangleclaw-master');
  });

  it('POST /api/master/ensure returns 200 on success and 500 with a code on refusal', async () => {
    // Stub the module function the route dispatches to — hitting the real one
    // from a test would create a real tmux session and launch a real engine.
    const original = master.ensureMasterSession;
    try {
      master.ensureMasterSession = () => ({ created: true, tmuxSession: 'tangleclaw-master', home: '/tmp/x' });
      const ok = await request('POST', '/api/master/ensure');
      assert.equal(ok.status, 200);
      assert.equal(ok.data.created, true);

      master.ensureMasterSession = () => ({ created: false, tmuxSession: 'tangleclaw-master', home: '/tmp/x', error: 'Engine "claude" not available (binary not found)' });
      const bad = await request('POST', '/api/master/ensure');
      assert.equal(bad.status, 500);
      assert.equal(bad.data.code, 'MASTER_ENSURE_FAILED');
    } finally {
      master.ensureMasterSession = original;
    }
  });
});

describe('refreshMasterIdentity (#726)', () => {
  const os = require('node:os');
  const fsx = require('node:fs');
  const pathx = require('node:path');

  function tmpHome() {
    return fsx.mkdtempSync(pathx.join(os.tmpdir(), 'tc-master-'));
  }

  it('rewrites a stale API base URL without starting a session', () => {
    const home = tmpHome();
    // Simulate an identity generated when the port was wrong — the #726 state.
    fsx.writeFileSync(pathx.join(home, 'CLAUDE.md'),
      '# CLAUDE.md — TangleClaw Project Master\n**TangleClaw API base URL**: `http://localhost:3101`\n');

    const result = master.refreshMasterIdentity({ home });
    assert.equal(result.refreshed, true);

    const after = fsx.readFileSync(pathx.join(home, 'CLAUDE.md'), 'utf8');
    // Assert the API base URL LINE specifically — the file also embeds guide
    // prose that legitimately mentions other ports, so a whole-file search for
    // the stale value reports a false failure.
    const urlLine = (after.match(/\*\*TangleClaw API base URL\*\*: `[^`]+`/) || [])[0];
    assert.ok(urlLine, 'refreshed identity must carry an API base URL line');

    const expectedPort = require('../lib/https-setup').effectiveServerPort(require('../lib/store').config.load());
    assert.match(urlLine, new RegExp(`localhost:${expectedPort}\``),
      `identity should name the effective port ${expectedPort}, got: ${urlLine}`);
  });

  it('does nothing when skipIfAbsent is set and no master home exists', () => {
    const home = pathx.join(os.tmpdir(), `tc-master-absent-${process.pid}`);
    if (fsx.existsSync(home)) fsx.rmSync(home, { recursive: true });

    const result = master.refreshMasterIdentity({ home, skipIfAbsent: true });
    assert.equal(result.refreshed, false, 'must not create master state as a boot side effect');
    assert.equal(fsx.existsSync(home), false, 'the home directory must not be created');
  });

  it('creates the identity when the home exists but the file does not', () => {
    const home = tmpHome();
    const result = master.refreshMasterIdentity({ home, skipIfAbsent: true });
    assert.equal(result.refreshed, true);
    assert.ok(fsx.existsSync(pathx.join(home, 'CLAUDE.md')));
  });
});
