'use strict';

// Chunk G slice 1 (#331) — the Project Master singleton: identity generation,
// idempotent ensure, tmux-truth status, and the two operator API routes.
// The master is deliberately NOT a sessions row / project — tests pin that
// invariant. tmux and engine detection are injected fakes: tests must never
// create a real `tangleclaw-master` session or launch a real engine.

const { describe, it, before, after, beforeEach } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const http = require('node:http');
const { setLevel } = require('../lib/logger');

setLevel('error');

const store = require('../lib/store');
const master = require('../lib/master');

let tmpDir;

before(() => {
  tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-master-'));
  store._setBasePath(tmpDir);
  store.init();
});

after(() => {
  store.close();
  fs.rmSync(tmpDir, { recursive: true, force: true });
});

/** Fake tmux with programmable liveness; records createSession calls. */
function fakeTmux({ alive = false } = {}) {
  const calls = [];
  return {
    calls,
    hasSession: () => alive,
    createSession: (name, opts) => { calls.push({ name, opts }); return true; }
  };
}

const availableEngines = { detectEngine: () => ({ available: true }) };

describe('buildMasterClaudeMd', () => {
  it('carries the generated marker, the role, and the read-only rules', () => {
    const md = master.buildMasterClaudeMd({ serverPort: 3101 });
    assert.match(md, /Generated by TangleClaw — Project Master identity/);
    assert.match(md, /TangleClaw Project Master/);
    assert.match(md, /Read-only\./);
    assert.match(md, /Use only GET endpoints/);
    assert.match(md, /Never edit files outside this directory/);
  });

  it('renders the API base URL from config port and the SERVED protocol (ENG-5R2W)', () => {
    // https only with the full willServeHttps conjunction (flag + both cert paths).
    const md = master.buildMasterClaudeMd({
      serverPort: 3200, httpsEnabled: true,
      httpsCertPath: '/c.pem', httpsKeyPath: '/k.pem'
    });
    assert.match(md, /https:\/\/localhost:3200/);
    const md2 = master.buildMasterClaudeMd({ serverPort: 3102 });
    assert.match(md2, /http:\/\/localhost:3102/);
    // httpsEnabled defaults to true — without cert paths the server serves
    // HTTP (createServer fallback), so the base URL must say http.
    const md3 = master.buildMasterClaudeMd({ serverPort: 3102, httpsEnabled: true });
    assert.match(md3, /http:\/\/localhost:3102/);
  });

  it('renders an http base URL in caddy ingress mode even with full HTTPS config (ENG-5R2W)', () => {
    const md = master.buildMasterClaudeMd({
      serverPort: 3102, ingressMode: 'caddy', httpsEnabled: true,
      httpsCertPath: '/c.pem', httpsKeyPath: '/k.pem'
    });
    assert.match(md, /http:\/\/localhost:3102/);
    assert.doesNotMatch(md, /https:\/\/localhost/);
  });

  it('includes the bearer Authentication block only when the gate is on AND a token exists', () => {
    const on = master.buildMasterClaudeMd({ serviceTokenEnabled: true, serviceToken: 'tcsk_abc' });
    assert.match(on, /Authorization: Bearer tcsk_abc/);
    assert.match(on, /\(bearer token\)/);
    const offNoToken = master.buildMasterClaudeMd({ serviceTokenEnabled: true });
    assert.doesNotMatch(offNoToken, /Authorization: Bearer/);
    const tokenButDisabled = master.buildMasterClaudeMd({ serviceToken: 'tcsk_abc' });
    assert.doesNotMatch(tokenButDisabled, /Authorization: Bearer/);
    assert.doesNotMatch(tokenButDisabled, /\(bearer token\)/);
  });
});

describe('ensureMasterSession', () => {
  let home;

  beforeEach(() => {
    home = path.join(tmpDir, `master-home-${Date.now()}-${Math.random().toString(36).slice(2)}`);
  });

  it('creates the home dir + CLAUDE.md and launches when the session is absent', () => {
    const t = fakeTmux({ alive: false });
    const r = master.ensureMasterSession({ home, tmuxLib: t, enginesLib: availableEngines });
    assert.equal(r.created, true);
    assert.equal(r.tmuxSession, master.MASTER_TMUX_SESSION);
    assert.equal(r.error, undefined);
    const md = fs.readFileSync(path.join(home, 'CLAUDE.md'), 'utf8');
    assert.match(md, /Project Master identity/);
    assert.equal(t.calls.length, 1);
    assert.equal(t.calls[0].name, 'tangleclaw-master');
    assert.equal(t.calls[0].opts.cwd, home, 'session cwd must be the master home');
    assert.ok(t.calls[0].opts.command, 'must send the engine launch command');
  });

  it('is idempotent — an alive session means no second launch, but CLAUDE.md still regenerates', () => {
    const t = fakeTmux({ alive: true });
    fs.mkdirSync(home, { recursive: true });
    fs.writeFileSync(path.join(home, 'CLAUDE.md'), 'stale hand-edit');
    const r = master.ensureMasterSession({ home, tmuxLib: t, enginesLib: availableEngines });
    assert.equal(r.created, false);
    assert.equal(r.error, undefined);
    assert.equal(t.calls.length, 0, 'must not create a second session');
    const md = fs.readFileSync(path.join(home, 'CLAUDE.md'), 'utf8');
    assert.match(md, /Project Master identity/, 'identity must be regenerated on every ensure');
    assert.doesNotMatch(md, /stale hand-edit/);
  });

  it('refuses with an error when the engine binary is unavailable — and does not create tmux', () => {
    const t = fakeTmux({ alive: false });
    const r = master.ensureMasterSession({
      home, tmuxLib: t, enginesLib: { detectEngine: () => ({ available: false }) }
    });
    assert.equal(r.created, false);
    assert.match(r.error, /not available/);
    assert.equal(t.calls.length, 0);
  });

  it('refuses with an error when the configured default engine has no profile', () => {
    const config = store.config.load();
    const saved = config.defaultEngine;
    try {
      config.defaultEngine = 'ghost-engine';
      store.config.save(config);
      const t = fakeTmux({ alive: false });
      const r = master.ensureMasterSession({ home, tmuxLib: t, enginesLib: availableEngines });
      assert.equal(r.created, false);
      assert.match(r.error, /"ghost-engine" not found/);
      assert.equal(t.calls.length, 0);
    } finally {
      config.defaultEngine = saved;
      store.config.save(config);
    }
  });

  it('refuses when the engine is available but has no launch command — no bare-shell master', () => {
    const sessionsLib = require('../lib/sessions');
    const original = sessionsLib._buildLaunchCommand;
    try {
      sessionsLib._buildLaunchCommand = () => undefined;
      const t = fakeTmux({ alive: false });
      const r = master.ensureMasterSession({ home, tmuxLib: t, enginesLib: availableEngines });
      assert.equal(r.created, false);
      assert.match(r.error, /no launch command/);
      assert.equal(t.calls.length, 0, 'must not create a session that would run a bare shell');
    } finally {
      sessionsLib._buildLaunchCommand = original;
    }
  });

  it('surfaces tmux failures as typed errors — create-false and thrown', () => {
    const engines = availableEngines;
    const refusing = { hasSession: () => false, createSession: () => false };
    const r1 = master.ensureMasterSession({ home, tmuxLib: refusing, enginesLib: engines });
    assert.equal(r1.created, false);
    assert.match(r1.error, /Failed to create tmux session/);

    const throwing = { hasSession: () => false, createSession: () => { throw new Error('boom'); } };
    const r2 = master.ensureMasterSession({ home: home + '-t', tmuxLib: throwing, enginesLib: engines });
    assert.equal(r2.created, false);
    assert.match(r2.error, /tmux error: boom/);
  });

  it('never records a sessions-table row — the master is not a project session', () => {
    // Structural guard (the TB-3 no-HTTP-client pattern): the module must not
    // touch the sessions store at all — its only lib/sessions dependency is
    // the launch-command builder.
    const src = fs.readFileSync(path.join(__dirname, '..', 'lib', 'master.js'), 'utf8');
    assert.doesNotMatch(src, /store\.sessions/,
      'lib/master.js must never read or write the sessions table');
    assert.doesNotMatch(src, /sessions\.launchSession/,
      'the master must not go through the project launch path');
  });
});

describe('getMasterStatus', () => {
  it('reports liveness straight from tmux', () => {
    assert.equal(master.getMasterStatus({ tmuxLib: fakeTmux({ alive: true }) }).exists, true);
    assert.equal(master.getMasterStatus({ tmuxLib: fakeTmux({ alive: false }) }).exists, false);
    assert.equal(master.getMasterStatus({ tmuxLib: fakeTmux() }).tmuxSession, 'tangleclaw-master');
  });
});

describe('master API routes over HTTP', () => {
  let server;

  before(async () => {
    const { createServer } = require('../server');
    server = createServer();
    await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  });

  after(async () => {
    await new Promise((resolve) => server.close(resolve));
  });

  function request(method, urlPath) {
    return new Promise((resolve, reject) => {
      const req = http.request({
        hostname: '127.0.0.1', port: server.address().port, path: urlPath, method,
        headers: { 'Content-Type': 'application/json' }
      }, (res) => {
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => resolve({ status: res.statusCode, data: JSON.parse(Buffer.concat(chunks).toString('utf8')) }));
      });
      req.on('error', reject);
      req.end();
    });
  }

  it('GET /api/master/status returns the tmux-truth shape', async () => {
    const { status, data } = await request('GET', '/api/master/status');
    assert.equal(status, 200);
    assert.equal(typeof data.exists, 'boolean');
    assert.equal(data.tmuxSession, 'tangleclaw-master');
  });

  it('POST /api/master/ensure returns 200 on success and 500 with a code on refusal', async () => {
    // Stub the module function the route dispatches to — hitting the real one
    // from a test would create a real tmux session and launch a real engine.
    const original = master.ensureMasterSession;
    try {
      master.ensureMasterSession = () => ({ created: true, tmuxSession: 'tangleclaw-master', home: '/tmp/x' });
      const ok = await request('POST', '/api/master/ensure');
      assert.equal(ok.status, 200);
      assert.equal(ok.data.created, true);

      master.ensureMasterSession = () => ({ created: false, tmuxSession: 'tangleclaw-master', home: '/tmp/x', error: 'Engine "claude" not available (binary not found)' });
      const bad = await request('POST', '/api/master/ensure');
      assert.equal(bad.status, 500);
      assert.equal(bad.data.code, 'MASTER_ENSURE_FAILED');
    } finally {
      master.ensureMasterSession = original;
    }
  });
});
