'use strict';

/*
 * Provenance on the whole-file engine carriers `.codex.yaml` and
 * `.aider.conf.yml` (ADR 0019). They are eligible only while git ignores them.
 * The #1619 predicate that keeps project identity out of committed carriers
 * decides both insertion and removal, so a carrier that becomes tracked loses
 * its line at its next regeneration.
 *
 * The line goes beneath the `Generated by TangleClaw` header and never above
 * it. The retire path reads that header in the first three lines as permission
 * to overwrite the file, and a provenance line must not move it.
 */

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const { execFileSync } = require('node:child_process');
const { setLevel } = require('../lib/logger');
setLevel('error');
const store = require('../lib/store');
const engines = require('../lib/engines');
const provenance = require('../lib/provenance');

const ON = { provenanceWatermark: { enabled: true, template: null } };

describe('provenance on whole-file engine carriers', () => {
  let tmpDir;
  let seq = 0;

  before(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-prov-carriers-'));
    store._setBasePath(tmpDir);
    store.init();
  });

  after(() => {
    store.close();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  /**
   * A real repository that ignores its engine-private carriers, which is what
   * a managed project looks like, registered under a known name.
   * @param {string} engineId
   * @returns {{name: string, dir: string}}
   */
  function makeRepo(engineId) {
    const name = `prov-carrier-${++seq}`;
    const dir = fs.mkdtempSync(path.join(tmpDir, `${name}-`));
    execFileSync('git', ['-C', dir, 'init', '-q']);
    fs.writeFileSync(path.join(dir, '.gitignore'), '.codex.yaml\n.aider.conf.yml\n');
    store.projects.create({ name, path: dir, engine: engineId });
    return { name, dir };
  }

  /**
   * @param {string} engineId
   * @param {string} dir
   * @param {object} extra - Project config keys beyond the engine.
   * @returns {{result: object, text: string, lines: string[]}}
   */
  function write(engineId, dir, extra) {
    const result = engines.writeEngineConfig(engineId, dir, { engine: engineId, ...extra }, store.engines.get(engineId));
    const text = fs.readFileSync(result.configFilePath, 'utf8');
    return { result, text, lines: text.split('\n') };
  }

  for (const [engineId, filename] of [['codex', '.codex.yaml'], ['aider', '.aider.conf.yml']]) {
    describe(filename, () => {
      it('reports no drift when only TangleClaw\'s own line changed', () => {
        const { dir } = makeRepo(engineId);
        write(engineId, dir, {});
        assert.equal(write(engineId, dir, ON).result.drifted, false, 'turning it on');
        assert.equal(write(engineId, dir, { provenanceWatermark: { enabled: true, template: 'Other {project}' } }).result.drifted, false,
          'changing the template');
        assert.equal(write(engineId, dir, {}).result.drifted, false, 'turning it off');
        fs.appendFileSync(path.join(dir, filename), '# an operator edit\n');
        assert.equal(write(engineId, dir, ON).result.drifted, true, 'a real hand-edit is still drift');
      });

      it('is byte-identical to a write without the setting while it is off', () => {
        const { dir } = makeRepo(engineId);
        const off = write(engineId, dir, {}).text;
        const explicitOff = write(engineId, dir, { provenanceWatermark: { enabled: false, template: 'x {project}' } }).text;
        assert.equal(explicitOff, off);
        assert.ok(!off.includes(provenance.SENTINEL));
      });

      it('puts one line directly beneath the generated header while the carrier is ignored', () => {
        const { name, dir } = makeRepo(engineId);
        const { lines, result } = write(engineId, dir, ON);
        assert.equal(result.error, null);
        assert.equal(lines[0], '# Generated by TangleClaw', 'the header stays on line 1');
        assert.equal(lines[1], `# tangleclaw:provenance Built by TangleClaw (Project: ${name})`);
        assert.equal(lines.filter((l) => l.includes(provenance.SENTINEL)).length, 1);
      });

      it('regenerating does not stack a second line or report drift', () => {
        const { dir } = makeRepo(engineId);
        const first = write(engineId, dir, ON).text;
        const again = write(engineId, dir, ON);
        assert.equal(again.text, first);
        assert.equal(again.result.drifted, false, 'the stamped file is what this write produces, not an operator edit');
      });

      it('the retire path still recognises the stamped file as generated', () => {
        const { dir } = makeRepo(engineId);
        const { text } = write(engineId, dir, ON);
        assert.ok(text.split('\n').slice(0, 3).some((l) => l.includes('Generated by TangleClaw')));
        const retired = engines.retireInactiveEngineConfig(dir, engineId, 'claude');
        assert.equal(retired.retired, true, JSON.stringify(retired));
      });

      it('a carrier that becomes tracked loses its line at the next regeneration, and regains it once ignored again', () => {
        const { dir } = makeRepo(engineId);
        assert.ok(write(engineId, dir, ON).text.includes(provenance.SENTINEL), 'precondition: stamped while ignored');

        fs.writeFileSync(path.join(dir, '.gitignore'), '');
        execFileSync('git', ['-C', dir, 'add', filename]);
        const tracked = write(engineId, dir, ON);
        assert.ok(!tracked.text.includes(provenance.SENTINEL), 'a tracked carrier carries no provenance line');
        assert.equal(tracked.lines[0], '# Generated by TangleClaw');

        execFileSync('git', ['-C', dir, 'rm', '-q', '-f', '--cached', filename]);
        fs.writeFileSync(path.join(dir, '.gitignore'), `${filename}\n`);
        assert.ok(write(engineId, dir, ON).text.includes(provenance.SENTINEL), 'eligible again once ignored');
      });

      it('when git cannot answer, the carrier counts as committed and gets no line', () => {
        const { dir } = makeRepo(engineId);
        const saved = engines._internal.checkIgnore;
        engines._internal.checkIgnore = () => null;
        try {
          assert.ok(!write(engineId, dir, ON).text.includes(provenance.SENTINEL));
        } finally {
          engines._internal.checkIgnore = saved;
        }
      });

      it('while off, the write asks git nothing on the setting\'s behalf', () => {
        const { dir } = makeRepo(engineId);
        const saved = engines._internal.checkIgnore;
        let asked = 0;
        const baseline = () => { asked = 0; engines._internal.checkIgnore = (...a) => { asked++; return saved(...a); }; };
        try {
          baseline();
          write(engineId, dir, {});
          const offCalls = asked;
          baseline();
          write(engineId, dir, ON);
          assert.equal(asked, offCalls + 1, 'on adds exactly the one tracked-carrier question; off adds none');
        } finally {
          engines._internal.checkIgnore = saved;
        }
      });

      for (const [label, config] of [['off', {}], ['on', ON]]) {
        it(`${label}: the carrier is written in place, keeping its mode, its symlink and a read-only refusal`, () => {
          const { dir } = makeRepo(engineId);
          const file = path.join(dir, filename);
          write(engineId, dir, config);

          // A tightened mode survives: the carrier can hold a bearer token (#1619).
          fs.chmodSync(file, 0o600);
          write(engineId, dir, config);
          assert.equal(fs.statSync(file).mode & 0o777, 0o600, 'mode kept');

          // A symlinked carrier stays a symlink, and its target gets the content.
          const target = path.join(dir, 'real-carrier.yml');
          fs.renameSync(file, target);
          fs.symlinkSync(target, file);
          write(engineId, dir, config);
          assert.ok(fs.lstatSync(file).isSymbolicLink(), 'symlink kept');
          assert.ok(fs.readFileSync(target, 'utf8').startsWith('# Generated by TangleClaw'));
          fs.rmSync(file);
          fs.renameSync(target, file);

          // A read-only carrier is a reported failure, not a silent replacement.
          if (process.getuid && process.getuid() === 0) return; // root writes through 0444
          fs.chmodSync(file, 0o444);
          try {
            const r = engines.writeEngineConfig(engineId, dir, { engine: engineId, ...config }, store.engines.get(engineId));
            assert.equal(r.written, false);
            assert.match(r.error, /EACCES|permission/i);
          } finally {
            fs.chmodSync(file, 0o644);
          }
        });
      }

      it('turning the setting off removes the line at the next regeneration', () => {
        const { dir } = makeRepo(engineId);
        const stamped = write(engineId, dir, ON).text;
        const cleared = write(engineId, dir, {}).text;
        assert.ok(stamped.includes(provenance.SENTINEL));
        assert.ok(!cleared.includes(provenance.SENTINEL));
      });
    });
  }

  it('the claude carrier is not a provenance surface, even while ignored (whole-file CLAUDE.md is excluded)', () => {
    const { dir } = makeRepo('claude');
    fs.writeFileSync(path.join(dir, '.gitignore'), 'CLAUDE.md\n');
    const { text } = write('claude', dir, ON);
    assert.ok(!text.includes(provenance.SENTINEL));
  });
});
