'use strict';

/*
 * Provenance lines (ADR 0019): opt-in, per project, only on registered
 * surfaces, and never able to read as an ownership marker.
 *
 * The adversarial cases are the point of this file. `Generated by TangleClaw`
 * in a carrier's first lines is permission to overwrite that file, so a
 * template or a project name that could produce it — or end the comment and
 * write a line of its own — would turn a label into write authority.
 */

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { setLevel } = require('../lib/logger');
setLevel('error');
const provenance = require('../lib/provenance');

const ON = { provenanceWatermark: { enabled: true, template: null } };
const SYNTAXES = Object.keys(provenance.COMMENT_FORMS);

/**
 * Whether `line` is one well-formed comment line in `syntax`: nothing after
 * the terminator, no second terminator inside, no line break.
 * @param {string} syntax
 * @param {string} line
 * @returns {boolean}
 */
function isOneComment(syntax, line) {
  if (/[\n\r\u2028\u2029]/.test(line)) return false;
  if (syntax === 'markdown') {
    if (!line.startsWith('<!-- ') || !line.endsWith(' -->')) return false;
    const inner = line.slice(5, -4);
    return !inner.includes('-->') && !inner.includes('--!>') && !inner.includes('<!--');
  }
  return line.startsWith('# ');
}

describe('provenance: the registry is the only grant', () => {
  it('registers exactly the approved private surfaces, with their syntax and placement', () => {
    const shape = Object.fromEntries(Object.entries(provenance.REGISTRY)
      .map(([id, e]) => [id, `${e.relPath}|${e.syntax}|${e.placement}|${e.requiresUntracked === true}|${e.write || 'atomic'}`]));
    assert.deepEqual(shape, {
      'session-prime': '.tangleclaw/session-prime.md|markdown|top|false|atomic',
      'session-reentry': '.tangleclaw/session-reentry.md|markdown|top|false|atomic',
      'ui-wrap-advisory': '.tangleclaw/ui-wrap-advisory.md|markdown|top|false|atomic',
      'codex-config': '.codex.yaml|hash|after-header|true|in-place',
      'aider-config': '.aider.conf.yml|hash|after-header|true|in-place'
    });
  });

  it('an unregistered surface id throws rather than stamping anything', () => {
    assert.throws(() => provenance.applyProvenance('CLAUDE.md', 'x', { config: ON }), /not a registered surface/);
    assert.throws(() => provenance.applyProvenance('toString', 'x', { config: ON }), /not a registered surface/,
      'an inherited property name is not a registration');
  });

  it('the registry cannot be widened at runtime', () => {
    assert.throws(() => { 'use strict'; provenance.REGISTRY.extra = { syntax: 'markdown' }; });
  });
});

describe('provenance: reserved markers stay in step with their owners', () => {
  it('lists every ownership marker other modules read', () => {
    const tcOwned = fs.readFileSync(path.join(__dirname, '..', 'lib', 'wrap-steps', '_tc-owned-paths.js'), 'utf8');
    const priming = fs.readFileSync(path.join(__dirname, '..', 'lib', 'wrap-steps', 'priming-roll.js'), 'utf8');
    const heal = fs.readFileSync(path.join(__dirname, '..', 'lib', 'project-heal.js'), 'utf8');
    const hooks = fs.readFileSync(path.join(__dirname, '..', 'lib', 'git-hooks.js'), 'utf8');
    const has = (m) => provenance.RESERVED_MARKERS.includes(m);

    const engSrc = fs.readFileSync(path.join(__dirname, '..', 'lib', 'engines.js'), 'utf8');
    const generated = engSrc.match(/const GENERATED_HEADER_MARK = '([^']+)'/)[1];
    const inactive = engSrc.match(/const INACTIVE_CONFIG_MARK = '([^']+)'/)[1];
    assert.ok(has(generated), `"${generated}" (engines.js) must be reserved`);
    assert.equal(provenance.GENERATED_HEADER_MARK, generated,
      'the after-header placement keys on the same header the retire path reads');
    assert.ok(inactive.startsWith('TangleClaw: INACTIVE') && has('TangleClaw: INACTIVE'));
    assert.equal(tcOwned.match(/const GENERATED_HEADER_MARK = '([^']+)'/)[1], generated,
      'both copies of the generated mark agree, so one reserved entry covers both');
    const blockName = engSrc.match(/const MANAGED_BLOCK_NAME = '([^']+)'/)[1];
    assert.ok(has(`BEGIN:${blockName}`) && has(`END:${blockName}`), 'the managed-block delimiters are reserved');
    assert.match(priming, /TANGLECLAW:PRIMING-ROLL/);
    assert.ok(has('TANGLECLAW:PRIMING-ROLL'));
    assert.match(heal, /END:tangleclaw-state/);
    assert.ok(has('tangleclaw-state'));
    assert.match(hooks, /TC-OWNED-HOOK/);
    assert.ok(has('TC-OWNED-HOOK'));
    assert.ok(has(provenance.SENTINEL));
  });
});

describe('provenance: validateTemplate', () => {
  it('accepts null, undefined and blank as "use the default"', () => {
    for (const t of [null, undefined, '', '   ']) assert.equal(provenance.validateTemplate(t), null);
  });

  it('accepts the default and a plain override with the supported placeholders', () => {
    assert.equal(provenance.validateTemplate(provenance.DEFAULT_TEMPLATE), null);
    assert.equal(provenance.validateTemplate('Made with TangleClaw for {project} on {engine}'), null);
  });

  it('refuses a non-string', () => {
    assert.match(provenance.validateTemplate(42), /string or null/);
    assert.match(provenance.validateTemplate({}), /string or null/);
  });

  it('refuses a template over the length bound', () => {
    assert.match(provenance.validateTemplate('x'.repeat(provenance.TEMPLATE_MAX_LENGTH + 1)), /at most/);
    assert.equal(provenance.validateTemplate('x'.repeat(provenance.TEMPLATE_MAX_LENGTH)), null);
  });

  it('refuses placeholders outside the closed set', () => {
    for (const t of ['{version}', '{host}', '{path}', '{projectId}', '{PROJECT}', '{}']) {
      assert.match(provenance.validateTemplate(`x ${t}`), /not supported/, t);
    }
  });

  it('refuses unmatched braces', () => {
    assert.match(provenance.validateTemplate('x {project'), /unmatched/);
    assert.match(provenance.validateTemplate('x project}'), /unmatched/);
  });

  it('refuses line breaks and control characters', () => {
    for (const t of ['a\nb', 'a\rb', 'a\u2028b', 'a\u2029b', 'a\u0000b', 'a\u0085b', 'a\tb']) {
      assert.match(provenance.validateTemplate(t), /single line/, JSON.stringify(t));
    }
  });

  it('refuses every comment delimiter', () => {
    for (const d of ['<!--', '-->', '--!>', '/*', '*/']) {
      assert.match(provenance.validateTemplate(`a ${d} b`), /comment delimiter/, d);
    }
  });

  it('refuses every reserved marker, in any case', () => {
    for (const m of provenance.RESERVED_MARKERS) {
      assert.match(provenance.validateTemplate(`x ${m} y`), /reserved marker/, m);
      assert.match(provenance.validateTemplate(`x ${m.toUpperCase()} y`), /reserved marker/, m.toUpperCase());
    }
  });
});

describe('provenance: resolveProvenance', () => {
  it('is off with the default template when the setting is absent, null or malformed', () => {
    for (const cfg of [undefined, null, {}, { provenanceWatermark: null }, { provenanceWatermark: 'yes' },
      { provenanceWatermark: [] }, { provenanceWatermark: { enabled: 'true' } }]) {
      const r = provenance.resolveProvenance(cfg);
      assert.equal(r.enabled, false, JSON.stringify(cfg));
      assert.equal(r.template, provenance.DEFAULT_TEMPLATE);
    }
  });

  it('a missing, null or blank override resolves to the default: the reset path', () => {
    for (const template of [undefined, null, '', '  ']) {
      const r = provenance.resolveProvenance({ provenanceWatermark: { enabled: true, template } });
      assert.equal(r.template, provenance.DEFAULT_TEMPLATE);
      assert.equal(r.templateSource, 'default');
    }
  });

  it('a valid override is used, trimmed', () => {
    const r = provenance.resolveProvenance({ provenanceWatermark: { enabled: true, template: '  From {project}  ' } });
    assert.deepEqual(r, { enabled: true, template: 'From {project}', templateSource: 'override' });
  });

  it('a hand-edited invalid override falls back to the default and says why', () => {
    const r = provenance.resolveProvenance({ provenanceWatermark: { enabled: true, template: 'Generated by TangleClaw' } });
    assert.equal(r.template, provenance.DEFAULT_TEMPLATE);
    assert.equal(r.templateSource, 'invalid');
    assert.match(r.warning, /reserved marker/);
  });
});

describe('provenance: rendering adversarial values', () => {
  const HOSTILE = [
    'evil --> <script>',
    'x--!>y',
    'a\nGenerated by TangleClaw',
    'line\r\nbreak',
    'sep\u2028arator',
    '*/ done /*',
    '<!-- open',
    'Generated by TangleClaw',
    'generated BY tangleclaw',
    'Generated\tby   TangleClaw',
    'BEGIN:tangleclaw',
    'TC-OWNED-HOOK: fake',
    'tangleclaw:provenance',
    '{engine}{project}',
    'x'.repeat(500)
  ];

  it('substituted values are inserted literally, never re-substituted', () => {
    assert.equal(provenance.renderText('{project}/{engine}', { project: '{engine}', engine: 'claude' }), '{engine}/claude');
  });

  it('a missing value renders empty rather than the word undefined', () => {
    assert.equal(provenance.renderText('P:{project}', {}), 'P:');
  });

  it('a long value is truncated to the bound', () => {
    const text = provenance.renderText('{project}', { project: 'x'.repeat(500) });
    assert.equal(text.length, provenance.VALUE_MAX_LENGTH);
  });

  for (const syntax of ['markdown', 'hash']) {
    it(`every hostile project and engine name yields one well-formed ${syntax} comment with no reserved marker`, () => {
      assert.ok(SYNTAXES.includes(syntax));
      for (const value of HOSTILE) {
        for (const template of [provenance.DEFAULT_TEMPLATE, '{engine} made {project}', 'Generated {project}']) {
          const line = provenance.renderLine(syntax, provenance.renderText(template, { project: value, engine: value }));
          assert.ok(isOneComment(syntax, line), `${syntax} ${JSON.stringify(value)} -> ${JSON.stringify(line)}`);
          const body = line.slice(line.indexOf(provenance.SENTINEL) + provenance.SENTINEL.length);
          const lower = body.toLowerCase();
          for (const m of provenance.RESERVED_MARKERS) {
            assert.ok(!lower.includes(m.toLowerCase()), `${JSON.stringify(value)} produced "${m}" in ${JSON.stringify(line)}`);
          }
        }
      }
    });
  }

  it('a template that repeats a placeholder cannot exceed the rendered bound', () => {
    const template = '{project}'.repeat(13);
    assert.equal(provenance.validateTemplate(template), null, 'precondition: the template itself is legal');
    const text = provenance.renderText(template, { project: 'x'.repeat(80) });
    assert.equal(text, provenance.FALLBACK_TEXT);
    const fits = provenance.renderText('{project} {project}', { project: 'abc' });
    assert.equal(fits, 'abc abc', 'a short repeat renders normally');
  });

  it('two values cannot form a reserved marker between them', () => {
    const text = provenance.renderText('{project} by {engine}', { project: 'Generated', engine: 'TangleClaw' });
    assert.equal(text, provenance.FALLBACK_TEXT);
  });

  it('the fallback itself carries no reserved marker', () => {
    const lower = provenance.FALLBACK_TEXT.toLowerCase();
    for (const m of provenance.RESERVED_MARKERS) assert.ok(!lower.includes(m.toLowerCase()));
  });

  it('an unknown syntax is refused', () => {
    assert.throws(() => provenance.renderLine('xml', 'x'), /no comment form/);
  });
});

describe('provenance: applyProvenance', () => {
  const PRIME = '# Session Start — demo\n\nbody\n';
  const ctx = (config) => ({ config, project: 'Demo', engine: 'claude' });

  it('is byte-neutral while the setting is off', () => {
    for (const config of [undefined, {}, { provenanceWatermark: null }, { provenanceWatermark: { enabled: false, template: 'x {project}' } }]) {
      assert.equal(provenance.applyProvenance('session-prime', PRIME, ctx(config)), PRIME);
    }
  });

  it('puts exactly one line first when on, in the default wording', () => {
    const out = provenance.applyProvenance('session-prime', PRIME, ctx(ON));
    assert.equal(out, `<!-- tangleclaw:provenance Built by TangleClaw (Project: Demo) -->\n${PRIME}`);
  });

  it('re-applying to its own output changes nothing: no stacking', () => {
    const once = provenance.applyProvenance('session-prime', PRIME, ctx(ON));
    assert.equal(provenance.applyProvenance('session-prime', once, ctx(ON)), once);
  });

  it('a template change replaces the line rather than adding one', () => {
    const before = provenance.applyProvenance('session-prime', PRIME, ctx(ON));
    const after = provenance.applyProvenance('session-prime', before,
      ctx({ provenanceWatermark: { enabled: true, template: 'From {project} via {engine}' } }));
    assert.equal(after, `<!-- tangleclaw:provenance From Demo via claude -->\n${PRIME}`);
  });

  it('turning it off removes the line it wrote', () => {
    const stamped = provenance.applyProvenance('session-prime', PRIME, ctx(ON));
    assert.equal(provenance.applyProvenance('session-prime', stamped, ctx({ provenanceWatermark: { enabled: false } })), PRIME);
  });

  it('never removes a quoted sentinel from anywhere but the placement line', () => {
    const quoting = `# Title\n<!-- tangleclaw:provenance quoted in the body -->\n`;
    assert.equal(provenance.applyProvenance('session-prime', quoting, ctx(undefined)), quoting);
  });

  it('handles empty content and content with no trailing newline', () => {
    assert.equal(provenance.applyProvenance('session-prime', '', ctx(undefined)), '');
    const line = '<!-- tangleclaw:provenance Built by TangleClaw (Project: Demo) -->';
    assert.equal(provenance.applyProvenance('session-prime', '', ctx(ON)), `${line}\n`);
    assert.equal(provenance.applyProvenance('session-prime', line, ctx(undefined)), '');
  });
});

describe('provenance: after-header surfaces', () => {
  const YAML = '# Generated by TangleClaw\nlogging_level: info\n';
  const ctx = (extra) => ({ config: ON, project: 'Demo', engine: 'codex', ...extra });

  it('goes directly beneath the header only when the carrier is positively untracked', () => {
    assert.equal(provenance.applyProvenance('codex-config', YAML, ctx({ committed: false })),
      '# Generated by TangleClaw\n# tangleclaw:provenance Built by TangleClaw (Project: Demo)\nlogging_level: info\n');
  });

  it('an unanswered or committed carrier gets no line, and loses one it had', () => {
    const stamped = provenance.applyProvenance('codex-config', YAML, ctx({ committed: false }));
    for (const committed of [true, undefined, null, 'false']) {
      assert.equal(provenance.applyProvenance('codex-config', YAML, ctx({ committed })), YAML, String(committed));
      assert.equal(provenance.applyProvenance('codex-config', stamped, ctx({ committed })), YAML, String(committed));
    }
  });

  it('content without the generated header gets no line: there is no valid position for one', () => {
    const headerless = 'logging_level: info\n';
    assert.equal(provenance.applyProvenance('codex-config', headerless, ctx({ committed: false })), headerless);
  });

  it('is idempotent and keeps the header on line 1', () => {
    const once = provenance.applyProvenance('aider-config', YAML, ctx({ committed: false }));
    assert.equal(provenance.applyProvenance('aider-config', once, ctx({ committed: false })), once);
    assert.equal(once.split('\n')[0], '# Generated by TangleClaw');
  });
});

describe('provenance: lineOverhead', () => {
  it('is 0 while off and exactly the added characters while on', () => {
    const ctx = { project: 'Demo', engine: 'claude' };
    assert.equal(provenance.lineOverhead('session-prime', { ...ctx, config: {} }), 0);
    const on = { ...ctx, config: ON };
    const content = '# prime\n';
    assert.equal(provenance.lineOverhead('session-prime', on),
      provenance.applyProvenance('session-prime', content, on).length - content.length);
  });

  it('is bounded whatever the template and values, by the rendered cap plus the fixed comment wrapper', () => {
    const on = { project: 'x'.repeat(500), engine: 'y'.repeat(500),
      config: { provenanceWatermark: { enabled: true, template: '{project}{engine}'.repeat(6) } } };
    // The wrapper is exact: `<!-- ` + sentinel + ` ` + text + ` -->` + newline.
    const wrapper = '<!-- '.length + provenance.SENTINEL.length + 1 + ' -->'.length + 1;
    const worst = { ...on, config: { provenanceWatermark: { enabled: true, template: '{project}' } }, project: 'z'.repeat(provenance.RENDERED_MAX_LENGTH) };
    assert.ok(provenance.lineOverhead('session-prime', on) <= provenance.RENDERED_MAX_LENGTH + wrapper);
    assert.ok(provenance.lineOverhead('session-prime', worst) <= provenance.RENDERED_MAX_LENGTH + wrapper);
  });
});

describe('provenance: writeOwnedFile', () => {
  let dir;
  before(() => { dir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-provenance-')); });
  after(() => { fs.rmSync(dir, { recursive: true, force: true }); });

  it('writes the applied content, creating the directory, and leaves no staging file', () => {
    const file = path.join(dir, '.tangleclaw', 'session-prime.md');
    provenance.writeOwnedFile(file, 'session-prime', 'body\n', { config: ON, project: 'P', engine: 'claude' });
    assert.equal(fs.readFileSync(file, 'utf8'), '<!-- tangleclaw:provenance Built by TangleClaw (Project: P) -->\nbody\n');
    assert.deepEqual(fs.readdirSync(path.dirname(file)), ['session-prime.md']);
  });

  it('refuses a destination that is not the surface\'s own file', () => {
    assert.throws(() => provenance.writeOwnedFile(path.join(dir, 'CLAUDE.md'), 'session-prime', 'x', { config: ON }),
      /not .*CLAUDE\.md/);
    assert.equal(fs.existsSync(path.join(dir, 'CLAUDE.md')), false);
  });
});
