'use strict';

/*
 * The per-project provenance setting's write path (ADR 0019): the validator
 * refuses what the renderer would discard, a partial PATCH keeps what it does
 * not mention, and clearing the template is the reset to the default.
 */

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { setLevel } = require('../lib/logger');
setLevel('error');
const store = require('../lib/store');
const provenance = require('../lib/provenance');

describe('provenanceWatermark project setting', () => {
  let tmpDir;
  let projectsDir;
  let projects;
  let seq = 0;

  before(() => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-provenance-settings-'));
    store._setBasePath(tmpDir);
    store.init();
    projectsDir = path.join(tmpDir, 'projects');
    fs.mkdirSync(projectsDir, { recursive: true });
    const config = store.config.load();
    config.projectsDir = projectsDir;
    store.config.save(config);
    projects = require('../lib/projects');
  });

  after(() => {
    store.close();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  /**
   * A fresh project with an optional stored provenance setting.
   * @param {object|null} [stored] - Stored provenanceWatermark value.
   * @returns {{name: string, dir: string}}
   */
  function makeProject(stored) {
    const name = `prov-${++seq}`;
    const dir = path.join(projectsDir, name);
    fs.mkdirSync(dir, { recursive: true });
    store.projects.create({ name, path: dir, engine: 'claude' });
    const cfg = JSON.parse(JSON.stringify(store.DEFAULT_PROJECT_CONFIG));
    cfg.engine = 'claude';
    if (stored !== undefined) cfg.provenanceWatermark = stored;
    store.projectConfig.save(dir, cfg);
    return { name, dir };
  }

  /** @param {string} dir @returns {unknown} */
  const stored = (dir) => store.projectConfig.load(dir).provenanceWatermark;

  it('defaults to null, which resolves to off', () => {
    assert.equal(store.DEFAULT_PROJECT_CONFIG.provenanceWatermark, null);
    const { dir } = makeProject();
    assert.equal(provenance.resolveProvenance(store.projectConfig.load(dir)).enabled, false);
  });

  it('enables with the default template', async () => {
    const { name, dir } = makeProject();
    const r = await projects.updateProject(name, { provenanceWatermark: { enabled: true } });
    assert.deepEqual(r.errors, []);
    assert.deepEqual(stored(dir), { enabled: true, template: null });
  });

  it('a PATCH carrying only enabled keeps the stored template', async () => {
    const { name, dir } = makeProject({ enabled: true, template: 'From {project}' });
    await projects.updateProject(name, { provenanceWatermark: { enabled: false } });
    assert.deepEqual(stored(dir), { enabled: false, template: 'From {project}' });
  });

  it('a PATCH carrying only a template keeps enabled', async () => {
    const { name, dir } = makeProject({ enabled: true, template: null });
    await projects.updateProject(name, { provenanceWatermark: { template: '  Via {engine}  ' } });
    assert.deepEqual(stored(dir), { enabled: true, template: 'Via {engine}' }, 'trimmed on the way in');
  });

  it('a blank or null template is stored as null: the reset to the default', async () => {
    for (const template of ['', '   ', null]) {
      const { name, dir } = makeProject({ enabled: true, template: 'From {project}' });
      const r = await projects.updateProject(name, { provenanceWatermark: { template } });
      assert.deepEqual(r.errors, []);
      assert.deepEqual(stored(dir), { enabled: true, template: null }, JSON.stringify(template));
      assert.equal(provenance.resolveProvenance(store.projectConfig.load(dir)).template, provenance.DEFAULT_TEMPLATE);
    }
  });

  it('null resets the whole setting', async () => {
    const { name, dir } = makeProject({ enabled: true, template: 'From {project}' });
    await projects.updateProject(name, { provenanceWatermark: null });
    assert.equal(stored(dir), null);
  });

  it('refuses malformed input and stores nothing', async () => {
    const cases = [
      [true, /object or null/],
      [[], /object or null/],
      [{}, /must set enabled or template/],
      [{ enabled: 'yes' }, /enabled must be a boolean/],
      [{ enabled: true, label: 'x' }, /label cannot be set/],
      [{ template: 7 }, /string or null/],
      [{ template: 'v{version}' }, /not supported/],
      [{ template: 'a\nb' }, /single line/],
      [{ template: 'x --> y' }, /comment delimiter/],
      [{ template: 'Generated by TangleClaw' }, /reserved marker/]
    ];
    for (const [patch, pattern] of cases) {
      const { name, dir } = makeProject({ enabled: false, template: null });
      const r = await projects.updateProject(name, { provenanceWatermark: patch });
      assert.equal(r.project, null, JSON.stringify(patch));
      assert.match(r.errors[0], pattern, JSON.stringify(patch));
      assert.deepEqual(stored(dir), { enabled: false, template: null }, `${JSON.stringify(patch)} must not be stored`);
    }
  });
});
