'use strict';

// GET /api/setup/ingress-state — the read-only probe the setup wizard uses to
// decide how to put a login in front of this install without destroying one the
// operator already built. Sibling of /api/setup/https-check: detection only,
// never a write.
//
// The security property under test alongside the states: the probe must not
// hand out the credential hash, and must not enumerate account names. It runs
// before setup completes, which is exactly when no gate exists yet.

const { describe, it, before, after, beforeEach } = require('node:test');
const assert = require('node:assert/strict');
const http = require('node:http');
const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const { setLevel } = require('../lib/logger');
const store = require('../lib/store');
const caddy = require('../lib/caddy');
const { createServer } = require('../server');

setLevel('error');

// Exactly 53 chars of [./A-Za-z0-9] after `$2a$14$` — the real bcrypt shape.
const BCRYPT_A = '$2a$14$abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0';
const BCRYPT_B = '$2a$14$zyxwvutsrqponmlkjihgfedcbaZYXWVUTSRQPONMLKJIHGFEDCBA9';

/**
 * Make a GET request to the test server.
 * @param {http.Server} server
 * @param {string} urlPath
 * @returns {Promise<{ status: number, data: any, raw: string }>}
 */
function get(server, urlPath) {
  return new Promise((resolve, reject) => {
    const addr = server.address();
    const req = http.request(
      { hostname: '127.0.0.1', port: addr.port, path: urlPath, method: 'GET' },
      (res) => {
        const chunks = [];
        res.on('data', (c) => chunks.push(c));
        res.on('end', () => {
          const raw = Buffer.concat(chunks).toString('utf8');
          let data;
          try { data = JSON.parse(raw); } catch { data = raw; }
          resolve({ status: res.statusCode, data, raw });
        });
      }
    );
    req.on('error', reject);
    req.end();
  });
}

/** Build a hand-edited Caddyfile (no integrity stamp) with the given credential lines. */
function handEdited(credentialLines) {
  return [
    '# Generated by TangleClaw (AUTH-1 / lib/caddy.js) — do not hand-edit.',
    '# NOTE (manual): gate added by hand.',
    'localhost {',
    '\tbasic_auth {',
    ...credentialLines.map((l) => `\t\t${l}`),
    '\t}',
    '\treverse_proxy 127.0.0.1:3102',
    '}',
    ''
  ].join('\n');
}

describe('GET /api/setup/ingress-state', () => {
  let tmpDir;
  let server;

  before(async () => {
    tmpDir = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-ingress-endpoint-'));
    store._setBasePath(tmpDir);
    store.init();
    server = createServer();
    await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  });

  after(async () => {
    await new Promise((resolve) => server.close(resolve));
    store.close();
    fs.rmSync(tmpDir, { recursive: true, force: true });
  });

  /** Remove any Caddyfile so each case starts from a known state. */
  beforeEach(() => {
    const p = caddy.getCaddyfilePath();
    if (fs.existsSync(p)) fs.rmSync(p);
  });

  /** Write a Caddyfile at the live path. */
  function writeLive(content) {
    const p = caddy.getCaddyfilePath();
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, content);
  }

  it('reports "absent" with safeToWrite when no Caddyfile exists', async () => {
    const res = await get(server, '/api/setup/ingress-state');
    assert.equal(res.status, 200);
    assert.equal(res.data.state, 'absent');
    assert.equal(res.data.safeToWrite, true);
  });

  it('reports "adoptable" and names the single user the wizard would adopt', async () => {
    writeLive(handEdited([`jason ${BCRYPT_A}`]));
    const res = await get(server, '/api/setup/ingress-state');
    assert.equal(res.status, 200);
    assert.equal(res.data.state, 'adoptable');
    assert.equal(res.data.safeToWrite, false);
    assert.equal(res.data.user, 'jason');
    assert.equal(res.data.userCount, 1);
  });

  it('reports "ambiguous" with a count but no user, when several logins exist', async () => {
    writeLive(handEdited([`jason ${BCRYPT_A}`, `alex ${BCRYPT_B}`]));
    const res = await get(server, '/api/setup/ingress-state');
    assert.equal(res.data.state, 'ambiguous');
    assert.equal(res.data.safeToWrite, false);
    assert.equal(res.data.user, null, 'must not guess which credential is canonical');
    assert.equal(res.data.userCount, 2);
  });

  it('reports "ungated" for a hand-maintained file with no credential', async () => {
    writeLive('# my own proxy\nlocalhost {\n\treverse_proxy 127.0.0.1:3102\n}\n');
    const res = await get(server, '/api/setup/ingress-state');
    assert.equal(res.data.state, 'ungated');
    assert.equal(res.data.safeToWrite, false);
    assert.equal(res.data.userCount, 0);
  });

  it('never returns the credential hash, in any state', async () => {
    for (const content of [
      handEdited([`jason ${BCRYPT_A}`]),
      handEdited([`jason ${BCRYPT_A}`, `alex ${BCRYPT_B}`])
    ]) {
      writeLive(content);
      const res = await get(server, '/api/setup/ingress-state');
      assert.ok(!res.raw.includes(BCRYPT_A), 'response leaked a bcrypt hash');
      assert.ok(!res.raw.includes(BCRYPT_B), 'response leaked a bcrypt hash');
      assert.ok(!/\$2[aby]\$/.test(res.raw), 'response carried something bcrypt-shaped');
    }
  });

  it('does not enumerate account names when the file is ambiguous', async () => {
    writeLive(handEdited([`jason ${BCRYPT_A}`, `alex ${BCRYPT_B}`]));
    const res = await get(server, '/api/setup/ingress-state');
    // The count is enough for the UI to be specific; the names are not the
    // probe's to publish on an endpoint that runs before any gate exists.
    assert.ok(!res.raw.includes('alex'), 'response enumerated a second account name');
    assert.equal(res.data.users, undefined, 'raw user list must not cross the API boundary');
  });

  it('withholds the username once setup is complete, keeping state and count honest', async () => {
    writeLive(handEdited([`jason ${BCRYPT_A}`]));

    const during = await get(server, '/api/setup/ingress-state');
    assert.equal(during.data.user, 'jason', 'the wizard needs the name while it runs');

    const config = store.config.load();
    const orig = config.setupComplete;
    config.setupComplete = true;
    store.config.save(config);
    try {
      const after = await get(server, '/api/setup/ingress-state');
      assert.equal(after.data.user, null, 'an installed TangleClaw must not hand out an account name');
      assert.ok(!after.raw.includes('jason'), 'the name leaked by another field');
      assert.equal(after.data.state, 'adoptable', 'the state is still answered honestly');
      assert.equal(after.data.userCount, 1, 'the count is still answered honestly');
    } finally {
      config.setupComplete = orig;
      store.config.save(config);
    }
  });

  it('reports caddy as unavailable, with a reason, when it is not on PATH', async () => {
    // A `typeof … === 'boolean'` assertion passes whichever way detection goes,
    // so it proves nothing about the branch the wizard actually depends on:
    // "I cannot provision a gate here". Force the absent case.
    const emptyBin = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-nopath-'));
    const origPath = process.env.PATH;
    process.env.PATH = emptyBin;
    try {
      const res = await get(server, '/api/setup/ingress-state');
      assert.equal(res.status, 200, 'a missing caddy is a reportable state, not an error');
      assert.equal(res.data.caddy.available, false);
      assert.ok(res.data.caddy.error, 'the wizard needs a reason it can show');
    } finally {
      process.env.PATH = origPath;
      fs.rmSync(emptyBin, { recursive: true, force: true });
    }
  });

  it('still classifies the Caddyfile when caddy itself is missing', async () => {
    // Detection and classification are independent: an operator can have a
    // hand-rolled config from a caddy they later uninstalled, and the wizard
    // must not offer to overwrite it just because the binary is gone.
    writeLive(handEdited([`jason ${BCRYPT_A}`]));
    const emptyBin = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-nopath-'));
    const origPath = process.env.PATH;
    process.env.PATH = emptyBin;
    try {
      const res = await get(server, '/api/setup/ingress-state');
      assert.equal(res.data.caddy.available, false);
      assert.equal(res.data.state, 'adoptable');
      assert.equal(res.data.safeToWrite, false);
    } finally {
      process.env.PATH = origPath;
      fs.rmSync(emptyBin, { recursive: true, force: true });
    }
  });

  it('never writes or creates a Caddyfile as a side effect of probing', async () => {
    const p = caddy.getCaddyfilePath();
    assert.equal(fs.existsSync(p), false);
    await get(server, '/api/setup/ingress-state');
    assert.equal(fs.existsSync(p), false, 'the probe created a file');

    writeLive(handEdited([`jason ${BCRYPT_A}`]));
    const before = fs.readFileSync(p, 'utf8');
    await get(server, '/api/setup/ingress-state');
    assert.equal(fs.readFileSync(p, 'utf8'), before, 'the probe modified the file');
  });

  // ── The step-list decision the wizard consumes ──
  //
  // The wizard shows or hides the admin step on `plan.action` and never derives
  // it in the browser. These cases pin the decision to the route, so a change to
  // the classification cannot quietly flip whether a credential gets collected.

  it('tells the wizard to collect a credential when nothing a human maintains is at risk', async () => {
    const res = await get(server, '/api/setup/ingress-state');
    assert.equal(res.data.state, 'absent');
    assert.equal(res.data.plan.action, 'provision');
    assert.equal(res.data.plan.remedy, null);
  });

  it('tells the wizard to adopt, and names the user, when a single-login config exists', async () => {
    writeLive(handEdited([`jason ${BCRYPT_A}`]));
    const res = await get(server, '/api/setup/ingress-state');
    assert.equal(res.data.plan.action, 'adopt');
    assert.match(res.data.plan.reason, /jason/);
  });

  it('tells the wizard to refuse — with a reason and a remedy — when it must not write', async () => {
    for (const [content, label] of [
      [handEdited([`jason ${BCRYPT_A}`, `alex ${BCRYPT_B}`]), 'ambiguous'],
      ['# my own proxy\nlocalhost {\n\treverse_proxy 127.0.0.1:3102\n}\n', 'ungated']
    ]) {
      writeLive(content);
      const res = await get(server, '/api/setup/ingress-state');
      assert.equal(res.data.plan.action, 'refuse', label);
      assert.ok(res.data.plan.reason, `${label} must say why`);
      assert.ok(res.data.plan.remedy, `${label} must say what fixes it`);
    }
  });

  it('refuses even an adoptable config when caddy is not installed', async () => {
    // A gate nothing is running is not a gate. Adopting here would report the
    // install as protected while no process enforces the login.
    writeLive(handEdited([`jason ${BCRYPT_A}`]));
    const emptyBin = fs.mkdtempSync(path.join(os.tmpdir(), 'tc-nopath-'));
    const origPath = process.env.PATH;
    process.env.PATH = emptyBin;
    try {
      const res = await get(server, '/api/setup/ingress-state');
      assert.equal(res.data.state, 'adoptable', 'classification is unchanged');
      assert.equal(res.data.plan.action, 'refuse');
      assert.match(res.data.plan.reason, /not installed/);
    } finally {
      process.env.PATH = origPath;
      fs.rmSync(emptyBin, { recursive: true, force: true });
    }
  });

  it('never leaks the credential hash through the plan text', async () => {
    writeLive(handEdited([`jason ${BCRYPT_A}`]));
    const res = await get(server, '/api/setup/ingress-state');
    assert.equal(res.data.plan.action, 'adopt');
    assert.ok(!/\$2[aby]\$/.test(JSON.stringify(res.data.plan)), 'plan carried something bcrypt-shaped');
  });
});
