'use strict';

// AUTH-1 (#395) — Caddy reverse-proxy ingress. This module is the caddy-mode
// counterpart to lib/https-setup.js (which stays as the direct-mode TLS path):
// it detects the Caddy binary, generates the Caddyfile that fronts TangleClaw,
// and validates that Caddyfile before any launchd reload. It performs NO socket
// binding and has NO live effect on its own — generation + validation only.
// The cutover that actually puts Caddy in front is an explicit operator step
// (see scripts/ingress-cutover.js) gated on config.ingressMode === 'caddy'.

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFileSync } = require('node:child_process');
const store = require('./store');
const { createLogger } = require('./logger');

const log = createLogger('caddy');

const CADDY_TIMEOUT_MS = 10000;

// First line of every generated Caddyfile carries this marker PLUS a sha256 of
// the body, so the cutover can tell a pristine generated file (body still hashes
// to the stamped value → safe to overwrite) from an operator-edited one (#397
// bug 3 — never silently clobber a hand-edited Caddyfile + its password). A
// marker alone is insufficient: operators edit the body but keep the header line,
// so integrity must be verified, not just the prefix matched.
const GENERATED_MARKER = '# Generated by TangleClaw';
const _bodyHash = (body) => crypto.createHash('sha256').update(body).digest('hex');

/**
 * Path to the generated Caddyfile. Uses the store's base path so tests can
 * override it (mirrors https-setup.getCertsDir()).
 * @returns {string}
 */
function getCaddyfilePath() {
  return path.join(store._getBasePath(), 'Caddyfile');
}

/**
 * Path to the ttyd Unix domain socket used in caddy ingress mode. In caddy mode
 * ttyd binds this socket instead of TCP :3100 so it is unreachable except via
 * the proxy chain behind Caddy. Under the store base path so tests can override.
 * @returns {string}
 */
function getTtydSocketPath() {
  return path.join(store._getBasePath(), 'run', 'ttyd.sock');
}

/**
 * Resolve how TangleClaw should connect to its ttyd backend for the current
 * ingress mode. In 'caddy' mode ttyd is on a Unix socket; otherwise it is on
 * the configured TCP port (today's behavior). The returned shape feeds Node's
 * connection APIs directly: `{ socketPath }` for caddy mode, `{ host, port }`
 * for direct mode. `hostHeader` is the value to send as the HTTP/WS Host header.
 * @param {object} [config] - Loaded TangleClaw config.
 * @returns {{ socketPath?: string, host?: string, port?: number, hostHeader: string }}
 */
function ttydConnectTarget(config) {
  if (config && config.ingressMode === 'caddy') {
    return { socketPath: getTtydSocketPath(), hostHeader: 'localhost' };
  }
  const port = (config && config.ttydPort) || 3100;
  return { host: '127.0.0.1', port, hostHeader: `127.0.0.1:${port}` };
}

/**
 * Run a command and return its stdout. Wraps execFileSync with a short timeout
 * and argv-form args (no shell — no injection surface). Mirrors https-setup._run.
 * @param {string} cmd
 * @param {string[]} args
 * @returns {string} trimmed stdout
 */
function _run(cmd, args) {
  return execFileSync(cmd, args, {
    encoding: 'utf8',
    timeout: CADDY_TIMEOUT_MS,
    stdio: ['ignore', 'pipe', 'pipe']
  }).toString().trim();
}

/**
 * Detect whether the Caddy binary is installed and return its metadata.
 * @returns {{ available: boolean, version: string|null, error: string|null }}
 */
function detectCaddy() {
  try {
    const out = _run('caddy', ['version']);
    // `caddy version` prints e.g. "v2.8.4 h1:..." — take the first token.
    const version = out.split(/\s+/)[0] || null;
    return { available: true, version, error: null };
  } catch (err) {
    return {
      available: false,
      version: null,
      error: err.code === 'ENOENT' ? 'caddy not found on PATH' : err.message
    };
  }
}

/**
 * Build the Caddyfile text that fronts TangleClaw in caddy ingress mode.
 *
 * Caddy terminates TLS and reverse-proxies every surface to TC's localhost
 * HTTP listener; TC continues to internally proxy ttyd and the OpenClaw gateway,
 * so the Caddyfile only needs the single TC upstream. `reverse_proxy` handles
 * WebSocket Upgrade transparently, so the three WS routes need no extra config.
 *
 * The local site reuses the operator's existing mkcert cert (keeps the
 * already-trusted CA — no re-trust). When `publicDomain` is set, a second site
 * block with NO tls directive is emitted so Caddy auto-provisions a real
 * Let's Encrypt (ACME) certificate for it.
 *
 * @param {object} options
 * @param {number} options.serverPort - TC's localhost HTTP port (the upstream).
 * @param {string} options.certPath - mkcert cert.pem for the local site.
 * @param {string} options.keyPath - mkcert key.pem for the local site.
 * @param {string} [options.localSite='localhost'] - Local site hostname (no port —
 *   the port comes from the global `https_port` directive).
 * @param {number} [options.httpsPort=8443] - Global HTTPS listen port. Non-privileged
 *   by default so Caddy runs as a user LaunchAgent without sudo.
 * @param {number} [options.httpPort=8080] - Global HTTP listen port (redirects + ACME challenge).
 * @param {string|null} [options.publicDomain=null] - Public domain for the ACME block.
 * @returns {string} Caddyfile content.
 */
function buildCaddyfileContent(options = {}) {
  const { serverPort, certPath, keyPath } = options;
  const localSite = options.localSite || 'localhost';
  const httpsPort = options.httpsPort || 8443;
  const httpPort = options.httpPort || 8080;
  const publicDomain = options.publicDomain || null;

  if (!serverPort || typeof serverPort !== 'number') {
    throw new Error('buildCaddyfileContent: serverPort (number) is required');
  }
  if (!certPath || !keyPath) {
    throw new Error('buildCaddyfileContent: certPath and keyPath are required');
  }

  const upstream = `127.0.0.1:${serverPort}`;
  const lines = [];

  // Global options. `https_port`/`http_port` keep Caddy off privileged ports so
  // it runs as a user LaunchAgent with no sudo (AUTH-1 default 8443/8080).
  // `admin off` drops Caddy's localhost:2019 admin API — we manage the process
  // via launchd, not the admin API, so the surface is dead weight.
  lines.push('{');
  lines.push(`\thttps_port ${httpsPort}`);
  lines.push(`\thttp_port ${httpPort}`);
  lines.push('\tadmin off');
  lines.push('}');
  lines.push('');

  // Local site — reuse the mkcert cert so local HTTPS is unchanged for the operator.
  lines.push(`${localSite} {`);
  lines.push(`\ttls ${certPath} ${keyPath}`);
  lines.push(`\treverse_proxy ${upstream}`);
  lines.push('}');

  // Public site — no tls directive ⇒ Caddy auto-provisions Let's Encrypt (ACME).
  if (publicDomain) {
    lines.push('');
    lines.push(`${publicDomain} {`);
    lines.push(`\treverse_proxy ${upstream}`);
    lines.push('}');
  }

  // Integrity-stamped header: the first line carries a sha256 of the body so the
  // cutover can verify the file is unmodified before overwriting (#397 bug 3).
  const body = lines.join('\n') + '\n';
  const header = `${GENERATED_MARKER} (AUTH-1 / lib/caddy.js) sha256:${_bodyHash(body)} — do not hand-edit; regenerated on ingress cutover.\n`;
  return header + body;
}

/**
 * Generate and write the Caddyfile to disk.
 * @param {object} options - Passed to buildCaddyfileContent, plus:
 * @param {string} [options.caddyfilePath] - Destination (default: getCaddyfilePath()).
 * @returns {{ caddyfilePath: string, content: string }}
 */
function writeCaddyfile(options = {}) {
  const caddyfilePath = options.caddyfilePath || getCaddyfilePath();
  const content = buildCaddyfileContent(options);

  const dir = path.dirname(caddyfilePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  }
  fs.writeFileSync(caddyfilePath, content, { mode: 0o600 });
  log.info('Wrote Caddyfile', { caddyfilePath, publicDomain: options.publicDomain || null });

  return { caddyfilePath, content };
}

/**
 * Validate a Caddyfile via `caddy validate` (catches a bad config before any
 * launchd reload — fail-closed cutover).
 * @param {string} [caddyfilePath] - Path to validate (default: getCaddyfilePath()).
 * @returns {{ ok: boolean, error: string|null }}
 */
function validateCaddyfile(caddyfilePath) {
  const target = caddyfilePath || getCaddyfilePath();
  if (!fs.existsSync(target)) {
    return { ok: false, error: `Caddyfile not found: ${target}` };
  }
  const detection = detectCaddy();
  if (!detection.available) {
    return { ok: false, error: `caddy is not available: ${detection.error || 'unknown'}` };
  }
  try {
    _run('caddy', ['validate', '--adapter', 'caddyfile', '--config', target]);
    return { ok: true, error: null };
  } catch (err) {
    // execFileSync surfaces validation failures via stderr in err.message/stderr.
    const detail = (err.stderr && err.stderr.toString().trim()) || err.message;
    return { ok: false, error: detail };
  }
}

/**
 * Whether a Caddyfile's content is a pristine, unmodified TangleClaw-generated
 * file — used by the cutover to refuse silently clobbering manual edits (#397
 * bug 3). Verifies the sha256 stamped in the header line against the live body,
 * so a file whose body was hand-edited (even if the header line was kept) reads
 * as NOT generated. A header with no stamp (legacy generated file or a foreign
 * file) also reads as not-generated — the safe default is to protect it.
 * @param {string} content - Caddyfile text.
 * @returns {boolean} true only if integrity-verified generated (safe to overwrite).
 */
function isGeneratedCaddyfile(content) {
  if (typeof content !== 'string') return false;
  const nl = content.indexOf('\n');
  if (nl === -1) return false;
  const firstLine = content.slice(0, nl);
  const body = content.slice(nl + 1);
  const m = firstLine.match(/^#\s*Generated by TangleClaw\b.*\bsha256:([0-9a-f]{64})\b/);
  if (!m) return false;
  return _bodyHash(body) === m[1];
}

/**
 * Directory where Caddy reads its TLS material in caddy ingress mode. The
 * launchd Caddy binary has no Full Disk Access, so it cannot read a cert under a
 * TCC-protected location (e.g. the operator's mkcert cert under ~/Documents);
 * certs are staged here, under the (non-TCC) store base path, before use (#397
 * bug 1). Coincides with https-setup.getCertsDir() by design — one cert location
 * — and stageCert() no-ops when the source already lives here. Test-overridable
 * via the store base path.
 * @returns {string}
 */
function getStagedCertsDir() {
  return path.join(store._getBasePath(), 'certs');
}

/**
 * Stage (copy) a cert + key into the non-TCC staging dir so the launchd Caddy
 * binary can read them, and return the staged paths. Overwrites on every call so
 * cert rotation propagates; the key is written 0600, the cert 0644. When a source
 * file already IS the staged file (the generate path writes straight into the
 * staging dir), the copy is skipped — same bytes, no self-copy error.
 * @param {string} certPath - Source cert.pem (may be under a TCC-protected dir).
 * @param {string} keyPath - Source key.pem.
 * @param {string} [stagingDir] - Destination dir (default: getStagedCertsDir()).
 * @returns {{ certPath: string, keyPath: string }} Staged paths to reference in the Caddyfile.
 */
function stageCert(certPath, keyPath, stagingDir) {
  if (!certPath || !keyPath) {
    throw new Error('stageCert: certPath and keyPath are required');
  }
  const dir = stagingDir || getStagedCertsDir();
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  }
  const staged = { certPath: path.join(dir, 'cert.pem'), keyPath: path.join(dir, 'key.pem') };
  const pairs = [[certPath, staged.certPath, 0o644], [keyPath, staged.keyPath, 0o600]];
  for (const [src, dest, mode] of pairs) {
    // Skip the copy when source and destination resolve to the same file (the
    // generate path already wrote into the staging dir). realpathSync only on an
    // existing dest; otherwise the paths differ and we copy.
    const sameFile = fs.existsSync(dest) && fs.realpathSync(src) === fs.realpathSync(dest);
    if (!sameFile) fs.copyFileSync(src, dest);
    fs.chmodSync(dest, mode);
  }
  log.info('Staged cert for caddy', { stagingDir: dir });
  return staged;
}

module.exports = {
  detectCaddy,
  buildCaddyfileContent,
  writeCaddyfile,
  validateCaddyfile,
  getCaddyfilePath,
  getTtydSocketPath,
  ttydConnectTarget,
  isGeneratedCaddyfile,
  getStagedCertsDir,
  stageCert,
  GENERATED_MARKER
};
