'use strict';

// AUTH-1 (#395) — Caddy reverse-proxy ingress. This module is the caddy-mode
// counterpart to lib/https-setup.js (which stays as the direct-mode TLS path):
// it detects the Caddy binary, generates the Caddyfile that fronts TangleClaw,
// and validates that Caddyfile before any launchd reload. It performs NO socket
// binding and has NO live effect on its own — generation + validation only.
// The cutover that actually puts Caddy in front is an explicit operator step
// (see scripts/ingress-cutover.js) gated on config.ingressMode === 'caddy'.

const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const { execFileSync } = require('node:child_process');
const store = require('./store');
const { createLogger } = require('./logger');

const log = createLogger('caddy');

const CADDY_TIMEOUT_MS = 10000;

// First line of every generated Caddyfile carries this marker PLUS a sha256 of
// the body, so the cutover can tell a pristine generated file (body still hashes
// to the stamped value → safe to overwrite) from an operator-edited one (#397
// bug 3 — never silently clobber a hand-edited Caddyfile + its password). A
// marker alone is insufficient: operators edit the body but keep the header line,
// so integrity must be verified, not just the prefix matched.
const GENERATED_MARKER = '# Generated by TangleClaw';
const _bodyHash = (body) => crypto.createHash('sha256').update(body).digest('hex');

/**
 * Build the integrity-stamped header line (no trailing newline) for a Caddyfile
 * body. Single source of truth for the header format so the generator and the
 * break-glass re-stamp can't drift (a drifted format would make isGeneratedCaddyfile
 * mis-classify a freshly-generated file as hand-edited).
 * @param {string} body - The Caddyfile body the header vouches for.
 * @returns {string} Header line without trailing newline.
 */
function _makeHeaderLine(body) {
  return `${GENERATED_MARKER} (lib/caddy.js) sha256:${_bodyHash(body)} — do not hand-edit; regenerated on ingress cutover.`;
}

/**
 * Path to the generated Caddyfile. Uses the store's base path so tests can
 * override it (mirrors https-setup.getCertsDir()).
 * @returns {string}
 */
function getCaddyfilePath() {
  return path.join(store._getBasePath(), 'Caddyfile');
}

/**
 * Path to the ttyd Unix domain socket used in caddy ingress mode. In caddy mode
 * ttyd binds this socket instead of TCP :3100 so it is unreachable except via
 * the proxy chain behind Caddy. Under the store base path so tests can override.
 * @returns {string}
 */
function getTtydSocketPath() {
  return path.join(store._getBasePath(), 'run', 'ttyd.sock');
}

/**
 * Resolve how TangleClaw should connect to its ttyd backend for the current
 * ingress mode. In 'caddy' mode ttyd is on a Unix socket; otherwise it is on
 * the configured TCP port (today's behavior). The returned shape feeds Node's
 * connection APIs directly: `{ socketPath }` for caddy mode, `{ host, port }`
 * for direct mode. `hostHeader` is the value to send as the HTTP/WS Host header.
 * @param {object} [config] - Loaded TangleClaw config.
 * @returns {{ socketPath?: string, host?: string, port?: number, hostHeader: string }}
 */
function ttydConnectTarget(config) {
  if (config && config.ingressMode === 'caddy') {
    return { socketPath: getTtydSocketPath(), hostHeader: 'localhost' };
  }
  const port = (config && config.ttydPort) || 3100;
  return { host: '127.0.0.1', port, hostHeader: `127.0.0.1:${port}` };
}

/**
 * Run a command and return its stdout. Wraps execFileSync with a short timeout
 * and argv-form args (no shell — no injection surface). Mirrors https-setup._run.
 * @param {string} cmd
 * @param {string[]} args
 * @returns {string} trimmed stdout
 */
function _run(cmd, args) {
  return execFileSync(cmd, args, {
    encoding: 'utf8',
    timeout: CADDY_TIMEOUT_MS,
    stdio: ['ignore', 'pipe', 'pipe']
  }).toString().trim();
}

/**
 * Detect whether the Caddy binary is installed and return its metadata.
 * @returns {{ available: boolean, version: string|null, error: string|null }}
 */
function detectCaddy() {
  try {
    const out = _run('caddy', ['version']);
    // `caddy version` prints e.g. "v2.8.4 h1:..." — take the first token.
    const version = out.split(/\s+/)[0] || null;
    return { available: true, version, error: null };
  } catch (err) {
    return {
      available: false,
      version: null,
      error: err.code === 'ENOENT' ? 'caddy not found on PATH' : err.message
    };
  }
}

// Named matcher for the auth-bypass: every request EXCEPT the health endpoint is
// gated. `/api/health` stays open so the ingress cutover's health probe — and any
// launchd/liveness check — reaches TC without credentials (the probe has none).
const AUTH_BYPASS_PATH = '/api/health';

/**
 * Append a Caddy site block to `lines`. Emits an optional `tls` directive and an
 * optional `basic_auth` gate, then the `reverse_proxy` upstream. With no `auth`
 * the block is byte-for-byte what AUTH-1 emitted, so an ungated Caddyfile is
 * unchanged (and its integrity hash is stable). A gated block additionally
 * forwards the authenticated username via `header_up X-Auth-User` (AUTH-3).
 * @param {string[]} lines - Accumulator, mutated in place.
 * @param {string} siteHeader - Site address (hostname, no port — the port comes
 *   from the global `https_port` directive).
 * @param {object} block
 * @param {{certPath:string,keyPath:string}} [block.tls] - TLS cert pair; omit for
 *   an ACME site (no tls directive ⇒ Caddy auto-provisions).
 * @param {string} block.upstream - reverse_proxy target (host:port).
 * @param {{user:string,hash:string}|null} [block.auth] - basic_auth credential
 *   (bcrypt hash), or null/undefined for an open site.
 */
function _pushSiteBlock(lines, siteHeader, block) {
  lines.push(`${siteHeader} {`);
  if (block.tls) {
    lines.push(`\ttls ${block.tls.certPath} ${block.tls.keyPath}`);
  }
  if (block.auth) {
    // Gate everything except the health endpoint. `basic_auth` runs before
    // `reverse_proxy` in Caddy's directive order, so unauthenticated requests to
    // any other path are challenged before they reach the upstream.
    lines.push(`\t@protected not path ${AUTH_BYPASS_PATH}`);
    lines.push('\tbasic_auth @protected {');
    lines.push(`\t\t${block.auth.user} ${block.auth.hash}`);
    lines.push('\t}');
    // AUTH-3: forward the authenticated username to TC. `{http.auth.user.id}` is
    // populated by `basic_auth` after a successful challenge; `header_up` uses set
    // semantics, so it OVERWRITES any client-supplied X-Auth-User — TC therefore
    // sees only Caddy's value and a forged header can't reach the app through the
    // proxy. Only emitted on a gated site (no auth ⇒ no identity to forward).
    lines.push(`\treverse_proxy ${block.upstream} {`);
    lines.push('\t\theader_up X-Auth-User {http.auth.user.id}');
    lines.push('\t}');
  } else {
    lines.push(`\treverse_proxy ${block.upstream}`);
  }
  lines.push('}');
}

/**
 * Build the Caddyfile text that fronts TangleClaw in caddy ingress mode.
 *
 * Caddy terminates TLS and reverse-proxies every surface to TC's localhost
 * HTTP listener; TC continues to internally proxy ttyd and the OpenClaw gateway,
 * so the Caddyfile only needs the single TC upstream. `reverse_proxy` handles
 * WebSocket Upgrade transparently, so the three WS routes need no extra config.
 *
 * The local site reuses the operator's existing mkcert cert (keeps the
 * already-trusted CA — no re-trust). When `publicDomain` is set, a second site
 * block with NO tls directive is emitted so Caddy auto-provisions a real
 * Let's Encrypt (ACME) certificate for it.
 *
 * When `basicAuthUser` + `basicAuthHash` are supplied (AUTH-2), every site block
 * gains a `basic_auth` gate over all paths except `/api/health`. The gate is the
 * stored bcrypt hash (never a plaintext password); the wizard hashes via
 * `caddy hash-password` and persists only the hash. Both are required together —
 * a half-set pair throws, so a misconfigured gate can never silently produce an
 * UNGATED ingress on a reachable box.
 *
 * @param {object} options
 * @param {number} options.serverPort - TC's localhost HTTP port (the upstream).
 * @param {string} options.certPath - mkcert cert.pem for the local site.
 * @param {string} options.keyPath - mkcert key.pem for the local site.
 * @param {string} [options.localSite='localhost'] - Local site hostname (no port —
 *   the port comes from the global `https_port` directive).
 * @param {number} [options.httpsPort=8443] - Global HTTPS listen port. Non-privileged
 *   by default so Caddy runs as a user LaunchAgent without sudo.
 * @param {number} [options.httpPort=8080] - Global HTTP listen port (redirects + ACME challenge).
 * @param {string|null} [options.publicDomain=null] - Public domain for the ACME block.
 * @param {string|null} [options.basicAuthUser=null] - basic_auth username (AUTH-2). Requires basicAuthHash.
 * @param {string|null} [options.basicAuthHash=null] - basic_auth bcrypt hash (AUTH-2). Requires basicAuthUser.
 * @param {boolean} [options.remoteHttpCatchAll=false] - Emit a gated plain-HTTP
 *   catch-all site (`http:// { ... }`) for WireGuard/Tailscale remote access
 *   (#397 codification of the 2026-06-23 hand-edit). Requires basic_auth — an
 *   ungated plain-HTTP catch-all would be an open door, so it throws. Also adds
 *   `auto_https disable_redirects` so Caddy serves the HTTP site instead of
 *   308-redirecting it to HTTPS before auth runs.
 * @returns {string} Caddyfile content.
 */
function buildCaddyfileContent(options = {}) {
  const { serverPort, certPath, keyPath } = options;
  const localSite = options.localSite || 'localhost';
  const httpsPort = options.httpsPort || 8443;
  const httpPort = options.httpPort || 8080;
  const publicDomain = options.publicDomain || null;
  const basicAuthUser = options.basicAuthUser || null;
  const basicAuthHash = options.basicAuthHash || null;
  const remoteHttpCatchAll = options.remoteHttpCatchAll === true;

  if (!serverPort || typeof serverPort !== 'number') {
    throw new Error('buildCaddyfileContent: serverPort (number) is required');
  }
  if (!certPath || !keyPath) {
    throw new Error('buildCaddyfileContent: certPath and keyPath are required');
  }
  // basic_auth needs BOTH a username and a hash — reject a half-set pair so a
  // misconfigured gate can't silently emit an UNGATED ingress (fail closed).
  if (Boolean(basicAuthUser) !== Boolean(basicAuthHash)) {
    throw new Error('buildCaddyfileContent: basicAuthUser and basicAuthHash must be set together');
  }
  // A plain-HTTP catch-all without a gate is an open ingress on every interface —
  // never emit it (fail closed, same posture as the half-set-pair guard above).
  if (remoteHttpCatchAll && !(basicAuthUser && basicAuthHash)) {
    throw new Error('buildCaddyfileContent: remoteHttpCatchAll requires basicAuthUser and basicAuthHash (an ungated plain-HTTP catch-all is an open door)');
  }

  const upstream = `127.0.0.1:${serverPort}`;
  const auth = basicAuthUser && basicAuthHash ? { user: basicAuthUser, hash: basicAuthHash } : null;
  const lines = [];

  // Global options. `https_port`/`http_port` keep Caddy off privileged ports so
  // it runs as a user LaunchAgent with no sudo (AUTH-1 default 8443/8080).
  // `admin off` drops Caddy's localhost:2019 admin API — we manage the process
  // via launchd, not the admin API, so the surface is dead weight.
  lines.push('{');
  lines.push(`\thttps_port ${httpsPort}`);
  lines.push(`\thttp_port ${httpPort}`);
  lines.push('\tadmin off');
  if (remoteHttpCatchAll) {
    // Without this Caddy 308-redirects the plain-HTTP catch-all to HTTPS before
    // basic_auth runs, breaking the WireGuard-transport remote path.
    lines.push('\tauto_https disable_redirects');
  }
  lines.push('}');
  lines.push('');

  // Local site — reuse the mkcert cert so local HTTPS is unchanged for the operator.
  _pushSiteBlock(lines, localSite, { tls: { certPath, keyPath }, upstream, auth });

  // Public site — no tls directive ⇒ Caddy auto-provisions Let's Encrypt (ACME).
  if (publicDomain) {
    lines.push('');
    _pushSiteBlock(lines, publicDomain, { upstream, auth });
  }

  // Remote plain-HTTP catch-all — Basic-Auth-gated (enforced above). The tailnet
  // (WireGuard) encrypts the transport, so credentials are protected in flight
  // (#397 codification of the 2026-06-23 hand-edit).
  if (remoteHttpCatchAll) {
    lines.push('');
    _pushSiteBlock(lines, 'http://', { upstream, auth });
  }

  // Integrity-stamped header: the first line carries a sha256 of the body so the
  // cutover can verify the file is unmodified before overwriting (#397 bug 3).
  const body = lines.join('\n') + '\n';
  return `${_makeHeaderLine(body)}\n${body}`;
}

/**
 * Generate and write the Caddyfile to disk.
 * @param {object} options - Passed to buildCaddyfileContent, plus:
 * @param {string} [options.caddyfilePath] - Destination (default: getCaddyfilePath()).
 * @returns {{ caddyfilePath: string, content: string }}
 */
function writeCaddyfile(options = {}) {
  const caddyfilePath = options.caddyfilePath || getCaddyfilePath();
  const content = buildCaddyfileContent(options);

  const dir = path.dirname(caddyfilePath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  }
  fs.writeFileSync(caddyfilePath, content, { mode: 0o600 });
  log.info('Wrote Caddyfile', { caddyfilePath, publicDomain: options.publicDomain || null });

  return { caddyfilePath, content };
}

/**
 * Validate a Caddyfile via `caddy validate` (catches a bad config before any
 * launchd reload — fail-closed cutover).
 * @param {string} [caddyfilePath] - Path to validate (default: getCaddyfilePath()).
 * @returns {{ ok: boolean, error: string|null }}
 */
function validateCaddyfile(caddyfilePath) {
  const target = caddyfilePath || getCaddyfilePath();
  if (!fs.existsSync(target)) {
    return { ok: false, error: `Caddyfile not found: ${target}` };
  }
  const detection = detectCaddy();
  if (!detection.available) {
    return { ok: false, error: `caddy is not available: ${detection.error || 'unknown'}` };
  }
  try {
    _run('caddy', ['validate', '--adapter', 'caddyfile', '--config', target]);
    return { ok: true, error: null };
  } catch (err) {
    // execFileSync surfaces validation failures via stderr in err.message/stderr.
    const detail = (err.stderr && err.stderr.toString().trim()) || err.message;
    return { ok: false, error: detail };
  }
}

/**
 * Whether a Caddyfile's content is a pristine, unmodified TangleClaw-generated
 * file — used by the cutover to refuse silently clobbering manual edits (#397
 * bug 3). Verifies the sha256 stamped in the header line against the live body,
 * so a file whose body was hand-edited (even if the header line was kept) reads
 * as NOT generated. A header with no stamp (legacy generated file or a foreign
 * file) also reads as not-generated — the safe default is to protect it.
 * @param {string} content - Caddyfile text.
 * @returns {boolean} true only if integrity-verified generated (safe to overwrite).
 */
function isGeneratedCaddyfile(content) {
  if (typeof content !== 'string') return false;
  const nl = content.indexOf('\n');
  if (nl === -1) return false;
  const firstLine = content.slice(0, nl);
  const body = content.slice(nl + 1);
  const m = firstLine.match(/^#\s*Generated by TangleClaw\b.*\bsha256:([0-9a-f]{64})\b/);
  if (!m) return false;
  return _bodyHash(body) === m[1];
}

/**
 * Directory where Caddy reads its TLS material in caddy ingress mode. The
 * launchd Caddy binary has no Full Disk Access, so it cannot read a cert under a
 * TCC-protected location (e.g. the operator's mkcert cert under ~/Documents);
 * certs are staged here, under the (non-TCC) store base path, before use (#397
 * bug 1). Coincides with https-setup.getCertsDir() by design — one cert location
 * — and stageCert() no-ops when the source already lives here. Test-overridable
 * via the store base path.
 * @returns {string}
 */
function getStagedCertsDir() {
  return path.join(store._getBasePath(), 'certs');
}

/**
 * Stage (copy) a cert + key into the non-TCC staging dir so the launchd Caddy
 * binary can read them, and return the staged paths. Overwrites on every call so
 * cert rotation propagates; the key is written 0600, the cert 0644. When a source
 * file already IS the staged file (the generate path writes straight into the
 * staging dir), the copy is skipped — same bytes, no self-copy error.
 * @param {string} certPath - Source cert.pem (may be under a TCC-protected dir).
 * @param {string} keyPath - Source key.pem.
 * @param {string} [stagingDir] - Destination dir (default: getStagedCertsDir()).
 * @returns {{ certPath: string, keyPath: string }} Staged paths to reference in the Caddyfile.
 */
function stageCert(certPath, keyPath, stagingDir) {
  if (!certPath || !keyPath) {
    throw new Error('stageCert: certPath and keyPath are required');
  }
  const dir = stagingDir || getStagedCertsDir();
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true, mode: 0o700 });
  }
  const staged = { certPath: path.join(dir, 'cert.pem'), keyPath: path.join(dir, 'key.pem') };
  const pairs = [[certPath, staged.certPath, 0o644], [keyPath, staged.keyPath, 0o600]];
  for (const [src, dest, mode] of pairs) {
    // Skip the copy when source and destination resolve to the same file (the
    // generate path already wrote into the staging dir). realpathSync only on an
    // existing dest; otherwise the paths differ and we copy.
    const sameFile = fs.existsSync(dest) && fs.realpathSync(src) === fs.realpathSync(dest);
    if (!sameFile) fs.copyFileSync(src, dest);
    fs.chmodSync(dest, mode);
  }
  log.info('Staged cert for caddy', { stagingDir: dir });
  return staged;
}

// ── AUTH-2: first-run admin credential (basic_auth) ──
// The wizard collects a plaintext password; the server validates it against these
// zero-dep rules and hashes it via `caddy hash-password`. Caddy's basic_auth
// directive reads bcrypt, so we shell out to the already-required caddy binary
// rather than add a hashing dependency (zero-dep policy).

const ADMIN_PASSWORD_MIN_LENGTH = 12;

// Small bundled denylist of the most common weak passwords (lowercased, all ≥
// ADMIN_PASSWORD_MIN_LENGTH so they'd otherwise pass the length gate). Zero-dep —
// a full breach corpus is out of scope; this just blocks the obvious footguns so
// the forced first-run admin can't be "passwordpassword". Checked case-insensitively.
const WEAK_PASSWORD_DENYLIST = new Set([
  'passwordpassword', 'password1234', 'password12345', 'password123456',
  'administrator', 'changeme1234', 'changeme12345', 'letmein12345',
  'qwertyuiop12', 'qwerty123456', '123456789012', '1234567890123',
  'tangleclaw12', 'tangleclaw123', 'iloveyou1234', 'welcome12345'
]);

// bcrypt hash shape — `caddy hash-password` (bcrypt) emits `$2a$NN$…` (60 chars).
// Exported as the single source of truth; server.js's PATCH /api/config
// validation consumes it (no duplicated literal that could drift).
const BCRYPT_HASH_RE = /^\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53}$/;

/**
 * Validate a proposed first-run admin password against the zero-dep rules:
 * present, no control chars, min length, not a known-weak password, and not
 * derivable from the username. Returns a structured result so the API can surface
 * the exact reason to the wizard.
 * @param {string} password - Plaintext candidate.
 * @param {string} [username] - The admin username (rejected if the password
 *   contains it, case-insensitive — stops "adminadmin12" style credentials).
 * @returns {{ ok: boolean, error: string|null }}
 */
function validateAdminPassword(password, username) {
  if (typeof password !== 'string' || password.length === 0) {
    return { ok: false, error: 'Password is required' };
  }
  // Control chars (incl. newline) would be truncated when piped to
  // `caddy hash-password` on stdin — reject so what we hash is what was typed.
  if (/[\u0000-\u001f\u007f]/.test(password)) {
    return { ok: false, error: 'Password must not contain control characters' };
  }
  if (password.length < ADMIN_PASSWORD_MIN_LENGTH) {
    return { ok: false, error: `Password must be at least ${ADMIN_PASSWORD_MIN_LENGTH} characters` };
  }
  if (WEAK_PASSWORD_DENYLIST.has(password.toLowerCase())) {
    return { ok: false, error: 'Password is too common — choose a less guessable one' };
  }
  const u = (typeof username === 'string' ? username.trim() : '').toLowerCase();
  if (u && password.toLowerCase().includes(u)) {
    return { ok: false, error: 'Password must not contain the username' };
  }
  return { ok: true, error: null };
}

/**
 * Hash a plaintext password into a bcrypt hash via `caddy hash-password`. The
 * plaintext is fed on STDIN (never argv) so it can't leak via `ps`. Throws if
 * caddy is unavailable or returns a non-bcrypt value, so a failed hash can never
 * be persisted as a credential.
 * @param {string} plaintext - Password to hash (caller must rule-validate first).
 * @returns {string} bcrypt hash (`$2a$NN$…`, 60 chars).
 */
function hashPassword(plaintext) {
  if (typeof plaintext !== 'string' || plaintext.length === 0) {
    throw new Error('hashPassword: a non-empty plaintext password is required');
  }
  let out;
  try {
    // With --plaintext omitted, `caddy hash-password` reads one line from stdin;
    // the trailing newline terminates the read.
    out = execFileSync('caddy', ['hash-password', '--algorithm', 'bcrypt'], {
      input: `${plaintext}\n`,
      encoding: 'utf8',
      timeout: CADDY_TIMEOUT_MS,
      stdio: ['pipe', 'pipe', 'pipe']
    }).toString().trim();
  } catch (err) {
    const detail = (err.stderr && err.stderr.toString().trim()) || err.message;
    throw new Error(`caddy hash-password failed: ${detail}`);
  }
  if (!BCRYPT_HASH_RE.test(out)) {
    throw new Error('caddy hash-password did not return a bcrypt hash');
  }
  return out;
}

// A basic_auth credential line inside any Caddyfile: leading indent, a username,
// whitespace, then a bcrypt hash to end-of-line. The very specific bcrypt shape
// (BCRYPT_HASH_RE's body) is what makes this safe to match line-by-line WITHOUT
// parsing block structure — so it works on the generated inline
// `basic_auth @protected { user hash }` AND a hand-edited snippet
// (`(tcauth) { basic_auth { user hash } }`) alike. Captures:
//   1 indent · 2 username · 3 separator · 4 bcrypt hash · 5 trailing space
const CREDENTIAL_LINE_RE = /^([ \t]*)(\S+)([ \t]+)(\$2[aby]\$\d{2}\$[./A-Za-z0-9]{53})([ \t]*)$/gm;

/**
 * List the distinct basic_auth usernames present in a Caddyfile, in first-seen
 * order. Used by scripts/reset-admin.js to resolve which credential to reset (and
 * to validate the new password against the right username) before prompting.
 * @param {string} content - Caddyfile text.
 * @returns {string[]} Distinct usernames (empty when the file has no gate).
 */
function listBasicAuthUsers(content) {
  if (typeof content !== 'string') return [];
  return [...new Set([...content.matchAll(CREDENTIAL_LINE_RE)].map((m) => m[2]))];
}

/**
 * Extract the basic_auth credential from an existing Caddyfile.
 *
 * The credential-durability primitive (#397 / 2026-07-03 lockout): the live
 * credential must be recoverable FROM the file so it can be adopted into the
 * canonical config, instead of living only inside a file that any regeneration
 * path can clobber. Works on both the generated inline gate and the hand-edited
 * `(tcauth)` snippet shape (same line-level match as replaceBasicAuthCredential).
 *
 * Returns null when the file carries no credential OR more than one distinct
 * user — adoption must never guess which credential is canonical.
 *
 * @param {string} content - Caddyfile text.
 * @returns {{ user: string, hash: string }|null}
 */
function extractBasicAuthCredential(content) {
  if (typeof content !== 'string') return null;
  const matches = [...content.matchAll(CREDENTIAL_LINE_RE)];
  if (matches.length === 0) return null;
  const users = [...new Set(matches.map((m) => m[2]))];
  if (users.length !== 1) return null; // ambiguous — refuse to guess
  return { user: users[0], hash: matches[0][4] };
}

/**
 * Whether a Caddyfile carries a plain-HTTP catch-all site (`http:// { ... }`) —
 * the hand-added remote-access shape (Tailscale carries the WireGuard-encrypted
 * transport, so Basic Auth over plain HTTP is acceptable there). Detected so
 * adoption can persist the shape into config and regeneration can preserve it.
 * @param {string} content - Caddyfile text.
 * @returns {boolean}
 */
function hasRemoteHttpCatchAll(content) {
  if (typeof content !== 'string') return false;
  return /^http:\/\/[ \t]*\{/m.test(content);
}

/**
 * Adopt the live Caddyfile's basic_auth credential (and remote-HTTP shape) into
 * the canonical config — READ-ONLY on the Caddyfile, writes config only.
 *
 * Root-cause hardening for the 2026-07-03 lockout (#397): the working credential
 * existed ONLY inside the hand-edited Caddyfile, so (a) any regeneration lost it
 * and (b) with empty config, a cutover would have emitted an UNGATED ingress.
 * After adoption the config is the durable source of truth and every
 * regeneration path (cutover, reset-admin) re-emits the same hash byte-for-byte.
 *
 * No-ops (returns `{ adopted: false, reason }`) when: not in caddy ingress mode,
 * config already carries a credential (never overwritten), the Caddyfile is
 * missing/unreadable, or the file's credentials are absent/ambiguous.
 * Non-throwing by design — boot must never die on an ingress config wrinkle.
 *
 * @param {object} [opts]
 * @param {boolean} [opts.requireCaddyMode=true] - Skip the ingressMode gate.
 *   The cutover TO caddy runs while the config still says 'direct', so it
 *   passes false; the boot-time caller keeps the default.
 * @returns {{ adopted: boolean, user?: string, remoteHttp?: boolean, reason?: string }}
 */
function adoptCredentialIntoConfig(opts = {}) {
  const requireCaddyMode = opts.requireCaddyMode !== false;
  try {
    const config = store.config.load();
    if (requireCaddyMode && config.ingressMode !== 'caddy') return { adopted: false, reason: 'not-caddy-mode' };
    if (config.basicAuthUser || config.basicAuthHash) return { adopted: false, reason: 'config-already-has-credential' };

    const caddyfilePath = getCaddyfilePath();
    if (!fs.existsSync(caddyfilePath)) return { adopted: false, reason: 'no-caddyfile' };
    const content = fs.readFileSync(caddyfilePath, 'utf8');

    const cred = extractBasicAuthCredential(content);
    if (!cred) return { adopted: false, reason: 'no-unambiguous-credential' };

    config.authEnabled = true;
    config.basicAuthUser = cred.user;
    config.basicAuthHash = cred.hash;
    const remoteHttp = hasRemoteHttpCatchAll(content);
    if (remoteHttp) config.caddyRemoteHttp = true;
    store.config.save(config);
    log.info('Adopted basic_auth credential from live Caddyfile into config (#397 durability)', {
      user: cred.user, remoteHttp
    });
    return { adopted: true, user: cred.user, remoteHttp };
  } catch (err) {
    log.warn('Credential adoption from Caddyfile failed (non-fatal)', { error: err.message });
    return { adopted: false, reason: `error: ${err.message}` };
  }
}

/**
 * Replace the bcrypt hash on the basic_auth credential line(s) of an existing
 * Caddyfile, in place — the content primitive behind scripts/reset-admin.js's
 * no-permanent-lockout guarantee. Matches the credential LINE rather than the
 * block wrapper, so it patches both the TangleClaw-generated inline gate and a
 * hand-edited snippet form without re-deriving the whole file (the live Caddyfile
 * is operator-owned; reset must not reshape it).
 *
 * Header invariant: when the input is an integrity-stamped generated file, the
 * sha256 header is recomputed so it stays "generated" (the cutover keeps treating
 * it as safe-to-regenerate). A hand-edited file's first line is left untouched so
 * the cutover clobber-guard keeps protecting it — reset never silently converts a
 * hand-edited file into a clobberable one.
 *
 * @param {string} content - Existing Caddyfile text.
 * @param {object} opts
 * @param {string} opts.hash - New bcrypt hash (must match BCRYPT_HASH_RE).
 * @param {string} [opts.user] - Restrict the replacement to this username.
 *   Required to disambiguate when the file carries more than one distinct user.
 * @returns {{ content: string, user: string, replaced: number }} New content, the
 *   username whose credential was reset, and how many lines changed (>1 when the
 *   same user gates multiple site blocks, e.g. local + public domain).
 */
function replaceBasicAuthCredential(content, opts = {}) {
  if (typeof content !== 'string') {
    throw new Error('replaceBasicAuthCredential: content (string) is required');
  }
  const { hash } = opts;
  if (!hash || !BCRYPT_HASH_RE.test(hash)) {
    throw new Error('replaceBasicAuthCredential: a valid bcrypt hash is required');
  }
  const wantUser = typeof opts.user === 'string' && opts.user.length ? opts.user : null;

  // Generated files have a stamped header on line 1 that vouches for the body; we
  // patch the body and re-stamp. Hand-edited files are patched whole, header intact.
  const generated = isGeneratedCaddyfile(content);
  let prefix = '';
  let target = content;
  if (generated) {
    const nl = content.indexOf('\n');
    prefix = content.slice(0, nl + 1); // header line + its newline
    target = content.slice(nl + 1);
  }

  // Discover the credential lines and their usernames (matchAll resets lastIndex).
  const matches = [...target.matchAll(CREDENTIAL_LINE_RE)];
  if (matches.length === 0) {
    throw new Error('replaceBasicAuthCredential: no basic_auth credential found in Caddyfile');
  }
  const users = [...new Set(matches.map((m) => m[2]))];
  let resolvedUser;
  if (wantUser) {
    if (!users.includes(wantUser)) {
      throw new Error(`replaceBasicAuthCredential: no credential for user '${wantUser}' (found: ${users.join(', ')})`);
    }
    resolvedUser = wantUser;
  } else {
    if (users.length > 1) {
      throw new Error(`replaceBasicAuthCredential: multiple users present (${users.join(', ')}); specify which with user`);
    }
    resolvedUser = users[0];
  }

  let replaced = 0;
  const newTarget = target.replace(CREDENTIAL_LINE_RE, (line, indent, user, sep, _oldHash, trail) => {
    if (user !== resolvedUser) return line; // leave other users untouched
    replaced++;
    return `${indent}${user}${sep}${hash}${trail}`;
  });

  const newContent = generated ? `${_makeHeaderLine(newTarget)}\n${newTarget}` : prefix + newTarget;
  return { content: newContent, user: resolvedUser, replaced };
}

module.exports = {
  detectCaddy,
  buildCaddyfileContent,
  writeCaddyfile,
  validateCaddyfile,
  getCaddyfilePath,
  getTtydSocketPath,
  ttydConnectTarget,
  isGeneratedCaddyfile,
  getStagedCertsDir,
  stageCert,
  validateAdminPassword,
  hashPassword,
  replaceBasicAuthCredential,
  listBasicAuthUsers,
  extractBasicAuthCredential,
  hasRemoteHttpCatchAll,
  adoptCredentialIntoConfig,
  ADMIN_PASSWORD_MIN_LENGTH,
  BCRYPT_HASH_RE,
  GENERATED_MARKER
};
