'use strict';

/**
 * Project Master (chunk G, #331) — ONE persistent global AI assistant above
 * all projects: a read-only cross-project control plane.
 *
 * Architecture (ratified 2026-06-16, spec .prawduct/artifacts/g-project-master.md):
 * the master is HARNESS-SESSION-BACKED — a persistent Claude Code session in a
 * reserved tmux session, NOT a TC-owned LLM chat loop. It lives in a dedicated
 * home directory (`~/.tangleclaw/master/` — never a repo clone, which would
 * share git HEAD with dev sessions) and talks to TC through the HTTP API.
 *
 * Deliberately NOT a `sessions` table row and NOT a project: the wrap
 * pipeline, idle watchdog, dashboard cards, and ownership objects all key on
 * projects, and none of them apply — the master is a parallel singleton with
 * its own two API routes. Its identity ships as a TC-generated CLAUDE.md in
 * the master home (Claude Code reads it natively — no prime/hook delivery
 * machinery), regenerated on every ensure so guide/token changes propagate.
 *
 * v1 read-only boundary is INSTRUCTIONAL (CLAUDE.md rules + no repo checkout
 * by construction) — TC's mutation endpoints stay open on the direct
 * localhost listener by design (single-operator posture). Enforcement via a
 * scoped token is a G2+ concern.
 */

const fs = require('node:fs');
const path = require('node:path');
const os = require('node:os');
const tmux = require('./tmux');
const store = require('./store');
const engines = require('./engines');
const sessions = require('./sessions');
const { createLogger } = require('./logger');
const { effectiveServerProtocol } = require('./https-setup');

const log = createLogger('master');

/** Reserved tmux session name for the Project Master. Never collides with
 *  project sessions: project tmux names come from project records, and the
 *  session machinery never sees this name (no `sessions` row). */
const MASTER_TMUX_SESSION = 'tangleclaw-master';

/**
 * Resolve the master's home directory (its session cwd and identity root).
 * @returns {string} Absolute path to the master home
 */
function masterHome() {
  return path.join(os.homedir(), '.tangleclaw', 'master');
}

/**
 * Build the master's CLAUDE.md identity file content.
 *
 * Pure. Mirrors the per-project generated-config conventions: a marker header
 * (so hand-edits are visibly futile), the TC API base URL, and — when the
 * AUTH-4 M2M gate is on — the bearer-token Authentication block for the gated
 * PortHub/shared-docs surfaces (same contract as engines._serviceTokenAuthLines).
 *
 * @param {object} config - Global config (store.config.load())
 * @returns {string} CLAUDE.md content
 */
function buildMasterClaudeMd(config) {
  const serverPort = config.serverPort || 3101;
  // ENG-5R2W: must match what the server actually serves (caddy mode / no-cert
  // installs bind plain HTTP even with httpsEnabled), not the raw flag.
  const serverProtocol = effectiveServerProtocol(config);
  const baseUrl = `${serverProtocol}://localhost:${serverPort}`;
  const tokenActive = !!(config.serviceTokenEnabled && config.serviceToken);

  const lines = [
    '<!-- Generated by TangleClaw — Project Master identity. Regenerated on every',
    '     master ensure; hand-edits will be overwritten. -->',
    '',
    '# CLAUDE.md — TangleClaw Project Master',
    '',
    'You are the **TangleClaw Project Master**: the read-only administrator of this',
    'whole TangleClaw instance, above all projects. You answer cross-project',
    'questions ("which projects have open PRs?", "what is stale?", "what sessions',
    'are live?") by querying the TangleClaw HTTP API. You are NOT a project',
    'session: you have no project checkout, you own no code, and you never wrap.',
    '',
    '## Hard rules (v1 boundary)',
    '',
    '- **Read-only.** Use only GET endpoints. Never call mutating endpoints',
    '  (POST/PATCH/DELETE) — including session launch/kill/wrap, config changes,',
    '  port leases, and shared-doc locks. When an action is needed, describe the',
    '  exact step for the operator to take instead.',
    '- **Never edit files outside this directory.** Your home is your only',
    '  writable surface (notes, scratch). You have no project working tree by',
    '  design — do not go looking for one.',
    '- For per-project code questions, direct the operator to that project\'s own',
    '  session; you report status, you do not do project work.',
    '',
    `**TangleClaw API base URL**: \`${baseUrl}\``,
    ''
  ];

  if (tokenActive) {
    lines.push(
      '## Authentication',
      '',
      'The PortHub (`/api/ports*`) and shared-docs (`/api/shared-docs*`) surfaces',
      'require a bearer token. Send this header on those requests:',
      '',
      '```',
      `Authorization: Bearer ${config.serviceToken}`,
      '```',
      ''
    );
  }

  lines.push(
    '## Read API quick reference',
    '',
    `- \`GET /api/projects\` — all projects (engine, archived, groups).`,
    `- \`GET /api/sessions/:project/status\` — a project's live-session state.`,
    `- \`GET /api/activity\` — recent cross-project activity feed.`,
    `- \`GET /api/server-info\` — server sha/uptime/staleness.`,
    `- \`GET /api/system\` — host/system snapshot.`,
    `- \`GET /api/engines\` — configured engines.`,
    `- \`GET /api/ports\` — the PortHub port registry${tokenActive ? ' (bearer token)' : ''}.`,
    `- \`GET /api/shared-docs?groupId=<id>\` — a group's shared docs${tokenActive ? ' (bearer token)' : ''}.`,
    `- \`GET /api/continuity/:project/search?q=\` — search a project's session history.`,
    '',
    'Prefer `curl -s` + `jq`-style summaries; report concisely with project names.',
    ''
  );

  return lines.join('\n');
}

/**
 * Ensure the Project Master session exists — idempotent.
 *
 * Always: creates the master home and (re)generates its CLAUDE.md identity.
 * When the reserved tmux session is absent: creates it (cwd = master home)
 * and starts the default engine's launch command in it. Never touches an
 * already-running master (no kill/adopt semantics in v1 — the operator owns
 * restarts via tmux).
 *
 * @param {object} [options]
 * @param {string} [options.home] - Master home override (tests)
 * @param {object} [options.tmuxLib] - tmux module override (tests)
 * @param {object} [options.enginesLib] - engines module override (tests)
 * @returns {{created: boolean, tmuxSession: string, home: string, error?: string}}
 */
function ensureMasterSession(options = {}) {
  const t = options.tmuxLib || tmux;
  const eng = options.enginesLib || engines;
  const home = options.home || masterHome();
  fs.mkdirSync(home, { recursive: true });

  const config = store.config.load();
  fs.writeFileSync(path.join(home, 'CLAUDE.md'), buildMasterClaudeMd(config));

  if (t.hasSession(MASTER_TMUX_SESSION)) {
    return { created: false, tmuxSession: MASTER_TMUX_SESSION, home };
  }

  const engineId = config.defaultEngine || 'claude';
  const engineProfile = store.engines.get(engineId);
  if (!engineProfile) {
    return { created: false, tmuxSession: MASTER_TMUX_SESSION, home, error: `Engine "${engineId}" not found` };
  }
  const det = eng.detectEngine(engineProfile);
  if (!det.available) {
    return { created: false, tmuxSession: MASTER_TMUX_SESSION, home, error: `Engine "${engineId}" not available (binary not found)` };
  }

  // Generic engine launch command (shellCommand + args). No project → the
  // OpenClaw branch and orchestration overlays never apply. An available
  // engine with no launch profile would otherwise start a bare shell while
  // reporting created:true — refuse instead (honest degradation).
  const launchCmd = sessions._buildLaunchCommand(engineProfile, null, null);
  if (!launchCmd) {
    return { created: false, tmuxSession: MASTER_TMUX_SESSION, home, error: `Engine "${engineId}" has no launch command` };
  }

  try {
    const created = t.createSession(MASTER_TMUX_SESSION, {
      cwd: home,
      command: launchCmd,
      env: engineProfile.launch ? engineProfile.launch.env : {}
    });
    if (!created) {
      return { created: false, tmuxSession: MASTER_TMUX_SESSION, home, error: `Failed to create tmux session "${MASTER_TMUX_SESSION}"` };
    }
  } catch (err) {
    return { created: false, tmuxSession: MASTER_TMUX_SESSION, home, error: `tmux error: ${err.message}` };
  }

  log.info('Project Master session launched', { tmuxSession: MASTER_TMUX_SESSION, home, engine: engineId });
  return { created: true, tmuxSession: MASTER_TMUX_SESSION, home };
}

/**
 * Report whether the Project Master session is alive. Truth comes from tmux —
 * there is no DB row to drift from reality.
 * @param {object} [options]
 * @param {object} [options.tmuxLib] - tmux module override (tests)
 * @returns {{exists: boolean, tmuxSession: string, home: string}}
 */
function getMasterStatus(options = {}) {
  const t = options.tmuxLib || tmux;
  return { exists: t.hasSession(MASTER_TMUX_SESSION), tmuxSession: MASTER_TMUX_SESSION, home: masterHome() };
}

module.exports = { MASTER_TMUX_SESSION, masterHome, buildMasterClaudeMd, ensureMasterSession, getMasterStatus };
