'use strict';

/**
 * An opt-in, per-project provenance line ("Built by TangleClaw (Project: X)")
 * on the files TangleClaw generates whole and keeps private (ADR 0019).
 *
 * WHY A REGISTRY AND NOT "EVERY FILE WE WRITE". Writing a file is not owning
 * it. TangleClaw also writes managed blocks inside files the operator owns,
 * JSON a parser reads, and state nobody should see a comment in. A file gets a
 * provenance line only when its writer passes a `surfaceId` that `REGISTRY`
 * names; nothing is inferred from an extension, a path, or the fact of the
 * write. Adding a surface is a registry entry with its own tests, never a
 * side effect of routing a writer through here.
 *
 * WHY THE LINE CAN NEVER LOOK LIKE AN OWNERSHIP MARKER. `Generated by
 * TangleClaw` in a carrier's first three lines is read as permission to
 * overwrite that whole file (`lib/engines.js` retire path, `_looksGenerated` in
 * the wrap). A template, or a project name substituted into one, that could
 * produce that sentence would let a provenance line grant write authority over
 * a file. So templates are bounded data with a closed placeholder set, the
 * substituted values are neutralized the same way, and anything that still
 * contains a reserved marker renders as a fixed line with no values at all.
 *
 * Off by default, and byte-neutral while off: with the setting disabled,
 * `applyProvenance` returns the content it was given.
 *
 * Deliberately a leaf: `node:` built-ins and two dependency-free project
 * modules only, so any writer can require it without pulling in the store.
 */

const path = require('node:path');
const fs = require('node:fs');
const stagedWrite = require('./staged-write');
const tcProjectFiles = require('./tangleclaw-project-files');

/** The token that identifies a provenance line, and the only thing replace and remove key on. */
const SENTINEL = 'tangleclaw:provenance';

/** The shipped line. A missing, null or blank override resolves to it. */
const DEFAULT_TEMPLATE = 'Built by TangleClaw (Project: {project})';

/**
 * What renders when the substituted text would contain a reserved marker. It
 * carries no values, so no project or engine name can reach it.
 */
const FALLBACK_TEXT = 'Built by TangleClaw';

/** Longest override accepted. A provenance line is a label, not a paragraph. */
const TEMPLATE_MAX_LENGTH = 120;

/** Longest substituted value, so a long project name cannot turn the line into a wall. */
const VALUE_MAX_LENGTH = 80;

/**
 * Longest rendered text. The template and each value are bounded, but a
 * template may repeat a placeholder, so the product is bounded here too. A
 * surface whose reader has a size cap reserves `lineOverhead` against it, and
 * that reservation is only meaningful if the line has a ceiling.
 */
const RENDERED_MAX_LENGTH = TEMPLATE_MAX_LENGTH + VALUE_MAX_LENGTH;

/**
 * The only placeholders a template may use. Each is stable and carries no
 * machine identity: `{version}` would rewrite every stamped file on every
 * upgrade, and hosts, paths and ids name the machine or the install.
 */
const PLACEHOLDERS = Object.freeze(['project', 'engine']);

/**
 * Text other code reads as a claim of ownership or as a block delimiter. None
 * may appear in a rendered provenance line, compared case-insensitively.
 * `test/provenance.test.js` pins the entries owned by other modules to their
 * source constants, so a renamed marker there cannot silently drop out here.
 */
const RESERVED_MARKERS = Object.freeze([
  'Generated by TangleClaw',
  'TangleClaw: INACTIVE',
  'BEGIN:tangleclaw',
  'END:tangleclaw',
  'TC-OWNED-HOOK',
  SENTINEL,
  'TANGLECLAW:PRIMING-ROLL',
  'tangleclaw-state'
]);

/**
 * Sequences that open or close a comment in a syntax the registry supports or
 * may. `--!>` is here because HTML ends a comment on it too.
 */
const COMMENT_DELIMITERS = Object.freeze(['<!--', '-->', '--!>', '/*', '*/']);

/** How each supported syntax wraps one line of text as a comment. */
const COMMENT_FORMS = Object.freeze({
  markdown: Object.freeze({ render: (text) => `<!-- ${text} -->`, match: /^<!-- tangleclaw:provenance(?: [^\n]*)? -->$/ }),
  hash: Object.freeze({ render: (text) => `# ${text}`, match: /^# tangleclaw:provenance(?: [^\n]*)?$/ })
});

/**
 * The surfaces that may carry a provenance line, keyed by the id their writer
 * passes. `relPath` is a sanity check on the destination, never the grant.
 * `placement: 'top'` puts the line first.
 */
const REGISTRY = Object.freeze({
  'session-prime': Object.freeze({
    relPath: tcProjectFiles.SESSION_PRIME_RELPATH,
    syntax: 'markdown',
    placement: 'top'
  })
});

/** Staging-file prefix for `writeOwnedFile`, distinct from every other staged writer's. */
const STAGING_PREFIX = '.tc-provenance-';

// C0 controls, DEL, C1 controls, and the Unicode line and paragraph separators:
// anything that could end the line a comment lives on.
// eslint-disable-next-line no-control-regex
const CONTROL_CHARS = /[\u0000-\u001f\u007f-\u009f\u2028\u2029]/;
// eslint-disable-next-line no-control-regex
const CONTROL_CHARS_GLOBAL = /[\u0000-\u001f\u007f-\u009f\u2028\u2029]/g;

/**
 * The first reserved marker `text` contains, compared case-insensitively.
 *
 * @param {string} text
 * @returns {string|null}
 */
function _reservedMarkerIn(text) {
  const lower = text.toLowerCase();
  return RESERVED_MARKERS.find((m) => lower.includes(m.toLowerCase())) || null;
}

/**
 * Why `template` cannot be stored as an override, or null when it can.
 *
 * `null`, `undefined` and a blank string are accepted: each means "use the
 * default", which is how the operator resets an override.
 *
 * @param {unknown} template
 * @returns {string|null} A sentence naming the problem, or null.
 */
function validateTemplate(template) {
  if (template === null || template === undefined) return null;
  if (typeof template !== 'string') return 'template must be a string or null';
  const t = template.trim();
  if (t === '') return null;
  if (t.length > TEMPLATE_MAX_LENGTH) return `template must be at most ${TEMPLATE_MAX_LENGTH} characters`;
  if (CONTROL_CHARS.test(t)) return 'template must be a single line with no control characters';
  const unknown = [...t.matchAll(/\{([^{}]*)\}/g)].map((m) => m[1]).filter((name) => !PLACEHOLDERS.includes(name));
  if (unknown.length > 0) {
    return `template placeholder {${unknown[0]}} is not supported (supported: ${PLACEHOLDERS.map((p) => `{${p}}`).join(', ')})`;
  }
  const stray = t.replace(/\{(project|engine)\}/g, '');
  if (stray.includes('{') || stray.includes('}')) return 'template has an unmatched { or }';
  const delimiter = COMMENT_DELIMITERS.find((d) => t.includes(d));
  if (delimiter) return `template must not contain the comment delimiter ${delimiter}`;
  const marker = _reservedMarkerIn(t);
  if (marker) return `template must not contain the reserved marker "${marker}"`;
  return null;
}

/**
 * This project's effective provenance setting.
 *
 * A missing or malformed setting is off. A missing, null or blank template is
 * the default; so is one hand-edited into something `validateTemplate`
 * refuses, reported through `warning` rather than rendered.
 *
 * @param {object|null|undefined} projConfig - A config as returned by `lib/project-config.js` `load`.
 * @returns {{enabled: boolean, template: string, templateSource: 'default'|'override'|'invalid', warning?: string}}
 */
function resolveProvenance(projConfig) {
  const raw = projConfig && projConfig.provenanceWatermark;
  const setting = raw && typeof raw === 'object' && !Array.isArray(raw) ? raw : {};
  const enabled = setting.enabled === true;
  const t = typeof setting.template === 'string' ? setting.template.trim() : '';
  if (t === '') return { enabled, template: DEFAULT_TEMPLATE, templateSource: 'default' };
  const problem = validateTemplate(t);
  if (problem) {
    return { enabled, template: DEFAULT_TEMPLATE, templateSource: 'invalid', warning: `provenanceWatermark.${problem}; using the default` };
  }
  return { enabled, template: t, templateSource: 'override' };
}

/**
 * A placeholder value made safe to sit inside a one-line comment: single-line,
 * no comment delimiter, bounded length. Reserved markers are handled after
 * substitution, over the whole line, since two values could form one together.
 *
 * @param {unknown} value
 * @returns {string}
 */
function _neutralizeValue(value) {
  let v = value === null || value === undefined ? '' : String(value);
  v = v.replace(CONTROL_CHARS_GLOBAL, ' ');
  // `<` and `>` open and close the HTML comment; `/*` and `*/` a block comment.
  v = v.replace(/</g, '‹').replace(/>/g, '›').replace(/\/\*/g, '/ *').replace(/\*\//g, '* /');
  v = v.replace(/\s+/g, ' ').trim();
  if (v.length > VALUE_MAX_LENGTH) v = `${v.slice(0, VALUE_MAX_LENGTH - 1)}…`;
  return v;
}

/**
 * The provenance text for a template and its values, never containing a
 * reserved marker or anything that ends the comment it will sit in.
 *
 * One pass with a replacer function, so a value that itself reads `{engine}`
 * is inserted literally and never substituted again.
 *
 * @param {string} template - A template `validateTemplate` accepts.
 * @param {{project?: string, engine?: string}} values
 * @returns {string}
 */
function renderText(template, values) {
  const text = template.replace(/\{(project|engine)\}/g, (_, name) => _neutralizeValue(values && values[name]));
  if (text.length > RENDERED_MAX_LENGTH || _reservedMarkerIn(text)
      || COMMENT_DELIMITERS.some((d) => text.includes(d)) || CONTROL_CHARS.test(text)) {
    return FALLBACK_TEXT;
  }
  return text;
}

/**
 * One provenance line in `syntax`'s comment form, sentinel first.
 *
 * @param {'markdown'|'hash'} syntax
 * @param {string} text - From `renderText`.
 * @returns {string} The line, without a line ending.
 */
function renderLine(syntax, text) {
  const form = COMMENT_FORMS[syntax];
  if (!form) throw new Error(`provenance: no comment form for syntax "${syntax}"`);
  return form.render(`${SENTINEL} ${text}`);
}

/**
 * The registry entry for `surfaceId`. An unregistered id is a programming
 * error in the writer, not a runtime condition, so it throws.
 *
 * @param {string} surfaceId
 * @returns {{relPath: string, syntax: string, placement: string}}
 */
function _entry(surfaceId) {
  const entry = Object.prototype.hasOwnProperty.call(REGISTRY, surfaceId) ? REGISTRY[surfaceId] : null;
  if (!entry) throw new Error(`provenance: "${surfaceId}" is not a registered surface`);
  return entry;
}

/**
 * `content` with this surface's provenance line removed from its placement,
 * then re-inserted when the project has the setting on.
 *
 * Only the placement line is examined, never the rest of the file: generated
 * content may legitimately quote the sentinel, and removing a quotation is not
 * this function's business. Re-applying to its own output changes nothing.
 *
 * @param {string} surfaceId - A `REGISTRY` key.
 * @param {string} content - The file content the writer generated.
 * @param {{config?: object, project?: string, engine?: string}} ctx - The
 *   project's loaded config, and the values for the placeholders.
 * @returns {string}
 */
function applyProvenance(surfaceId, content, ctx = {}) {
  const entry = _entry(surfaceId);
  const form = COMMENT_FORMS[entry.syntax];
  let body = content;
  const newline = body.indexOf('\n');
  const first = newline === -1 ? body : body.slice(0, newline);
  if (form.match.test(first.replace(/\r$/, ''))) {
    body = newline === -1 ? '' : body.slice(newline + 1);
  }
  const setting = resolveProvenance(ctx.config);
  if (!setting.enabled) return body;
  const line = renderLine(entry.syntax, renderText(setting.template, { project: ctx.project, engine: ctx.engine }));
  return `${line}\n${body}`;
}

/**
 * How many characters `applyProvenance` adds to fresh content for this
 * surface and project: the line and its newline, or 0 when the setting is off.
 *
 * For a writer whose reader has a size cap, such as the session prime, which the
 * engine's startup hook discards whole when it is over its limit. That writer
 * must fit its content to the cap minus this, because the line is added after
 * the content is final.
 *
 * @param {string} surfaceId - A `REGISTRY` key.
 * @param {{config?: object, project?: string, engine?: string}} ctx - As for `applyProvenance`.
 * @returns {number}
 */
function lineOverhead(surfaceId, ctx = {}) {
  return applyProvenance(surfaceId, '', ctx).length;
}

/**
 * Write a registered surface's content, with its provenance line applied, so
 * no reader observes a partial file. Creates the parent directory.
 *
 * Throws what the write throws; whether that is fatal is the caller's call.
 *
 * @param {string} absPath - The destination.
 * @param {string} surfaceId - A `REGISTRY` key.
 * @param {string} content - The generated content, without a provenance line.
 * @param {{config?: object, project?: string, engine?: string}} ctx
 * @returns {void}
 */
function writeOwnedFile(absPath, surfaceId, content, ctx = {}) {
  const entry = _entry(surfaceId);
  const expected = entry.relPath.split('/').join(path.sep);
  if (!absPath.endsWith(path.sep + expected)) {
    throw new Error(`provenance: surface "${surfaceId}" is ${entry.relPath}, not ${absPath}`);
  }
  fs.mkdirSync(path.dirname(absPath), { recursive: true });
  stagedWrite.writeAtomic(absPath, applyProvenance(surfaceId, content, ctx), STAGING_PREFIX);
}

module.exports = {
  SENTINEL,
  DEFAULT_TEMPLATE,
  FALLBACK_TEXT,
  TEMPLATE_MAX_LENGTH,
  VALUE_MAX_LENGTH,
  RENDERED_MAX_LENGTH,
  STAGING_PREFIX,
  PLACEHOLDERS,
  RESERVED_MARKERS,
  COMMENT_FORMS,
  REGISTRY,
  validateTemplate,
  resolveProvenance,
  renderText,
  renderLine,
  applyProvenance,
  lineOverhead,
  writeOwnedFile
};
